import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
	collectBlocksFromDirectory,
	extractBlocksFromSource as extractMarkedBlocksFromSource,
	renderMarkdownTemplate,
} from "../scripts/doc-blocks";

const GENERATED_NOTICE =
	"<!-- This file is generated by `npm run generate:readme`. Do not edit README.md by hand. -->\n\n";
const README_MARKER_PREFIX = "README_BLOCK";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const defaultExamplesDir = join(scriptDir, "examples");
const defaultTemplatePath = join(scriptDir, "README.template.md");
const defaultReadmePath = resolve(scriptDir, "..", "README.md");
const isMainModule =
	process.argv[1] !== undefined &&
	resolve(process.argv[1]) === fileURLToPath(import.meta.url);

export function extractBlocksFromSource(
	sourceText: string,
	filePath: string,
): Map<string, string> {
	return extractMarkedBlocksFromSource(sourceText, filePath, {
		markerPrefix: README_MARKER_PREFIX,
	});
}

export function collectExampleBlocks(
	examplesDir = defaultExamplesDir,
): Map<string, string> {
	return collectBlocksFromDirectory({
		examplesDir,
		markerPrefix: README_MARKER_PREFIX,
	});
}

export function renderReadmeTemplate(
	templateText: string,
	blocks: Map<string, string>,
): string {
	return `${`${GENERATED_NOTICE}${renderMarkdownTemplate({
		blocks,
		markerPrefix: README_MARKER_PREFIX,
		templateText,
	})}`.trimEnd()}\n`;
}

export function buildReadme(options?: {
	examplesDir?: string;
	templatePath?: string;
}) {
	const templatePath = options?.templatePath ?? defaultTemplatePath;
	const examplesDir = options?.examplesDir ?? defaultExamplesDir;
	const templateText = readFileSync(templatePath, "utf8");
	const blocks = collectExampleBlocks(examplesDir);

	return renderReadmeTemplate(templateText, blocks);
}

export function writeReadme(options?: {
	examplesDir?: string;
	outputPath?: string;
	templatePath?: string;
}) {
	const outputPath = options?.outputPath ?? defaultReadmePath;
	const readme = buildReadme(options);

	writeFileSync(outputPath, readme);

	return readme;
}

if (isMainModule) {
	writeReadme();
}
