import { fileURLToPath } from "node:url";
import { type ArtifactDraft, defineCodegen, runCodegenCommand } from "codegen";
import { dumlingRoutes } from "dumling/codegen";
import { readingKnowledgeSchema } from "dumrel/schema";
import { z } from "zod";
import {
	breakdownRecordFileSchema,
	recordFileSchema,
	textRecordFileSchema,
} from "../src/record-schema.js";

// Emits one record JSON Schema per language, with each target's route and
// Attestation drawn from Dumling's per-route schemas and its Reading Knowledge
// from dumrel's schema, one Breakdown Record Schema per language, with its
// Locution and Saying Lemmas and Lexeme routes and Attestations, and one for
// Text Records, so a record's `$schema` gives editors completion and
// validation. Also emits `src/generated/routes.ts`, each language's routes,
// which the loader checks a target's route against without its Attestation.
type Target = "schema" | "generated";
const artifacts: ArtifactDraft<Target, null>[] = [];

function write(target: Target, path: string, content: string) {
	artifacts.push({
		id: `${target}/${path}`,
		to: { target, path },
		content,
		provenance: [],
		meta: null,
	});
}

const emit = (name: string, schema: object) =>
	write("schema", `${name}.json`, `${JSON.stringify(schema, null, "\t")}\n`);

const routesByLanguage: Record<string, { family: string; kind: string }[]> = {};

for (const language of ["de", "en", "he"] as const) {
	const schemas = await Promise.all(
		dumlingRoutes
			.filter((route) => route.language === language)
			.map(async (route) => ({
				...route,
				...((await import(`dumling/schema/${route.schemaPath}`)) as {
					lemmaSchema: z.ZodType;
					attestationSchema: z.ZodType;
				}),
			})),
	);
	const union = (members: z.ZodType[], of: string) => {
		const [first, ...rest] = members;
		if (!first) throw Error(`Dumling has no ${language} ${of}`);
		return rest.length === 0 ? first : z.union([first, ...rest]);
	};
	const routeSchemas = (from: typeof schemas) =>
		from.map(({ family, kind }) =>
			z.strictObject({
				family: z.literal(family),
				kind: z.literal(kind),
			}),
		);
	routesByLanguage[language] = schemas
		.map(({ family, kind }) => ({ family, kind }))
		.toSorted((a, b) =>
			`${a.family}/${a.kind}` < `${b.family}/${b.kind}` ? -1 : 1,
		);
	const lexemes = schemas.filter(({ family }) => family === "Lexeme");
	const { $schema, ...body } = z.toJSONSchema(
		recordFileSchema({
			route: union(routeSchemas(schemas), "routes"),
			attestation: union(
				schemas.map((schema) => schema.attestationSchema),
				"routes",
			),
			knowledge: readingKnowledgeSchema,
		}),
		{ io: "input", unrepresentable: "any", reused: "ref" },
	);
	emit(`spec-record.${language}`, {
		$schema,
		$id: `https://unpkg.com/dumcorpus/schema/spec-record.${language}.json`,
		title: `Dumcorpus ${language} Spec Record`,
		...body,
	});
	const { $schema: breakdownSchema, ...breakdownBody } = z.toJSONSchema(
		breakdownRecordFileSchema(
			union(
				schemas
					.filter(
						({ family }) =>
							family === "Locution" || family === "Saying",
					)
					.map((schema) => schema.lemmaSchema),
				"Locution or Saying routes",
			),
			{
				route: union(routeSchemas(lexemes), "Lexeme routes"),
				attestation: union(
					lexemes.map((schema) => schema.attestationSchema),
					"Lexeme routes",
				),
				knowledge: readingKnowledgeSchema,
			},
		),
		{ io: "input", unrepresentable: "any", reused: "ref" },
	);
	emit(`breakdown-record.${language}`, {
		$schema: breakdownSchema,
		$id: `https://unpkg.com/dumcorpus/schema/breakdown-record.${language}.json`,
		title: `Dumcorpus ${language} Breakdown Record`,
		...breakdownBody,
	});
}
const { $schema, ...body } = z.toJSONSchema(textRecordFileSchema, {
	io: "input",
});
emit("text-record", {
	$schema,
	$id: "https://unpkg.com/dumcorpus/schema/text-record.json",
	title: "Dumcorpus Text Record",
	...body,
});
write(
	"generated",
	"routes.ts",
	[
		"// Generated by codegen/generate-record-schemas.ts from Dumling's route",
		"// schemas. Run bun run generate.",
		"",
		'import type * as Dumling from "dumling/types";',
		"",
		"/** Each language's routes, sorted by `<Family>/<Kind>`. */",
		"export const unitRoutes: {",
		"\treadonly [L in Dumling.Language]: readonly Extract<",
		"\t\tDumling.LemmaRoute,",
		"\t\t{ language: L }",
		"\t>[];",
		"} = {",
		...Object.entries(routesByLanguage).flatMap(([language, routes]) => [
			`\t${language}: [`,
			...routes.map(
				({ family, kind }) =>
					`\t\t{ language: ${JSON.stringify(language)}, family: ${JSON.stringify(family)}, kind: ${JSON.stringify(kind)} },`,
			),
			"\t],",
		]),
		"};",
		"",
	].join("\n"),
);
const recipe = defineCodegen({
	inputs: {},
	outputs: {
		schema: { root: fileURLToPath(new URL("../schema/", import.meta.url)) },
		generated: {
			root: fileURLToPath(new URL("../src/generated/", import.meta.url)),
		},
	},
	build: () => artifacts,
});
await runCodegenCommand(recipe, { label: "Dumcorpus record schemas" });
