// PROTOTYPE ONLY — fixed segmentation-chain-v1 corpus copied from issue #3.

export const KINDS = [
	"ResolvableText",
	"OpaqueText",
	"Whitespace",
	"Punctuation",
] as const;

export type Kind = (typeof KINDS)[number];
export type Decision = "Accepted" | "UnsupportedLanguage" | "Unintelligible";
export type Segment = { kind: Kind; text: string };
export type CorpusCase = {
	id: string;
	className: string;
	source: string;
	decision: Decision;
	segments?: readonly Segment[];
};

const R = (text: string): Segment => ({ kind: "ResolvableText", text });
const O = (text: string): Segment => ({ kind: "OpaqueText", text });
const W = (text: string): Segment => ({ kind: "Whitespace", text });
const P = (text: string): Segment => ({ kind: "Punctuation", text });

export const CORPUS: readonly CorpusCase[] = [
	{
		id: "DE-CLEAN-01",
		className: "clean German",
		source: "Heute regnet es.",
		decision: "Accepted",
		segments: [R("Heute"), W(" "), R("regnet"), W(" "), R("es"), P(".")],
	},
	{
		id: "DE-CLEAN-02",
		className: "clean German",
		source: "Die Haustür steht offen.",
		decision: "Accepted",
		segments: [
			R("Die"),
			W(" "),
			R("Haustür"),
			W(" "),
			R("steht"),
			W(" "),
			R("offen"),
			P("."),
		],
	},
	{
		id: "DE-CLEAN-03",
		className: "clean German",
		source: "Zum Frühstück gibt es Brötchen.",
		decision: "Accepted",
		segments: [
			R("Zum"),
			W(" "),
			R("Frühstück"),
			W(" "),
			R("gibt"),
			W(" "),
			R("es"),
			W(" "),
			R("Brötchen"),
			P("."),
		],
	},
	{
		id: "DE-CLEAN-04",
		className: "clean German",
		source: "„Guten Morgen“, sagte sie.",
		decision: "Accepted",
		segments: [
			P("„"),
			R("Guten"),
			W(" "),
			R("Morgen"),
			P("“"),
			P(","),
			W(" "),
			R("sagte"),
			W(" "),
			R("sie"),
			P("."),
		],
	},
	{
		id: "DE-BOUND-01",
		className: "punctuation",
		source: "Hallo, Welt!",
		decision: "Accepted",
		segments: [R("Hallo"), P(","), W(" "), R("Welt"), P("!")],
	},
	{
		id: "DE-BOUND-02",
		className: "punctuation and whitespace",
		source: "Wirklich?!  Ja.\n",
		decision: "Accepted",
		segments: [
			R("Wirklich"),
			P("?"),
			P("!"),
			W("  "),
			R("Ja"),
			P("."),
			W("\n"),
		],
	},
	{
		id: "DE-BOUND-03",
		className: "punctuation inside text",
		source: "E-Mail-Adresse",
		decision: "Accepted",
		segments: [R("E"), P("-"), R("Mail"), P("-"), R("Adresse")],
	},
	{
		id: "DE-BOUND-04",
		className: "tab and repeated space",
		source: "Eins,\tzwei  drei.",
		decision: "Accepted",
		segments: [
			R("Eins"),
			P(","),
			W("\t"),
			R("zwei"),
			W("  "),
			R("drei"),
			P("."),
		],
	},
	{
		id: "DE-BOUND-05",
		className: "nested punctuation",
		source: "Er sagte: „Nein.“",
		decision: "Accepted",
		segments: [
			R("Er"),
			W(" "),
			R("sagte"),
			P(":"),
			W(" "),
			P("„"),
			R("Nein"),
			P("."),
			P("“"),
		],
	},
	{
		id: "DE-PRESERVE-01",
		className: "ordinary typo",
		source: "Das ist nähmlich schwierig.",
		decision: "Accepted",
		segments: [
			R("Das"),
			W(" "),
			R("ist"),
			W(" "),
			R("nähmlich"),
			W(" "),
			R("schwierig"),
			P("."),
		],
	},
	{
		id: "DE-PRESERVE-02",
		className: "ordinary typo",
		source: "Ich habe das garnicht gewusst.",
		decision: "Accepted",
		segments: [
			R("Ich"),
			W(" "),
			R("habe"),
			W(" "),
			R("das"),
			W(" "),
			R("garnicht"),
			W(" "),
			R("gewusst"),
			P("."),
		],
	},
	{
		id: "DE-PRESERVE-03",
		className: "licensed variant",
		source: "Der Delphin schwimmt schnell.",
		decision: "Accepted",
		segments: [
			R("Der"),
			W(" "),
			R("Delphin"),
			W(" "),
			R("schwimmt"),
			W(" "),
			R("schnell"),
			P("."),
		],
	},
	{
		id: "DE-PRESERVE-04",
		className: "licensed variants",
		source: "Das ist aufwändig und aufwendig.",
		decision: "Accepted",
		segments: [
			R("Das"),
			W(" "),
			R("ist"),
			W(" "),
			R("aufwändig"),
			W(" "),
			R("und"),
			W(" "),
			R("aufwendig"),
			P("."),
		],
	},
	{
		id: "RECON-01",
		className: "severe structural corruption",
		source: "Ichgeh heute nachHause.",
		decision: "Accepted",
		segments: [
			R("Ich"),
			W(" "),
			R("geh"),
			W(" "),
			R("heute"),
			W(" "),
			R("nach"),
			W(" "),
			R("Hause"),
			P("."),
		],
	},
	{
		id: "RECON-02",
		className: "severe structural corruption",
		source: "Wirkönnenmorgenkommen.",
		decision: "Accepted",
		segments: [
			R("Wir"),
			W(" "),
			R("können"),
			W(" "),
			R("morgen"),
			W(" "),
			R("kommen"),
			P("."),
		],
	},
	{
		id: "RECON-03",
		className: "required noisy atom case",
		source: "bra w u r him frfr",
		decision: "Accepted",
		segments: [
			R("braw"),
			W(" "),
			R("u"),
			W(" "),
			R("r"),
			W(" "),
			R("him"),
			W(" "),
			R("frfr"),
		],
	},
	{
		id: "RECON-04",
		className: "severe structural corruption",
		source: "HeuteistdasWettergut.",
		decision: "Accepted",
		segments: [
			R("Heute"),
			W(" "),
			R("ist"),
			W(" "),
			R("das"),
			W(" "),
			R("Wetter"),
			W(" "),
			R("gut"),
			P("."),
		],
	},
	{
		id: "MIXED-01",
		className: "accepted with local opaque text",
		source: "Ich treffe blorx morgen.",
		decision: "Accepted",
		segments: [
			R("Ich"),
			W(" "),
			R("treffe"),
			W(" "),
			O("blorx"),
			W(" "),
			R("morgen"),
			P("."),
		],
	},
	{
		id: "MIXED-02",
		className: "accepted with local opaque text",
		source: "Heute ist xqz!! alles gut.",
		decision: "Accepted",
		segments: [
			R("Heute"),
			W(" "),
			R("ist"),
			W(" "),
			O("xqz"),
			P("!"),
			P("!"),
			W(" "),
			R("alles"),
			W(" "),
			R("gut"),
			P("."),
		],
	},
	{
		id: "MIXED-03",
		className: "accepted with local opaque text",
		source: "Das ist 🫠 kompliziert.",
		decision: "Accepted",
		segments: [
			R("Das"),
			W(" "),
			R("ist"),
			W(" "),
			O("🫠"),
			W(" "),
			R("kompliziert"),
			P("."),
		],
	},
	{
		id: "UNINT-01",
		className: "unintelligible",
		source: "jfdksl qweoi zmxncb",
		decision: "Unintelligible",
	},
	{
		id: "UNINT-02",
		className: "unintelligible",
		source: "qxv zzkk rrppf",
		decision: "Unintelligible",
	},
	{
		id: "UNSUP-01",
		className: "valid unsupported Polish",
		source: "To jest piękny dzień.",
		decision: "UnsupportedLanguage",
	},
	{
		id: "UNSUP-02",
		className: "valid unsupported Spanish",
		source: "Mañana iremos al mercado.",
		decision: "UnsupportedLanguage",
	},
	{
		id: "HE-FUSED-01",
		className: "Hebrew visible fused prefixes",
		source: "הילד בבית.",
		decision: "Accepted",
		segments: [R("ה"), R("ילד"), W(" "), R("ב"), R("בית"), P(".")],
	},
	{
		id: "HE-FUSED-02",
		className: "Hebrew prefix and pronominal suffix",
		source: "וספרו נמצא כאן.",
		decision: "Accepted",
		segments: [
			R("ו"),
			R("ספר"),
			R("ו"),
			W(" "),
			R("נמצא"),
			W(" "),
			R("כאן"),
			P("."),
		],
	},
	{
		id: "HE-FUSED-03",
		className: "Hebrew object suffix",
		source: "אהבתיה.",
		decision: "Accepted",
		segments: [R("אהבתי"), R("ה"), P(".")],
	},
	{
		id: "HE-FUSED-04",
		className: "Hebrew stacked visible prefixes",
		source: "כשנגיע, נתקשר.",
		decision: "Accepted",
		segments: [
			R("כ"),
			R("ש"),
			R("נגיע"),
			P(","),
			W(" "),
			R("נתקשר"),
			P("."),
		],
	},
] as const;
