/**
 * Rebuilds the bundled Hebrew word list
 * (`src/concrete-lang/he/segmentation/word-list-data.ts`) from Wikidata's
 * Hebrew lexemes, which are CC0 1.0 (public domain dedication), so the list
 * can ship inside this MIT package without conditions.
 *
 * Every written form and lemma of a Hebrew lexeme becomes one unpointed word
 * with the prefix classes its lexical categories allow (`word-list.ts`). A
 * short reviewed supplement adds words the lexemes lack.
 *
 *     bun run generate:hebrew-word-list
 *
 * The script queries the live Wikidata Query Service; the output names the
 * retrieval date as its version.
 */
import { writeFile } from "node:fs/promises";
import { formatTypeScript } from "../../dumrel/codegen/format-typescript.js";
import {
	encodeHebrewWordList,
	normalizeHebrewWord,
	WordClass,
} from "../src/concrete-lang/he/segmentation/word-list.js";

const endpoint = "https://query.wikidata.org/sparql";
const output = new URL(
	"../src/concrete-lang/he/segmentation/word-list-data.ts",
	import.meta.url,
);

const nominal =
	WordClass.TakesPreposition |
	WordClass.TakesArticle |
	WordClass.TakesHiddenArticle;
const closedWithPreposition =
	WordClass.TakesPreposition | WordClass.FunctionWord;

/** Prefix classes by Wikidata lexical category; unlisted categories are skipped. */
const classesByCategory: Readonly<Record<string, number>> = {
	Q1084: nominal, // noun
	Q63116: nominal, // numeral
	Q147276: WordClass.TakesPreposition, // proper noun
	Q34698: WordClass.TakesArticle, // adjective
	Q24905: 0, // verb; present-tense forms also take the article
	Q380057: closedWithPreposition, // adverb
	Q36224: closedWithPreposition, // pronoun
	Q576271: closedWithPreposition, // determiner
	Q2304610: closedWithPreposition, // interrogative word
	Q4833830: WordClass.FunctionWord, // preposition
	Q36484: WordClass.FunctionWord, // conjunction
	Q83034: WordClass.FunctionWord, // interjection
	Q1478451: WordClass.FunctionWord, // negation
};
const verb = "Q24905";
const presentTense = "Q192613";

/** Reviewed words the lexemes lack, each needed by a Hebrew Spec Record. */
const supplement: Readonly<Record<string, number>> = {
	"דו״ח": nominal, // report; הדו"ח in hadoch-nichtav-etmol
};

const formsQuery = `SELECT ?cat ?rep (MAX(?present) AS ?p) WHERE {
  ?l dct:language wd:Q9288 ; wikibase:lexicalCategory ?cat ; ontolex:lexicalForm ?f .
  ?f ontolex:representation ?rep .
  BIND(EXISTS { ?f wikibase:grammaticalFeature wd:${presentTense} } AS ?present)
  FILTER(?cat CATEGORY)
} GROUP BY ?l ?cat ?rep`;
const lemmasQuery = `SELECT ?cat ?lemma WHERE {
  ?l dct:language wd:Q9288 ; wikibase:lexicalCategory ?cat ; wikibase:lemma ?lemma .
}`;
const lexemeCountQuery = `SELECT (COUNT(?l) AS ?n) WHERE { ?l dct:language wd:Q9288 . }`;

async function rows(query: string): Promise<string[][]> {
	const response = await fetch(
		`${endpoint}?query=${encodeURIComponent(query)}`,
		{
			headers: {
				Accept: "text/tab-separated-values",
				"User-Agent": "texteater-dumgen-hebrew-word-list/1.0",
			},
		},
	);
	if (!response.ok)
		throw Error(
			`Wikidata answered ${response.status}: ${await response.text()}`,
		);
	return (await response.text())
		.split("\n")
		.slice(1)
		.filter(Boolean)
		.map((line) => line.split("\t"));
}

const literal = (cell: string) =>
	cell.match(/^"(.*)"(?:@[\w-]+)?$/u)?.[1] ?? cell;
const entity = (cell: string) => cell.match(/entity\/(Q\d+)>$/u)?.[1] ?? "";

const words = new Map<string, number>();
const add = (written: string, classes: number) => {
	const word = normalizeHebrewWord(written);
	if (!/^[א-ת][א-ת׳״]*$/u.test(word)) return;
	words.set(word, (words.get(word) ?? 0) | classes);
};

// Nouns alone come close to the service's time limit, so they are one query.
const forms = [
	...(await rows(formsQuery.replace("CATEGORY", "= wd:Q1084"))),
	...(await rows(formsQuery.replace("CATEGORY", "!= wd:Q1084"))),
];
for (const [category = "", representation = "", present = ""] of forms) {
	const classes = classesByCategory[entity(category)];
	if (classes === undefined) continue;
	const participle = entity(category) === verb && present.includes("true");
	add(literal(representation), participle ? WordClass.TakesArticle : classes);
}
for (const [category = "", lemma = ""] of await rows(lemmasQuery)) {
	const classes = classesByCategory[entity(category)];
	if (classes !== undefined) add(literal(lemma), classes);
}
for (const [word, classes] of Object.entries(supplement)) add(word, classes);
const lexemes = literal((await rows(lexemeCountQuery))[0]?.[0] ?? "");

const retrieved = new Date().toISOString().slice(0, 10);
const encoded = encodeHebrewWordList(words);
const source = `/**
 * Generated by \`bun codegen/hebrew-word-list.ts\`; do not edit.
 *
 * Source: Wikidata lexicographical data, Hebrew lexemes
 * (https://www.wikidata.org/wiki/Wikidata:Lexicographical_data).
 * License: CC0 1.0 Universal (https://creativecommons.org/publicdomain/zero/1.0/).
 * Version: retrieved ${retrieved} from ${endpoint}; ${lexemes} lexemes,
 * ${words.size} unpointed words, plus ${Object.keys(supplement).length} reviewed supplement words.
 *
 * Each key is a set of WordClass flags; its value holds the words with exactly
 * those classes, sorted and front-coded in blocks (\`word-list.ts\`).
 */
export const hebrewWordListData: Readonly<Record<string, readonly string[]>> = ${JSON.stringify(encoded)};
`;
await writeFile(output, await formatTypeScript(source, output));
console.log(`Wrote ${words.size} Hebrew words from ${lexemes} lexemes.`);
