import type { FeatureNameTokenKey } from "./tiny-tokens";

export const concreteFeatureSchemaInventory = {
	featureNames: [
		"abbr",
		"adpType",
		"aspect",
		"case",
		"conjType",
		"definite",
		"degree",
		"discourseFormulaRole",
		"extPos",
		"foreign",
		"gender",
		"gender[psor]",
		"governedCase",
		"hasGovPrep",
		"hasSepPrefix",
		"historicalStatus",
		"hebBinyan",
		"hebExistential",
		"hyph",
		"lexicallyReflexive",
		"mood",
		"number",
		"number[psor]",
		"numForm",
		"numType",
		"orthography",
		"partType",
		"person",
		"phrasal",
		"polarity",
		"polite",
		"poss",
		"prefix",
		"pronType",
		"punctType",
		"reflex",
		"coverage",
		"spelling",
		"style",
		"tense",
		"variant",
		"verbForm",
		"verbType",
		"voice",
	],
	finiteFeatureValues: {
		abbr: ["Yes"],
		adpType: ["Circ", "Post", "Prep"],
		aspect: ["Perf"],
		case: ["Acc", "Dat", "Gen", "Nom", "Tem"],
		conjType: ["Comp"],
		definite: ["Cons", "Def", "Ind"],
		degree: ["Cmp", "Pos", "Sup"],
		discourseFormulaRole: [
			"Acknowledgment",
			"Apology",
			"Farewell",
			"Greeting",
			"Initiation",
			"Reaction",
			"Refusal",
			"Request",
			"Thanks",
			"Transition",
		],
		extPos: ["ADP", "ADV", "CCONJ", "DET", "PRON", "PROPN", "SCONJ"],
		foreign: ["Yes"],
		gender: ["Fem", "Masc", "Neut"],
		"gender[psor]": ["Fem", "Masc", "Neut"],
		governedCase: [
			"Abe",
			"Abl",
			"Acc",
			"Add",
			"Ade",
			"All",
			"Ben",
			"Cau",
			"Cmp",
			"Cns",
			"Com",
			"Dat",
			"Del",
			"Dis",
			"Ela",
			"Equ",
			"Ess",
			"Gen",
			"Ill",
			"Ine",
			"Ins",
			"Lat",
			"Loc",
			"Nom",
			"Par",
			"Per",
			"Sbe",
			"Sbl",
			"Spl",
			"Sub",
			"Sup",
			"Tem",
			"Ter",
		],
		historicalStatus: ["Archaic"],
		hebBinyan: [
			"HIFIL",
			"HITPAEL",
			"HUFAL",
			"NIFAL",
			"PAAL",
			"PIEL",
			"PUAL",
		],
		hebExistential: ["Yes"],
		hyph: ["Yes"],
		lexicallyReflexive: ["Yes"],
		mood: ["Imp", "Ind", "Sub"],
		number: ["Dual", "Plur", "Ptan", "Sing"],
		"number[psor]": ["Plur", "Sing"],
		numForm: ["Combi", "Digit", "Roman", "Word"],
		numType: ["Card", "Frac", "Mult", "Ord", "Range"],
		orthography: ["Typo"],
		partType: ["Inf", "Res", "Vbp"],
		person: ["1", "2", "3"],
		phrasal: ["Yes"],
		polarity: ["Neg", "Pos"],
		polite: ["Form", "Infm"],
		poss: ["Yes"],
		prefix: ["Yes"],
		pronType: [
			"Art",
			"Dem",
			"Emp",
			"Exc",
			"Ind",
			"Int",
			"Neg",
			"Prs",
			"Rcp",
			"Rel",
			"Tot",
		],
		punctType: [
			"Brck",
			"Colo",
			"Comm",
			"Dash",
			"Elip",
			"Excl",
			"Peri",
			"Qest",
			"Quot",
		],
		reflex: ["Yes"],
		coverage: ["Partial"],
		spelling: ["Variant"],
		style: ["Arch", "Coll", "Expr", "Slng", "Vrnc"],
		tense: ["Fut", "Past", "Pres"],
		variant: ["Short"],
		verbForm: ["Fin", "Ger", "Inf", "Part"],
		verbType: ["Cop", "Mod"],
		voice: ["Act", "Mid", "Pass"],
	},
} as const satisfies {
	featureNames: readonly FeatureNameTokenKey[];
	finiteFeatureValues: Partial<
		Record<FeatureNameTokenKey, readonly string[]>
	>;
};
