/** Generated by tooling/compile-relation-verdict.ts. Do not edit. */
export const COMPILED_RELATION_VERDICT = {
	"formatVersion": "tf-demo-compiled-relation-verdict-v2",
	"candidateId": "100b1cd5891c34ea363293ac0a4fb41b1caeeb41a74455a31b0a49d6b260fc68",
	"verdictArtifactPath": "battery/dumgen/docs/prototypes/german-relation-human-gate/verdict.json",
	"fingerprints": {
		"prompt": "sha256:9518dc27d59397718ca8568b9a930bf6990b90ea442b2cc2be564d166b1f78e0",
		"schema": "sha256:19c520d5c4a0171b87bd8b40adf4bd021567c02577960ddc91cb97e5819c7312",
		"evaluator": "sha256:835cdbfc9b41278ba9c6707a1a2e20112351b0947a1368e05eba822e5e7ed84c",
		"model": "sha256:dae3db292da3e761d1703cc0cba41843832c1357a1635f856e9fadcada0a67ec",
		"policy": "sha256:644954406851383eae91948d8cebb50546c20eeeaf1b367c58a5cc70ffcbcf76"
	},
	"historicalCandidate": {
		"candidateId": "100b1cd5891c34ea363293ac0a4fb41b1caeeb41a74455a31b0a49d6b260fc68",
		"originalVerdictArtifactPath": "battery/dumgen/docs/prototypes/german-relation-human-gate/verdict.json",
		"archivedArtifacts": [
			{
				"role": "retained-result",
				"commit": "e5060a0407252f25af801f59674f47a5aff71e55",
				"path": "battery/dumgen-new/docs/prototypes/german-relation-prompt-iteration-lab/runs/2026-08-20T17-05-28-531Z/results.json",
				"sha256": "c968b9096f17a5dc756b3784f685dcf5c38975628280ee88d4e8f9efb753c082"
			}
		],
		"fingerprints": {
			"prompt": "sha256:0896648f922dcb122a3d7f3956126a9b30d2964bdf04a187503bc8526980628a",
			"schema": "sha256:3562a451015bb9c16ae65e45792e5f5897ab4c118cbc7c76340ad38b11e7968d",
			"evaluator": "sha256:fdd2c95c575a1764918df1943c89b7a0ed3f29cac3c1e7dd35e0c7c4d7532f82",
			"model": "openai:gpt-5.6-luna:sha256:b8de968b038ede28ac0892743a7e2e76b4899eb4fce0e85e5c1c471cf82ea627",
			"policy": "candidate:100b1cd5891c34ea363293ac0a4fb41b1caeeb41a74455a31b0a49d6b260fc68:sha256:e411821b03992797c8dddae175727b03f7b97b29ddc405076632ac07e1709720"
		},
		"verdict": null
	},
	"invalidationReasons": [
		"archivedRunEvidence",
		"missingReviewedVerdictArtifact",
		"historicalCandidateRequiresReevaluation"
	],
	"verdict": null
} as const;
