/** Generated by tooling/compile-relation-verdict.ts. Do not edit. */
export const COMPILED_RELATION_VERDICT = {
	"formatVersion": "tf-demo-compiled-relation-verdict-v2",
	"candidateId": "100b1cd5891c34ea363293ac0a4fb41b1caeeb41a74455a31b0a49d6b260fc68",
	"verdictArtifactPath": "battery/dumgen/docs/prototypes/german-relation-human-gate/verdict.json",
	"fingerprints": {
		"prompt": "sha256:22fa229da8159ee578d42c985e5856c4d0aca247112a9c83dc28acc6ea1b7b8b",
		"schema": "sha256:3af36349093db14654a319490111c475cd7b004456d16583354c8d49bd3cd8f9",
		"evaluator": "sha256:0e6b1537051d40ff23766a469aa3727e1ad3906995f0b134f751b84551f89327",
		"model": "sha256:a3a99d0878ef227494e47c4f24c739b9e8744e5d64edebea42bebcdf6d8770bf",
		"policy": "sha256:7e9b85da697ffbb07927367ebbfe8ca3f74d69ea3b42ff5a90cd54a0d3993712"
	},
	"historicalCandidate": {
		"candidateId": "100b1cd5891c34ea363293ac0a4fb41b1caeeb41a74455a31b0a49d6b260fc68",
		"originalVerdictArtifactPath": "battery/dumgen/docs/prototypes/german-relation-human-gate/verdict.json",
		"archivedArtifacts": [
			{
				"role": "retained-result",
				"commit": "e5060a0407252f25af801f59674f47a5aff71e55",
				"path": "battery/dumgen-new/docs/prototypes/german-relation-prompt-iteration-lab/runs/2026-08-20T17-05-28-531Z/results.json",
				"sha256": "c968b9096f17a5dc756b3784f685dcf5c38975628280ee88d4e8f9efb753c082"
			}
		],
		"fingerprints": {
			"prompt": "sha256:0896648f922dcb122a3d7f3956126a9b30d2964bdf04a187503bc8526980628a",
			"schema": "sha256:3562a451015bb9c16ae65e45792e5f5897ab4c118cbc7c76340ad38b11e7968d",
			"evaluator": "sha256:fdd2c95c575a1764918df1943c89b7a0ed3f29cac3c1e7dd35e0c7c4d7532f82",
			"model": "openai:gpt-5.6-luna:sha256:b8de968b038ede28ac0892743a7e2e76b4899eb4fce0e85e5c1c471cf82ea627",
			"policy": "candidate:100b1cd5891c34ea363293ac0a4fb41b1caeeb41a74455a31b0a49d6b260fc68:sha256:e411821b03992797c8dddae175727b03f7b97b29ddc405076632ac07e1709720"
		},
		"verdict": null
	},
	"invalidationReasons": [
		"archivedRunEvidence",
		"missingReviewedVerdictArtifact",
		"historicalCandidateRequiresReevaluation"
	],
	"verdict": null
} as const;
