/** Generated by tooling/compile-relation-verdict.ts. Do not edit. */
export const COMPILED_RELATION_VERDICT = {
	"formatVersion": "tf-demo-compiled-relation-verdict-v2",
	"candidateId": "100b1cd5891c34ea363293ac0a4fb41b1caeeb41a74455a31b0a49d6b260fc68",
	"verdictArtifactPath": "battery/dumgen/docs/prototypes/german-relation-human-gate/verdict.json",
	"fingerprints": {
		"prompt": "sha256:a0c3d4a1d5339d59e902da153656f7f5b85d9f7dac45a0c60a3b8e17490ec279",
		"schema": "sha256:0cae0e2b25b803efad94a1d14165bf260ca616211773d8c8dba8b6f126f2a866",
		"evaluator": "sha256:f76a6494d0a254a3f06b3ffb9ed22d1eee4bb857ec605052603577e911675cf2",
		"model": "sha256:14300fa174a88d4e02f74cd115b14057c205aca1e8bcbab67cf95c4fd233a98b",
		"policy": "sha256:59b74f0bb3fe24c0344db8c82dc6aad3be0cc08c1a38b8ba6d309ab270458e46"
	},
	"historicalCandidate": {
		"candidateId": "100b1cd5891c34ea363293ac0a4fb41b1caeeb41a74455a31b0a49d6b260fc68",
		"originalVerdictArtifactPath": "battery/dumgen/docs/prototypes/german-relation-human-gate/verdict.json",
		"archivedArtifacts": [
			{
				"role": "retained-result",
				"commit": "e5060a0407252f25af801f59674f47a5aff71e55",
				"path": "battery/dumgen-new/docs/prototypes/german-relation-prompt-iteration-lab/runs/2026-08-20T17-05-28-531Z/results.json",
				"sha256": "c968b9096f17a5dc756b3784f685dcf5c38975628280ee88d4e8f9efb753c082"
			}
		],
		"fingerprints": {
			"prompt": "sha256:0896648f922dcb122a3d7f3956126a9b30d2964bdf04a187503bc8526980628a",
			"schema": "sha256:3562a451015bb9c16ae65e45792e5f5897ab4c118cbc7c76340ad38b11e7968d",
			"evaluator": "sha256:fdd2c95c575a1764918df1943c89b7a0ed3f29cac3c1e7dd35e0c7c4d7532f82",
			"model": "openai:gpt-5.6-luna:sha256:b8de968b038ede28ac0892743a7e2e76b4899eb4fce0e85e5c1c471cf82ea627",
			"policy": "candidate:100b1cd5891c34ea363293ac0a4fb41b1caeeb41a74455a31b0a49d6b260fc68:sha256:e411821b03992797c8dddae175727b03f7b97b29ddc405076632ac07e1709720"
		},
		"verdict": null
	},
	"invalidationReasons": [
		"archivedRunEvidence",
		"missingReviewedVerdictArtifact",
		"historicalCandidateRequiresReevaluation"
	],
	"verdict": null
} as const;
