import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const GENERATED_NOTICE =
	"<!-- This file is generated by `bun run generate:readme`. Do not edit README.md by hand. -->\n\n";
const BLOCK_MARKER = /^\s*\/\/\s*README_BLOCK:([a-z0-9-]+):(start|end)\s*$/;
const TEMPLATE_MARKER = /<!-- README_BLOCK:([a-z0-9-]+) -->/g;

const scriptDir = dirname(fileURLToPath(import.meta.url));
const defaultExamplesDir = join(scriptDir, "examples");
const defaultTemplatePath = join(scriptDir, "README.template.md");
const defaultReadmePath = resolve(scriptDir, "..", "README.md");
const isMainModule =
	process.argv[1] !== undefined &&
	resolve(process.argv[1]) === fileURLToPath(import.meta.url);

export function extractBlocksFromSource(
	sourceText: string,
	filePath: string,
): Map<string, string> {
	const blocks = new Map<string, string>();
	const lines = sourceText.split("\n");
	let activeBlockName: string | null = null;
	let activeBlockStartLine = -1;
	let activeBlockLines: string[] = [];

	for (const [index, line] of lines.entries()) {
		const markerMatch = BLOCK_MARKER.exec(line);
		if (!markerMatch) {
			if (activeBlockName !== null) {
				activeBlockLines.push(line);
			}
			continue;
		}

		const blockName = markerMatch[1];
		const markerKind = markerMatch[2];
		if (blockName === undefined || markerKind === undefined) {
			throw new Error(
				`Invalid README block marker in ${filePath}:${index + 1}.`,
			);
		}

		if (markerKind === "start") {
			if (activeBlockName !== null) {
				throw new Error(
					`Nested README block "${blockName}" in ${filePath}:${index + 1}.`,
				);
			}
			if (blocks.has(blockName)) {
				throw new Error(
					`Duplicate README block "${blockName}" in ${filePath}:${index + 1}.`,
				);
			}
			activeBlockName = blockName;
			activeBlockStartLine = index + 1;
			activeBlockLines = [];
			continue;
		}

		if (activeBlockName !== blockName) {
			throw new Error(
				`Unexpected README block end "${blockName}" in ${filePath}:${index + 1}.`,
			);
		}

		const blockText = activeBlockLines.join("\n").trim();
		blocks.set(blockName, blockText);
		activeBlockName = null;
		activeBlockStartLine = -1;
		activeBlockLines = [];
	}

	if (activeBlockName !== null) {
		throw new Error(
			`Unclosed README block "${activeBlockName}" in ${filePath}:${activeBlockStartLine}.`,
		);
	}

	return blocks;
}

export function collectExampleBlocks(
	examplesDir = defaultExamplesDir,
): Map<string, string> {
	const blockEntries = new Map<string, string>();
	const exampleFiles = readdirSync(examplesDir)
		.filter((fileName) => fileName.endsWith(".ts"))
		.sort();

	for (const fileName of exampleFiles) {
		const filePath = join(examplesDir, fileName);
		const fileBlocks = extractBlocksFromSource(
			readFileSync(filePath, "utf8"),
			filePath,
		);

		for (const [blockName, blockText] of fileBlocks) {
			if (blockEntries.has(blockName)) {
				throw new Error(
					`README block "${blockName}" is defined more than once.`,
				);
			}
			blockEntries.set(blockName, blockText);
		}
	}

	return blockEntries;
}

export function renderReadmeTemplate(
	templateText: string,
	blocks: Map<string, string>,
): string {
	const usedBlocks = new Set<string>();
	const renderedTemplate = templateText.replaceAll(
		TEMPLATE_MARKER,
		(_, blockName: string) => {
			const block = blocks.get(blockName);
			if (block === undefined) {
				throw new Error(`Missing README block "${blockName}".`);
			}
			usedBlocks.add(blockName);
			return `\`\`\`ts\n${block}\n\`\`\``;
		},
	);
	const unusedBlocks = [...blocks.keys()].filter(
		(blockName) => !usedBlocks.has(blockName),
	);

	if (unusedBlocks.length > 0) {
		throw new Error(
			`Unused README blocks: ${unusedBlocks.toSorted().join(", ")}.`,
		);
	}

	return `${`${GENERATED_NOTICE}${renderedTemplate}`.trimEnd()}\n`;
}

export function buildReadme(options?: {
	examplesDir?: string;
	templatePath?: string;
}) {
	const templatePath = options?.templatePath ?? defaultTemplatePath;
	const examplesDir = options?.examplesDir ?? defaultExamplesDir;
	const templateText = readFileSync(templatePath, "utf8");
	const blocks = collectExampleBlocks(examplesDir);

	return renderReadmeTemplate(templateText, blocks);
}

export function writeReadme(options?: {
	examplesDir?: string;
	outputPath?: string;
	templatePath?: string;
}) {
	const outputPath = options?.outputPath ?? defaultReadmePath;
	const readme = buildReadme(options);

	writeFileSync(outputPath, readme);

	return readme;
}

if (isMainModule) {
	writeReadme();
}
