export * from "./de/lemmas";
export * from "./de/selections";
export * from "./de/surfaces";
export * from "./eng/lemmas";
export * from "./eng/selections";
export * from "./eng/surfaces";
export * from "./heb/lemmas";
export * from "./heb/selections";
export * from "./heb/surfaces";
