export * from "./de/attestations";
export * from "./de/lemmas";
export * from "./de/surfaces";
export * from "./eng/attestations";
export * from "./eng/lemmas";
export * from "./eng/surfaces";
export * from "./heb/attestations";
export * from "./heb/lemmas";
export * from "./heb/surfaces";
