import type { Rule, RuleRoute } from "./types.js";

const lexeme = (...kinds: RuleRoute["kind"][]): RuleRoute[] =>
	kinds.map((kind) => ({ language: "de", family: "Lexeme", kind }));
const locution = (...kinds: RuleRoute["kind"][]): RuleRoute[] =>
	kinds.map((kind) => ({ language: "de", family: "Locution", kind }));
const everyLocution = locution(
	"VERB",
	"NOUN",
	"ADJ",
	"ADV",
	"ADP",
	"CCONJ",
	"SCONJ",
	"DET",
	"PRON",
	"NUM",
	"INTJ",
);
const saying: RuleRoute[] = [
	{ language: "de", family: "Saying", kind: "Saying" },
];
const everyMultiword = [...everyLocution, ...saying];

/** Which Segments form one unit, whatever its route. */
const units: Rule[] = [
	{
		id: "de/largest-fixed-unit",
		statement:
			"A click on a word selects the largest complete fixed unit that contains it. Every fixed member selects the same unit, and the unit is found by position in the sentence, never by spelling.",
		adrs: ["ADR-0003", "ADR-0039", "dumgen/ADR-0007"],
		routes: [],
		records: [
			"de/verbrannt-ist-alles-ganz-und-gar",
			"de/bei-dieser-formel-verstehe-ich-nur-bahnhof",
			"de/damit-triffst-du-den-nagel-auf-den-kopf",
			"de/guten-tag-ich-habe-einen-termin",
			"de/na-ja-ganz-ueberzeugt-bin-ich-nicht",
			"de/tut-mir-leid-das-war-mein-fehler",
			"de/genau-da-liegt-der-hase-im-pfeffer",
			"de/morgenstund-hat-gold-im-mund-sagte-sie-verschlafen",
			"de/wer-zuerst-kommt-mahlt-zuerst",
		],
	},
	{
		id: "de/fixed-members-only",
		statement:
			"A unit's members are the words it fixes, function words included. Free arguments, modifiers, fillers, punctuation and opaque text stay outside. Words are not fixed just because they stand together, often occur together or form an ordinary compositional phrase.",
		adrs: ["ADR-0003"],
		routes: [],
		records: [
			"de/bei-dieser-formel-verstehe-ich-nur-bahnhof",
			"de/damit-triffst-du-den-nagel-auf-den-kopf",
			"de/ich-gehe-tomaten-kaufen-um-einen-salat-zu-machen",
			"de/genau-da-liegt-der-hase-im-pfeffer",
		],
	},
	{
		id: "de/locutions-and-sayings-are-made-of-lexemes",
		statement:
			"Every word belongs to exactly one target: the biggest unit it is part of. A word inside a Locution or a Saying has no target of its own in the sentence; the multiword unit leads to it through the Lemma's Breakdown.",
		adrs: ["ADR-0041", "dumgen/ADR-0007"],
		routes: everyMultiword,
		records: [
			"de/bei-dieser-formel-verstehe-ich-nur-bahnhof",
			"de/damit-triffst-du-den-nagel-auf-den-kopf",
			"de/guten-tag-ich-habe-einen-termin",
			"de/ich-gehe-tomaten-kaufen-um-einen-salat-zu-machen",
			"de/na-ja-ganz-ueberzeugt-bin-ich-nicht",
			"de/genau-da-liegt-der-hase-im-pfeffer",
			"de/morgenstund-hat-gold-im-mund-sagte-sie-verschlafen",
			"de/wer-zuerst-kommt-mahlt-zuerst",
		],
	},
	{
		id: "de/unresolved-over-repair",
		statement:
			"A target is right only when its members are exactly the complete fixed unit the sentence realizes: no fixed member that is present is left out, and no free word is added. When membership is uncertain or contradictory, the answer is Unresolved; the group is never trimmed, extended or repaired.",
		adrs: ["ADR-0003", "dumgen/ADR-0007"],
		routes: [],
		records: [],
	},
	{
		id: "de/no-target",
		statement:
			"A word has no target when no route for it is defensible: unintelligible text or a nonce word that no German or foreign word, name or plausible typo fits (xqzt, glorpen), a word broken off (trans…), an article whose noun phrase breaks off before its Head (das in Er brach das…), or a suspended-compound fragment with no right conjunct to complete it. The context must show the break, not an ellipsis alone, and no noun or demonstrative reading is made up: a complete Er brach das. gives das PRON. The classifier answers Unresolved for it.",
		adrs: ["ADR-0037", "ADR-0040", "ADR-0045"],
		routes: [],
		records: [
			"de/das-wetter-ist-xqzt",
			"de/im-beispiel-sollte-die-figur-morgen-glorpen-doch-die",
			"de/der-blarg-tauchte-ohne-erklaerung-im-bericht-auf",
			"de/das-glossar-fuehrte-den-nicht-weiter-bestimmten-eintrag",
			"de/die-aufnahme-brach-mitten-im-begonnenen-wort-nach-trans",
			"de/die-sprecherin-begann-mit-unver-und-brach-das-wort-hoerbar",
			"de/er-brach-das",
		],
	},
	{
		id: "de/foreign-unless-duden-or-german-grammar",
		statement:
			"A word from another language that Duden lists in this meaning is a Lexeme of its real Kind, inflected or not: mit lol gives INTJ lol. An unlisted word is a Lexeme only when this occurrence shows German grammar on it: an ending (geyeetet gives VERB yeeten) or an agreeing article or determiner (der Hotfix). Filling a slot is not grammar, so sehr sus is a Foreign unit with its source language. A Foreign unit is one word or a phrase fixed in its source language (by the way); other foreign syntax gives one unit per word. Its Canonical Form corrects only position casing and typos.",
		adrs: ["ADR-0045"],
		routes: [
			{ language: "de", family: "Foreign", kind: "Foreign" },
			...lexeme("NOUN", "ADJ", "INTJ"),
		],
		records: [
			"de/er-antwortete-im-chat-nur-mit-lol",
			"de/in-der-jugendgruppe-fanden-alle-die-szene-ziemlich-cringe",
			"de/sein-kommentar-wirkt-cringe",
			"de/im-ansonsten-deutschen-gespraech-nannte-er-die-entscheidung",
			"de/im-deutsch-englischen-chat-war-mit-dem-tippfehler-wierd",
			"de/die-studentin-nannte-das-ergebnis-low-key-ueberraschend",
			"de/das-ist-sus",
			"de/im-deutschsprachigen-spielchat-wirkte-die-erklaerung-sehr",
			"de/das-war-ein-special-moment-fuer-das-team",
			"de/im-deutsch-englischen-gespraech-sagte-er-das-ist-not-okay",
			"de/das-meeting-war-very-good",
			"de/in-der-sonst-deutschen-unterhaltung-antwortete-sie-nur",
			"de/whatever-sagte-sie-am-anfang-ihrer-deutschen-antwort",
			"de/im-chat-war-mit-dem-fehlerhaft-geschriebenen-englischen-wort",
			"de/der-englische-ausdruck-off-grid-blieb-im-deutschen-gespraech",
			"de/die-britische-schreibvariante-colour-stand-in-der-deutschen",
			"de/vor-ihrer-meinung-schrieb-sie-im-deutschen-chat-tbh",
			"de/der-alte-forenbeitrag-endete-mit-dem-slangausdruck-w00t",
		],
	},
];

const verbs: Rule[] = [
	{
		id: "de/verb-owns-its-scattered-members",
		statement:
			"A verb's target includes its separable particle, its lexical reflexive and the auxiliaries of its own perfect, future and passive, wherever they stand: zog … an gives [zog, an] VERB anziehen. The reflexive is lexical when this sense needs it coreferent with the subject and a non-reflexive object would change the sense. The same test decides a reflexive in Locutions of every type: sich Sorgen machen, sich ins Fäustchen lachen. A reflexive that alternates with other objects in the same sense is a PRON target of its own.",
		adrs: ["ADR-0003", "ADR-0022", "ADR-0039"],
		routes: [...lexeme("VERB"), ...everyLocution],
		records: [
			"de/es-zog-der-wilde-jaegersmann",
			"de/pass-auf-dich-auf",
			"de/der-faehrmann-hat-uns-uebergesetzt",
			"de/der-laster-fuhr-das-schild-um",
			"de/er-versucht-hinauszulaufen",
			"de/sie-wurde-um-geduld-gebeten",
			"de/sie-erinnert-sich-an-den-geruch",
			"de/die-peitsche-hat-er-mitgebracht",
			"de/nahm-ranzen-pulverhorn-und-flint",
			"de/fort-geht-nun-die-mutter-und",
			"de/verbrannt-ist-alles-ganz-und-gar",
			"de/wir-liefen-den-fluss-entlang",
			"de/sieh-mal-an-die-kleine-von-nebenan",
			"de/er-lag-auf-seinem-panzerartig-harten-ruecken-und-sah-wenn-er",
			"de/vergeblich-frage-ich-mich-was-mit-ihm-geschehen-wird",
			"de/alles-was-stirbt-hat-vorher-eine-art-ziel-eine-art",
			"de/alfred-neigte-das-haupt-leer-laechelnd-wie-zum",
			"de/es-kam-auch-vor-dass-ihn-mitten-im-sprechen-eine-welle-der",
			"de/es-war-klar-dass-doktor-mantelsack-heute-ausserhalb-jeder",
			"de/seit-wochen-macht-sich-meine-mutter-sorgen-um-ihre-gesundheit",
			"de/nach-der-ueberraschenden-nachricht-hat-sie-sich-heimlich-ins",
			"de/tut-mir-leid-das-war-mein-fehler",
			"de/als-sie-vom-tod-seines-hundes-erfuhr-sagte-sie-leise-tut-mir",
		],
	},
	{
		id: "de/expletive-es-joins-its-verb",
		statement:
			"A subject es that the verb selects and that refers to nothing belongs to the verb's target, across word order changes and free words in between: es gibt (Lemma geben), es regnet. The es of weather or time is such an es with sein too: Es war gegen halb zwölf gives [Es, war] VERB sein. Referential es, positional es (Es kamen Gäste) and anticipatory es (Es freut mich, dass du kommst) are PRON targets of their own; an object es is a member only as de/fixed-member-test says. A clitic 's takes the same test as es: Mir geht's gut gives [geht, 's] gehen. An omitted es is never added.",
		adrs: ["ADR-0022"],
		routes: lexeme("VERB", "PRON"),
		records: [
			"de/es-brennt-die-hand-es-brennt-das-haar",
			"de/es-zog-der-wilde-jaegersmann",
			"de/mir-geht-s-gut",
			"de/wenn-s-morgen-regnet-bleibt-das-turnier-in-der-halle",
			"de/das-radio-geht-s-wieder",
			"de/es-war-gegen-halb-12-uhr-die-badegaeste-mussten-sich-noch-am",
			"de/sofort-klopfte-es-und-ein-mann-den-er-in-dieser-wohnung-noch",
			"de/darauf-kommt-es-an",
			"de/es-kam-auch-vor-dass-ihn-mitten-im-sprechen-eine-welle-der",
			"de/es-war-jetzt-nicht-mehr-so-drohend-wahrscheinlich-dass-hanno",
			"de/es-war-klar-dass-doktor-mantelsack-heute-ausserhalb-jeder",
			"de/nachdem-er-die-vase-zerbrochen-hatte-sagte-er-es-tut-mir",
		],
	},
	{
		id: "de/governed-preposition-joins-its-governor",
		statement:
			"A preposition that a verb, adjective or noun selects for its complement is a member of that word's target, also when it stands apart: Auf ihn bin ich stolz gives [stolz, auf] ADJ. It joins the smallest unit its government survives in (aus Angst vor Hunden gives [Angst, vor] NOUN) and is never part of the Lemma. A participial ADJ governs the preposition its source verb governs in the same sense. Government is read from E-VALBU, and from Duden where E-VALBU has no entry. A free adjunct preposition (wartet im Keller) is not a member, and neither is the preposition inside an Adverbial complement (legt das Buch auf den Tisch, wohnt in Bonn): the verb requires a place or direction, not that preposition.",
		adrs: ["ADR-0029", "ADR-0034", "ADR-0036"],
		routes: [
			...lexeme("VERB", "ADJ", "NOUN"),
			...locution("VERB", "ADJ", "NOUN"),
		],
		records: [
			"de/pass-auf-dich-auf",
			"de/das-rote-band-lag-auf-dem-geschenk",
			"de/er-wartet-auf-den-nachtbus",
			"de/sie-wurde-um-geduld-gebeten",
			"de/sie-erinnert-sich-an-den-geruch",
			"de/er-ist-stolz-auf-seinen-sohn",
			"de/als-gregor-samsa-eines-morgens-aus-unruhigen-traeumen",
			"de/vergeblich-frage-ich-mich-was-mit-ihm-geschehen-wird",
			"de/er-wechselte-einen-gluecklichen-blick-mit-kai-und-fing-an",
			"de/mit-einer-dame-die-so-gut-erzogen-wurde-kann-man-sich",
		],
	},
	{
		id: "de/bracket-particle-or-circumposition",
		statement:
			"A directional or locative word (vorbei, hinaus, entlang, gegenüber) in the verbal bracket is the verb's separable particle when verb and word form a particle verb in this sense, one a dictionary lists or a productive series it describes yields (herschreiten like hergehen): führt an der Schule vorbei gives [führt, an, vorbei] VERB vorbeiführen. Coordinated with a free directional phrase under one shared verb, the word is an ADV. Preposition and word form a circumposition, a Locution ADP, only as one constituent outside the bracket or when no such particle verb exists (um … willen).",
		adrs: ["ADR-0003", "ADR-0022", "ADR-0034", "ADR-0039"],
		routes: [...lexeme("VERB"), ...locution("ADP")],
		records: [
			"de/der-radweg-fuehrt-an-der-schule-vorbei",
			"de/die-wirkung-reicht-ueber-das-jahr-hinaus",
			"de/der-weg-an-der-kirche-vorbei-ist-gesperrt",
			"de/von-der-terrasse-aus-sieht-man-den-see",
			"de/um-des-friedens-willen-schwiegen-beide-seiten",
			"de/von-diesem-tag-an-fuehrte-sie-das-protokoll",
			"de/er-lief-erst-nach-links-und-dann-hinaus",
			"de/als-der-feueralarm-losging-lief-sie-sofort-hinaus",
			"de/die-verhandlung-lief-schliesslich-auf-einen-kompromiss",
			"de/sie-ging-erst-in-die-kueche-und-dann-hinaus",
			"de/nach-dem-essen-ging-er-kurz-hinaus",
			"de/das-geht-weit-ueber-meine-kraefte-hinaus",
			"de/nahm-ranzen-pulverhorn-und-flint",
			"de/wir-liefen-den-fluss-entlang",
			"de/den-fluss-entlang-standen-alte-weiden",
			"de/um-diese-frage-kommt-er-nicht-herum",
			"de/ueber-die-zusicherung-hinaus-gab-er-nicht-nach",
			"de/der-junge-schwarzkopf-schritt-in-seinem-grauen-filzhut-sein",
			"de/der-musiktempel-zwischen-nadelbaeumen-versteckt-stand",
		],
	},
	{
		id: "de/r-adverb-is-her-or-hin-shorthand",
		statement:
			"A colloquial r- adverb (raus, rein, rüber, runter, rauf, ran) is the Shorthand of the her- or hin- word it shortens, never a Lemma or Variant of its own: the target is the full word, with the r- word as its member in Shorthand orthography. Movement towards the speaker or the scene's viewpoint gives the her- word, movement away the hin- word, and ran is always heran. In the verbal bracket the r- word is the particle of that word's particle verb, and the Surface spells the full particle: Komm sofort raus! gives [Komm, raus] VERB herauskommen.",
		adrs: ["ADR-0022", "ADR-0026", "ADR-0035"],
		routes: lexeme("ADV", "VERB"),
		records: [
			"de/die-zahnaerztin-sieht-sich-das-roentgenbild-an-der-zahn-muss",
			"de/der-brief-liegt-hier-auf-meinem-schreibtisch-das-muss-heute",
			"de/der-vater-holt-die-pinzette-der-splitter-muss-heraus",
			"de/die-kinder-sitzen-seit-stunden-drinnen-jetzt-wollen-sie",
			"de/ich-warte-draussen-vor-der-tuer-komm-sofort-raus",
			"de/sie-blieb-in-ihrer-wohnung-und-warf-ihn-raus",
			"de/es-schneit-und-ich-bleibe-drinnen-geh-bitte-nicht-ohne-jacke",
			"de/die-tuer-ist-offen-ich-bin-in-der-kueche-komm-doch-rein",
			"de/ich-bleibe-draussen-auf-der-terrasse-aber-sie-geht-schon",
			"de/ich-bin-schon-auf-der-anderen-strassenseite-kommst-du-auch",
			"de/unser-zelt-steht-auf-der-anderen-seite-des-flusses-wir",
			"de/ich-warte-unten-an-der-haustuer-kommst-du-runter",
			"de/er-steht-oben-auf-dem-dach-und-schaut-runter",
			"de/ich-bin-oben-in-der-dachwohnung-bring-den-koffer-bitte-rauf",
			"de/wir-stehen-unten-an-der-talstation-und-wollen-heute-noch",
			"de/ich-stehe-hier-neben-dem-fenster-komm-naeher-ran-dann-siehst",
		],
	},
	{
		id: "de/dr-adverb-is-da-shorthand",
		statement:
			"A colloquial dr- adverb (dran, drauf, drin, drüber, drum) is the Shorthand of the da(r)- pronominal adverb it shortens, never a Lemma or Variant of its own: the target is the full word, with the dr- word as its member in Shorthand orthography. ohne recht dran zu glauben gives [dran] ADV daran.",
		adrs: ["ADR-0029", "ADR-0035"],
		routes: lexeme("ADV"),
		records: [
			"de/gluecklicherweise-sagen-sie-das-so-hin-ohne-recht-dran-zu",
		],
	},
	{
		id: "de/split-adverb-is-one-target",
		statement:
			"A da, wo or hier split from its hin, her or preposition is one target of the whole ADV Lexeme, and the verb stays bare: Wo gehst du hin? gives [Wo, hin] ADV wohin and [gehst] VERB gehen, not hingehen. A split pronominal adverb is one target the same way. When hin or her is written as part of the verb, it stays with the verb, and wo or da is a target on its own.",
		adrs: ["ADR-0029"],
		routes: lexeme("ADV", "VERB"),
		records: [
			"de/wo-gehst-du-hin",
			"de/wo-kommst-du-her",
			"de/wo-willst-du-hinfahren",
			"de/da-gehe-ich-morgen-hin",
			"de/da-weiss-ich-nichts-von",
			"de/da-kann-ich-nichts-fuer",
			"de/wo-hast-du-das-mit-gemacht",
		],
	},
	{
		id: "de/pronominal-adverb-stands-alone",
		statement:
			"A pronominal adverb (darauf, davon, dazu, damit, worauf, hierfür) stands for a whole prepositional phrase, or for a clause it anticipates as a correlate, and is an ADV target of its own. Written as one word, it is a single-member ADV; split, it is one ADV target with two members: Da weiß ich nichts von gives [Da, von] ADV davon (de/split-adverb-is-one-target). Either way it never joins a verb or adjective, even one that governs the preposition inside it: wartet darauf gives [wartet] VERB and [darauf] ADV. The governor's valency evidence still records that slot, with no member.",
		adrs: ["ADR-0029", "ADR-0034"],
		routes: lexeme("ADV"),
		records: [
			"de/da-weiss-ich-nichts-von",
			"de/da-kann-ich-nichts-fuer",
			"de/wo-hast-du-das-mit-gemacht",
			"de/es-war-klar-dass-doktor-mantelsack-heute-ausserhalb-jeder",
			"de/gluecklicherweise-sagen-sie-das-so-hin-ohne-recht-dran-zu",
			"de/darauf-kommt-es-an",
		],
	},
	{
		id: "de/modal-is-a-verb",
		statement:
			"A modal (dürfen, können, mögen, müssen, sollen, wollen) is a VERB with its own meaning, whether or not an infinitive follows. Without one, a directional word after it is an ADV, never its particle, though dictionaries list herausmüssen. It owns the auxiliaries that serve it, and the infinitive it governs is a separate VERB target: hat … schreiben müssen gives [hat, müssen] and [schreiben]. Verbs that add a meaning beside a construction (sich lassen, gehören with a participle, brauchen, scheinen, drohen, versprechen or pflegen with zu, copular bleiben) are VERBs in the same way.",
		adrs: ["ADR-0026", "ADR-0022"],
		routes: lexeme("VERB"),
		records: [
			"de/er-muss-heute-arbeiten",
			"de/der-brief-liegt-hier-auf-meinem-schreibtisch-das-muss-heute",
			"de/unser-zelt-steht-auf-der-anderen-seite-des-flusses-wir",
			"de/die-kinder-sitzen-seit-stunden-drinnen-jetzt-wollen-sie",
			"de/die-zahnaerztin-sieht-sich-das-roentgenbild-an-der-zahn-muss",
		],
	},
	{
		id: "de/auxiliary-joins-the-verb-it-serves",
		statement:
			"sein, haben or werden marking perfect, future or passive is never a target on its own. It joins the verb it serves as that unit's auxiliary, and a click on it selects that verb. Standing alone, the same verbs are VERBs with their own meaning: copular sein, haben 'to own', werden 'to become'.",
		adrs: ["ADR-0026", "ADR-0022"],
		routes: lexeme("VERB", "AUX"),
		records: [
			"de/der-faehrmann-hat-uns-uebergesetzt",
			"de/wir-haetten-gern-mehr-zeit",
			"de/sie-wurde-um-geduld-gebeten",
			"de/das-waere-schoen-gewesen",
			"de/das-waere-fast-schief-gewesen",
			"de/die-peitsche-hat-er-mitgebracht",
			"de/jetzt-schien-die-sonne-gar-zu-sehr",
			"de/verbrannt-ist-alles-ganz-und-gar",
		],
	},
	{
		id: "de/causative-lassen",
		statement:
			"lassen with an infinitive joins that infinitive's target as its causative, voice Cau on the Surface, only when the clause names no doer in any form and lassen is not the modal-passive sich lassen ('can be done'): Ich lasse mir die Haare schneiden gives [lasse, schneiden] VERB schneiden. With an intransitive infinitive, the accusative is its doer. The modal-passive is VERB sich lassen over lassen and its sich, and any other lassen, permissive let included, is VERB lassen; the infinitive is then a target of its own. All of this holds unless the combination is an Idiom under de/idiom.",
		adrs: ["ADR-0026", "ADR-0022"],
		routes: lexeme("VERB", "AUX"),
		records: [
			"de/ich-lasse-mir-morgen-die-haare-schneiden",
			"de/ich-will-mir-morgen-die-haare-schneiden-lassen",
			"de/sie-hat-den-zaun-reparieren-lassen",
			"de/ich-lasse-ihn-das-auto-reparieren",
			"de/ich-lasse-das-auto-von-ihm-reparieren",
			"de/sie-laesst-die-kinder-spielen",
			"de/lass-uns-gehen",
			"de/das-fenster-laesst-sich-oeffnen",
		],
	},
	{
		id: "de/copula-stays-apart",
		statement:
			"A copula (sein, werden, bleiben, scheinen, wirken, sich zeigen) never joins its predicate: in Das Wetter ist schön, ist is a single-member VERB and schön an ADJ of its own. A copula and a predicative adjective never form a Collocation, so Er ist stolz auf seinen Sohn gives [ist] VERB and [stolz, auf] ADJ. The one exception is a copula expression whose reflexive is a member by de/verb-owns-its-scattered-members (sich schlüssig werden, sich im Klaren sein): copula, reflexive and predicate form one Locution VERB, not a Collocation.",
		adrs: ["ADR-0026", "ADR-0034", "ADR-0036", "ADR-0039"],
		routes: [...lexeme("VERB", "ADJ"), ...locution("VERB")],
		records: [
			"de/das-wetter-ist-xqzt",
			"de/er-wog-vielleicht-ein-halbes-lot",
			"de/die-aufgabe-bleibt-ungeloest",
			"de/das-waere-schoen-gewesen",
			"de/das-waere-fast-schief-gewesen",
			"de/jetzt-schien-die-sonne-gar-zu-sehr",
			"de/er-ist-stolz-auf-seinen-sohn",
			"de/aber-wie-es-auch-liegen-mag-marcell-wir-muessen-uns-nun",
		],
	},
	{
		id: "de/recipient-passive",
		statement:
			"bekommen, kriegen or erhalten with a Partizip II that adds nothing lexical is the recipient passive and joins the participle's verb: bekommt … geliefert is one VERB target. Lexical bekommen with an object (Sie bekommt ein Paket) and resultative bekommen (Sie bekommt das Glas geöffnet, she manages to open it) are the VERB, and the participle stays outside.",
		adrs: ["ADR-0026", "ADR-0036"],
		routes: lexeme("VERB", "AUX"),
		records: [
			"de/sie-bekommt-das-paket-geliefert-2",
			"de/der-preistraeger-erhielt-die-urkunde-ueberreicht",
			"de/sie-bekommt-ein-paket",
			"de/sie-bekommt-das-glas-endlich-geoeffnet",
		],
	},
];

const participles: Rule[] = [
	{
		id: "de/verbal-participle",
		statement:
			"A participle is verbal only in a perfect with haben or sein (hat gebacken, ist abgereist) or a passive with werden, bekommen, kriegen or erhalten (wird gebacken). There it joins its auxiliaries in one VERB target: ist … aufgefunden worden includes all three.",
		adrs: ["ADR-0036", "ADR-0022"],
		routes: lexeme("VERB"),
		records: [
			"de/der-faehrmann-hat-uns-uebergesetzt",
			"de/sie-wurde-um-geduld-gebeten",
			"de/das-waere-schoen-gewesen",
			"de/das-waere-fast-schief-gewesen",
			"de/die-peitsche-hat-er-mitgebracht",
			"de/verbrannt-ist-alles-ganz-und-gar",
		],
	},
	{
		id: "de/sein-perfect-or-copula",
		statement:
			"sein or haben with a participle is a perfect only when the clause reports the verb's own event. The context decides, and a simple past that says the same supports it: ist abgefahren is fuhr ab, hat um 8 geöffnet is öffnete um 8. Otherwise the participle is an ADJ describing a state and the verb stays apart: copular sein, the state passive included (Das Fenster ist geöffnet gives [ist] VERB and [geöffnet] ADJ; Sie ist verärgert gives verärgert ADJ with no reflexive), or the VERB haben (Der Laden hat bis 20 Uhr geöffnet gives [hat] VERB and [geöffnet] ADJ).",
		adrs: ["ADR-0036"],
		routes: lexeme("VERB", "ADJ"),
		records: [
			"de/der-brief-ist-schon-geschrieben",
			"de/die-kartoffeln-sind-bereits-gekocht",
			"de/die-tuer-ist-geschlossen",
			"de/auf-der-karte-sind-drei-seen-eingezeichnet",
			"de/sie-ist-verheiratet",
			"de/verbrannt-ist-alles-ganz-und-gar",
			"de/der-laden-hat-bis-20-uhr-geoeffnet",
			"de/der-laden-hat-heute-erst-um-8-geoeffnet",
			"de/er-hat-die-ganze-zeit-die-augen-geschlossen",
			"de/er-hat-ploetzlich-die-augen-geschlossen",
		],
	},
	{
		id: "de/participial-adjective",
		statement:
			"A participle outside a perfect or passive is an ADJ, attributive, adverbial or predicative: die gebratenen Zwiebeln. Its own objects, adverbs and agents are free words, and so are its prepositional phrases, except a preposition it governs (de/governed-preposition-joins-its-governor). A substantivized participle or adjective is a NOUN, capitalized and owning its article like any noun (der Reisende). A participle or adjective whose noun is elided stays lowercase and ADJ, and owns the article as the Head of its phrase.",
		adrs: ["ADR-0036", "ADR-0040"],
		routes: lexeme("ADJ", "NOUN"),
		records: [
			"de/der-reisende-wartete-draussen",
			"de/der-reisende-haendler-wartete-draussen",
			"de/der-neue-brunnen-ist-tiefer-als-der-alte",
			"de/der-brief-ist-schon-geschrieben",
			"de/der-geschriebene-brief-lag-auf-dem-tisch",
			"de/die-mit-bleistift-geschriebene-notiz-lag-noch-auf-dem-tisch",
			"de/die-kartoffeln-sind-bereits-gekocht",
			"de/die-gekochten-kartoffeln-standen-schon-bereit",
			"de/die-tuer-ist-geschlossen",
			"de/auf-der-karte-sind-drei-seen-eingezeichnet",
			"de/die-eingezeichneten-seen-sind-jetzt-besser-zu-sehen",
			"de/der-lachende-junge-winkte-uns-zu",
			"de/sie-kam-lachend-herein",
			"de/er-sass-schweigend-am-fenster",
			"de/die-schlafenden-kinder-wurden-nicht-geweckt",
			"de/der-von-allen-bewunderte-lehrer-ging-in-den-ruhestand",
			"de/die-auf-ihn-abgestimmte-loesung-half-sofort",
			"de/die-aufgabe-bleibt-ungeloest",
			"de/sie-ist-verheiratet",
			"de/ein-interessierter-leser-fragte-nach",
			"de/die-angestellten-streikten-gestern",
			"de/ein-verletzter-lag-am-strassenrand",
			"de/trotz-der-hektik-blieb-sie-ganz-gelassen",
			"de/der-alte-sass-allein-am-fenster",
			"de/als-gregor-samsa-eines-morgens-aus-unruhigen-traeumen",
		],
	},
];

const nouns: Rule[] = [
	{
		id: "de/substantivized-infinitive-is-a-noun",
		statement:
			"A capitalized infinitive used as a noun is a NOUN of its own with gender Neut, never the VERB: das Schwimmen, sein ständiges Meckern.",
		adrs: ["ADR-0002", "ADR-0040"],
		routes: lexeme("NOUN", "VERB"),
		records: [
			"de/das-rennen-hat-spass-gemacht",
			"de/schwimmen-ist-gesund",
			"de/sein-staendiges-meckern-nervt",
		],
	},
	{
		id: "de/noun-owns-its-article",
		statement:
			"The Head of a noun phrase owns the article that opens it, across adjectives, numerals and extended attributes, and a click on the article selects the Head: der steile Aufstieg gives [der, Aufstieg] NOUN and [steile] ADJ. When the noun is elided, the word standing in for it is the Head. An article cut off from its Head by a verb, a clause boundary or a noun outside such an attribute is not its article. The article is a member, never a feature: its spelling, read through a fused or shortened form, names the cell of der or ein for its Head's case, number and gender, and that cell is its DET.",
		adrs: ["ADR-0035", "ADR-0040", "ADR-0041"],
		routes: lexeme("NOUN", "PROPN", "ADJ", "NUM", "PRON"),
		records: [
			"de/das-wetter-ist-xqzt",
			"de/es-zog-der-wilde-jaegersmann",
			"de/ich-bin-im-wald",
			"de/die-drei-maedchen-spielen-draussen",
			"de/der-neue-brunnen-ist-tiefer-als-der-alte",
			"de/der-reisende-wartete-draussen",
			"de/ein-verletzter-lag-am-strassenrand",
			"de/am-naechsten-morgen-war-alles-anders",
			"de/das-kind-spielt-im-garten",
			"de/er-zaehlt-eins-und-kauft-danach-einen-mantel",
			"de/das-rote-band-lag-auf-dem-geschenk",
			"de/der-dritte-band-ist-laengst-vergriffen",
			"de/die-band-spielt-heute-im-kellerclub",
			"de/das-schloss-an-der-tuer-klemmt",
			"de/das-schloss-ueber-dem-fluss-wurde-renoviert",
			"de/die-mutter-passt-nicht-auf-diese-schraube",
			"de/der-kiefer-schmerzte-nach-der-operation",
			"de/die-alte-kiefer-steht-am-hang",
			"de/der-leiter-der-werkstatt-kam-spaeter",
			"de/die-leiter-wackelte-auf-dem-nassen-boden",
			"de/die-angestellten-streikten-gestern",
			"de/mit-den-kindern-ist-es-nie-langweilig",
			"de/sie-folgte-ihrem-herzen",
			"de/unter-falschem-namen-mietete-er-das-zimmer",
			"de/viele-vermissen-das-alte-berlin",
			"de/das-rennen-hat-spass-gemacht",
			"de/schwimmen-ist-gesund",
			"de/in-berlin-betreibt-die-bvg-die-u-bahn",
			"de/die-peitsche-hat-er-mitgebracht",
			"de/er-wog-vielleicht-ein-halbes-lot",
			"de/das-problem-ist-der-preis",
			"de/dein-garten-ist-gross-der-meine-ist-klein",
			"de/der-musiktempel-zwischen-nadelbaeumen-versteckt-stand",
			"de/k-wartete-noch-ein-weilchen-sah-von-seinem-kopfkissen-aus",
		],
	},
	{
		id: "de/adjectival-noun-lemma",
		statement:
			"An adjective or participle used as a noun for a person (der Reisende, ein Verletzter) is one Lemma for both sexes, cited in its weak form after the definite article (Reisende, Verletzte), with gender null. Its singular Surface marks the gender its form shows, and the article agrees: der Reisende is Masc, die Angestellte Fem. A plural marks none. A neuter with a meaning of its own is a separate Lemma with gender Neut: ins Deutsche übersetzen gives Deutsche.",
		adrs: ["ADR-0040", "ADR-0002"],
		routes: lexeme("NOUN"),
		records: [
			"de/der-reisende-wartete-draussen",
			"de/ein-verletzter-lag-am-strassenrand",
			"de/die-angestellte-oeffnete-uns-die-tuer",
			"de/die-angestellten-streikten-gestern",
			"de/wir-danken-den-angestellten-fuer-ihre-hilfe",
			"de/die-reisenden-steigen-am-bahnhof-aus",
			"de/auf-dem-bahnsteig-warten-dreizehn-reisende",
			"de/sie-uebersetzt-den-vertrag-ins-deutsche",
			"de/der-reisende-haendler-wartete-draussen",
			"de/der-alte-sass-allein-am-fenster",
		],
	},
	{
		id: "de/neuter-adjectival-noun",
		statement:
			"An adjective or participle used as a neuter noun for a thing or an abstraction is a NOUN Lemma with gender Neut, cited in its weak form (das Böse gives Böse), whether a dictionary lists it or it is formed on the spot: etwas Böses and nichts Neues give NOUN Böse and Neue. It is a Lemma apart from the person noun of the same spelling (der Böse, gender null).",
		adrs: ["ADR-0040", "ADR-0002"],
		routes: lexeme("NOUN"),
		records: [
			"de/sie-uebersetzt-den-vertrag-ins-deutsche",
			"de/jemand-musste-josef-k-verleumdet-haben-denn-ohne-dass-er",
		],
	},
	{
		id: "de/only-der-and-ein-are-articles",
		statement:
			"Only forms of der, die, das and ein are articles, including the article piece of a fused word (m in im) and a shortened article ('ne, 'nen). mein, dieser, kein and other determiners are DETs of their own: kein Haus gives [kein] DET and [Haus] NOUN. The der- part of derselbe and derjenige belongs to the word, not an article, fused piece included: am selben Morgen gives [m, selben] DET derselbe with Full coverage, and Morgen no article.",
		adrs: ["ADR-0035", "ADR-0040"],
		routes: lexeme("NOUN", "DET"),
		records: [
			"de/ich-bin-im-wald",
			"de/da-steht-ne-kiste-auf-dem-flur",
			"de/wir-brauchen-fuer-den-transport-noch-n-auto",
			"de/sie-folgte-ihrem-herzen",
			"de/sein-staendiges-meckern-nervt",
			"de/bitte-folgen-sie-ihrem-ansprechpartner",
			"de/er-vergass-seinen-schluessel-im-buero",
			"de/mit-keinem-wort-erwaehnte-sie-den-plan",
			"de/am-selben-morgen-fiel-erneut-der-strom-aus",
			"de/an-demselben-morgen-fiel-erneut-der-strom-aus",
			"de/am-ende-desselben-tages-fiel-der-strom-aus",
		],
	},
	{
		id: "de/shared-article-in-coordination",
		statement:
			"In coordinated nouns that agree, only the closest noun owns the article: der Aufstieg und Abstieg gives [der, Aufstieg] and [Abstieg], and Abstieg records der as a shared article with Partial coverage. Closest counts Segments within that noun phrase, nested phrases aside, and a tie is Unresolved. Nearness alone never licenses sharing, and another article or a clause boundary ends it.",
		adrs: ["ADR-0003", "ADR-0035", "ADR-0040"],
		routes: lexeme("NOUN"),
		records: [
			"de/der-aufstieg-und-abstieg",
			"de/der-aufstieg-und-abstieg-und-umstieg",
			"de/der-aufstieg-und-der-abstieg",
		],
	},
	{
		id: "de/proper-noun-article",
		statement:
			"A proper noun cited with its definite article (die Schweiz) has Core article Definite and owns that article as a common noun does, fused pieces included: im Rhein gives [i] ADP and [m, Rhein] PROPN. Names of streets, squares, rivers, mountains and buildings are cited with it, as is a title whose article inflects. A name cited bare (Berlin) has none and still owns the article that opens its phrase. A surname or coined name, unlike other names, has no Core gender: its Surface marks the gender an owned article or agreeing adjective shows, and must where it owns one (der junge Schwarzkopf).",
		adrs: ["ADR-0035", "ADR-0040"],
		routes: lexeme("PROPN"),
		records: [
			"de/am-samstag-sehen-wir-die-zauberfloete-in-der-oper",
			"de/er-badet-im-rhein",
			"de/mr-und-mrs-parker-wohnen-im-fliederweg-nummer-7",
			"de/ich-wohne-im-alten-berlin",
			"de/viele-vermissen-das-alte-berlin",
			"de/in-berlin-betreibt-die-bvg-die-u-bahn",
			"de/sieh-einmal-hier-steht-er",
			"de/die-nato-beraet-heute-ueber-den-antrag",
			"de/im-sommer-besucht-sie-die-schweiz",
			"de/der-junge-schwarzkopf-schritt-in-seinem-grauen-filzhut-sein",
			"de/die-koechin-der-frau-grubach-seiner-zimmervermieterin-die",
			"de/alles-was-stirbt-hat-vorher-eine-art-ziel-eine-art",
			"de/ach-treibel-sie-sind-ewig-ein-spoetter",
		],
	},
	{
		id: "de/title-before-a-name",
		statement:
			"A title or form of address before a name (Herr, Frau, Dr., Mr, Mrs) is a common noun of its own, and the name a separate PROPN. It takes the name's case and number, unless it addresses someone. An abbreviated title stands for its expansion, also without the dot British usage drops: Mr und Mrs Parker gives [Mr] NOUN Mister and [Mrs] NOUN Missis.",
		adrs: ["ADR-0035"],
		routes: lexeme("NOUN", "PROPN"),
		records: [
			"de/mr-und-mrs-parker-wohnen-im-fliederweg-nummer-7",
			"de/dipl-ing-mueller-leitet-das-projekt",
		],
	},
];

const fusedWords: Rule[] = [
	{
		id: "de/fused-word-pieces",
		statement:
			"A fused word is one Segment per word it holds, and each piece belongs to the unit of the word it stands for: im is i (in) and m (dem). Outside a fixed expression a preposition piece is a single-member ADP unless a word governs it, and an article piece belongs to the Head of its phrase: Ich bin im Wald gives [i] ADP and [m, Wald] NOUN. Inside a fixed expression both pieces are members. A click on a piece opens the unit that owns it, never the whole written word. am before a superlative with no noun after it is one Segment and a member of the word whose degree it marks.",
		adrs: ["ADR-0027", "ADR-0035", "ADR-0040", "dumgen/ADR-0004"],
		routes: lexeme("ADP", "NOUN", "ADJ", "ADV"),
		records: [
			"de/ich-bin-im-wald",
			"de/mina-reist-am-liebsten-im-fruehling",
			"de/wer-steht-am-naechsten",
			"de/von-allen-arbeitet-sie-am-sorgfaeltigsten",
			"de/am-naechsten-morgen-war-alles-anders",
			"de/genau-da-liegt-der-hase-im-pfeffer",
			"de/morgenstund-hat-gold-im-mund-sagte-sie-verschlafen",
			"de/wir-gehen-zur-schule",
			"de/das-radio-geht-s-wieder",
			"de/er-wartet-aufs-ende",
			"de/der-streit-eskalierte-bereits-mit-seiner-provokation-goss-er",
			"de/wir-stellen-die-daten-zur-verfuegung",
		],
	},
	{
		id: "de/abbreviation-is-one-segment",
		statement:
			"An abbreviation (z.B., usw., Dr.) is one Segment and stands for its whole expansion: the Surface of z.B. is zum Beispiel. A name whose initialism is its usual form (BVG, NATO, ZDF, SPD) stays its own Lemma instead, with abbr Yes, and its Surface keeps the letters: die BVG gives [die, BVG] PROPN BVG, never Berliner Verkehrsbetriebe. An initial the text never expands is its own Lemma the same way, and a name it ends is another: K. and Josef K. are two PROPN Lemmas.",
		adrs: ["ADR-0035", "dumgen/ADR-0004"],
		routes: [],
		records: [
			"de/in-berlin-betreibt-die-bvg-die-u-bahn",
			"de/jemand-musste-josef-k-verleumdet-haben-denn-ohne-dass-er",
			"de/k-wartete-noch-ein-weilchen-sah-von-seinem-kopfkissen-aus",
		],
	},
];

const pronounsAndAdjectives: Rule[] = [
	{
		id: "de/pron-or-det-by-use",
		statement:
			"An interrogative, demonstrative, relative, quantifier or negative that stands for a noun phrase is PRON; one that directly modifies a noun is DET. Genitive jedermanns is PRON, and so are attributive dessen, deren and wessen, whose following noun is a separate target.",
		adrs: [],
		routes: lexeme("PRON", "DET"),
		records: [
			"de/und-minz-und-maunz-die-schreien",
			"de/der-autor-dessen-buch-fehlt-wartet-draussen",
			"de/die-zeugin-deren-aussage-zaehlt-bleibt-anonym",
			"de/mit-keinem-wort-erwaehnte-sie-den-plan",
			"de/nach-manchem-fehler-lernt-man-schneller",
			"de/viele-kamen-zu-spaet",
			"de/wer-war-das",
			"de/wer-mitkommen-will-meldet-sich-bis-freitag",
		],
	},
	{
		id: "de/quantifier-by-use",
		statement:
			"viel, wenig, mehr and meist are classed by use, and the first test that fits decides: after a determiner they are ADJ, also with their noun elided (seine vielen Beine, die meisten); standing for a noun phrase, PRON; determining a noun, DET; used adverbially, the comparable ADV viel or wenig, whose Cmp and Sup are mehr and am meisten, weniger and am wenigsten. For these words this Rule decides over de/pron-or-det-by-use and de/adjective-stays-adj.",
		adrs: ["ADR-0040", "ADR-0042"],
		routes: lexeme("ADJ", "PRON", "DET", "ADV"),
		records: [
			"de/viele-kamen-zu-spaet",
			"de/wir-haetten-gern-mehr-zeit",
			"de/viele-deutschsprachigen-quellen-fehlen-noch",
			"de/mehr-als-die-haelfte-der-gaeste-blieb-bis-zum-ende",
			"de/viele-buecher-wurden-an-die-schule-gespendet",
			"de/nach-dem-umbau-arbeitet-die-pumpe-wenig",
			"de/die-meisten-gaeste-reisten-am-sonntag-ab",
			"de/seine-vielen-im-vergleich-zu-seinem-sonstigen-umfang",
			"de/ich-lese-und-dann-wir-gehen-viel-spazieren",
			"de/ich-muss-darum-auch-viel-in-der-sonne-sitzen-hat-der-arzt",
		],
	},
	{
		id: "de/possessive-after-article",
		statement:
			"In der meine, der meinige and der eine, the pronoun stands in for an elided noun, so it is the Head of its phrase and owns the article the way a noun does: Der meine ist rot gives [Der, meine] PRON. The article is no DET target of its own.",
		adrs: ["ADR-0040"],
		routes: lexeme("PRON", "DET"),
		records: ["de/dein-garten-ist-gross-der-meine-ist-klein"],
	},
	{
		id: "de/was-fuer",
		statement:
			"Standalone was für einer or was für welche is one PRON target. was für ein before a noun, and plural or mass was für, is one DET target. Either may be split across the sentence; the noun and other free words stay outside.",
		adrs: ["ADR-0039"],
		routes: locution("PRON", "DET"),
		records: [],
	},
	{
		id: "de/relative-w-adverb-fills-a-slot",
		statement:
			"Outside a question, direct or indirect, a w-adverb is a relative ADV (pronType Rel) when it names a place, time, manner or reason inside its own clause, with or without an antecedent: die Stadt, wo sie wohnt. A causal overtone on such a use is an inference and changes neither Kind nor Reading. The same word is SCONJ when it only links the clauses and names nothing inside its own. Comparison wie fills no slot in its clause: it is CCONJ before a phrase and SCONJ before a clause.",
		adrs: [],
		routes: lexeme("ADV", "SCONJ", "CCONJ"),
		records: [
			"de/das-ist-die-stadt-wo-sie-wohnt",
			"de/jetzt-wo-du-da-bist-koennen-wir-anfangen",
			"de/er-will-mitkommen-wo-er-doch-krank-ist",
			"de/mach-es-wie-du-willst",
			"de/die-maschine-arbeitet-so-leise-wie-der-hersteller",
			"de/mira-ist-genauso-gross-wie-ihre-schwester",
			"de/die-zweite-loesung-ist-ebenso-robust-wie-die-erste",
			"de/das-ist-der-grund-weshalb-die-faehre-heute-ausfaellt",
			"de/in-dem-moment-wo-sie-ankam-begann-es-zu-regnen",
			"de/in-faellen-wo-das-gesetz-schweigt-entscheidet-das-gericht",
			"de/komm-wann-du-willst",
		],
	},
	{
		id: "de/relative-wo-place-or-time",
		statement:
			"Relative wo has two Readings, picked by what wo names inside its clause, not by the word it follows. It is the time Reading 🧩⏰ when wo names a time: in dem Moment, wo sie ankam; jetzt, wo du da bist; damals, wo; der Tag, wo. Otherwise it is the place Reading 🧩📍, abstract settings included, since English keeps where for them too: die Stadt, wo sie wohnt; in Fällen, wo; an dem Punkt, wo; eine Situation, wo.",
		adrs: [],
		routes: lexeme("ADV"),
		records: [
			"de/in-dem-moment-wo-sie-ankam-begann-es-zu-regnen",
			"de/jetzt-wo-du-da-bist-koennen-wir-anfangen",
			"de/in-faellen-wo-das-gesetz-schweigt-entscheidet-das-gericht",
			"de/das-ist-die-stadt-wo-sie-wohnt",
		],
	},
	{
		id: "de/bare-w-word-is-shorthand",
		statement:
			"A bare w-word that neither asks nor opens a relative clause, usually unstressed inside its clause, is the Shorthand of its irgend- word: the target is that indefinite, and the w-word is its one member, in Shorthand orthography: Das liegt wo im Keller gives [wo] ADV irgendwo. wer, wen and wem are irgendwer, and bare was is etwas, not irgendwas. An echo question stays interrogative.",
		adrs: ["ADR-0035"],
		routes: lexeme("ADV", "PRON"),
		records: [
			"de/komm-wann-vorbei",
			"de/das-liegt-wo-im-keller",
			"de/das-muss-wie-gehen",
			"de/ist-da-wer",
			"de/hast-du-das-wem-erzaehlt",
			"de/stell-das-einfach-wohin",
			"de/den-kenn-ich-woher",
			"de/ich-hab-was-gehoert",
			"de/sag-doch-was",
			"de/ich-habe-das-auto-verkauft-du-hast-was-gemacht",
		],
	},
	{
		id: "de/adjective-stays-adj",
		statement:
			"Comparative and adverbially used adjectives are ADJ, never ADV: sie singt laut gives [laut] ADJ. A word that can inflect as an attributive adjective (lauter, langsame) is an adjective.",
		adrs: [],
		routes: lexeme("ADJ", "ADV"),
		records: [
			"de/sie-kam-lachend-herein",
			"de/er-sass-schweigend-am-fenster",
			"de/ich-suche-einen-besseren-ansatz",
			"de/am-naechsten-morgen-war-alles-anders",
			"de/die-peitsche-hat-er-mitgebracht",
			"de/nahm-ranzen-pulverhorn-und-flint",
			"de/und-minz-und-maunz-die-schreien",
		],
	},
	{
		id: "de/comparability-is-lexical",
		statement:
			"An ADV or ADJ Lemma is comparable when Duden, or else DWDS, gives it comparison forms, suppletive ones included: gern → lieber, am liebsten. A form marked colloquial or rare does not count (töter, toter). A participle no dictionary lists as an adjective is not comparable. Every Surface of a comparable Lemma marks Degree, Pos in a citation and in predicative or adverbial use (singt laut). No Surface of a non-comparable Lemma (hier, heute, tot, entzwei) marks Degree. Such a Surface has no inflection, except that an attributive ADJ marks case, gender and number (der tote Mann).",
		adrs: ["ADR-0042"],
		routes: lexeme("ADJ", "ADV"),
		records: [
			"de/als-grundform-wird-mild-angegeben",
			"de/bitte-warten-sie-hier-vor-dem-eingang",
			"de/der-brief-ist-schon-geschrieben",
			"de/der-geschriebene-brief-lag-auf-dem-tisch",
			"de/die-mit-bleistift-geschriebene-notiz-lag-noch-auf-dem-tisch",
			"de/die-kartoffeln-sind-bereits-gekocht",
			"de/die-gekochten-kartoffeln-standen-schon-bereit",
			"de/die-tuer-ist-geschlossen",
			"de/auf-der-karte-sind-drei-seen-eingezeichnet",
			"de/die-eingezeichneten-seen-sind-jetzt-besser-zu-sehen",
			"de/der-lachende-junge-winkte-uns-zu",
			"de/sie-kam-lachend-herein",
			"de/er-sass-schweigend-am-fenster",
			"de/die-schlafenden-kinder-wurden-nicht-geweckt",
			"de/der-reisende-haendler-wartete-draussen",
			"de/der-von-allen-bewunderte-lehrer-ging-in-den-ruhestand",
			"de/die-auf-ihn-abgestimmte-loesung-half-sofort",
			"de/die-aufgabe-bleibt-ungeloest",
			"de/sie-ist-verheiratet",
			"de/ein-interessierter-leser-fragte-nach",
			"de/die-linke-hand-zitterte",
			"de/ich-suche-einen-besseren-ansatz",
			"de/am-naechsten-morgen-war-alles-anders",
			"de/viele-deutschsprachigen-quellen-fehlen-noch",
			"de/die-peitsche-hat-er-mitgebracht",
			"de/morgen-fahren-wir-nach-hamburg",
			"de/einst-ging-er-an-ufers-rand",
			"de/er-wog-vielleicht-ein-halbes-lot",
			"de/es-brennt-die-hand-es-brennt-das-haar",
			"de/die-schoss-das-haeschen-ganz-entzwei",
			"de/jetzt-schien-die-sonne-gar-zu-sehr",
			"de/nahm-ranzen-pulverhorn-und-flint",
			"de/sieh-einmal-hier-steht-er",
			"de/und-minz-und-maunz-die-schreien",
			"de/er-ist-stolz-auf-seinen-sohn",
			"de/es-war-jetzt-nicht-mehr-so-drohend-wahrscheinlich-dass-hanno",
			"de/er-legte-jedes-ding-das-er-beruehrte-kaum-ergriffen-wieder",
			"de/so-ueber-alle-zweifel-war-das-entschieden-dass-er",
			"de/vergeblich-frage-ich-mich-was-mit-ihm-geschehen-wird",
			"de/ach-treibel-sie-sind-ewig-ein-spoetter",
			"de/er-konnte-kein-gespraech-mit-kameraden-fuehren-ohne-grundlos",
		],
	},
	{
		id: "de/attributive-adjective-stands-alone",
		statement:
			"An attributive adjective or participle is a target of its own, joined only by a preposition it governs. The article before it and the noun after it belong to the noun: in ein alter Mann, alter gives [alter] ADJ, and in der wartende Kunde, der belongs to [der, Kunde].",
		adrs: ["ADR-0036", "ADR-0040"],
		routes: lexeme("ADJ"),
		records: [
			"de/der-geschriebene-brief-lag-auf-dem-tisch",
			"de/die-mit-bleistift-geschriebene-notiz-lag-noch-auf-dem-tisch",
			"de/die-gekochten-kartoffeln-standen-schon-bereit",
			"de/die-eingezeichneten-seen-sind-jetzt-besser-zu-sehen",
			"de/der-lachende-junge-winkte-uns-zu",
			"de/die-schlafenden-kinder-wurden-nicht-geweckt",
			"de/der-reisende-haendler-wartete-draussen",
			"de/der-von-allen-bewunderte-lehrer-ging-in-den-ruhestand",
			"de/die-auf-ihn-abgestimmte-loesung-half-sofort",
			"de/ein-interessierter-leser-fragte-nach",
			"de/die-linke-hand-zitterte",
			"de/ich-suche-einen-besseren-ansatz",
			"de/am-naechsten-morgen-war-alles-anders",
			"de/viele-deutschsprachigen-quellen-fehlen-noch",
		],
	},
];

const conjunctionsAndParticles: Rule[] = [
	{
		id: "de/correlator-anchors",
		statement:
			"A fixed correlator is one Locution made of its anchors only, never the words they connect, and its Kind is the part of speech of the whole unit, not of the clicked anchor: entweder … oder, weder … noch, sowohl … als auch and nicht nur … sondern auch are CCONJ; je … desto, je … umso and je … je are SCONJ, as the je clause is verb-final, and so are so … dass and the zu-infinitive conjunctions in germanConjunctionLocutions (um … zu); einerseits … andererseits and teils … teils are ADV. je … desto, je … umso (pre-1996 Variant je … um so) and je … je are three Lemmas, related as synonyms.",
		adrs: ["ADR-0039"],
		routes: locution("CCONJ", "SCONJ", "ADV"),
		records: [
			"de/je-hoeher-der-druck-desdo-groesser-das-risiko",
			"de/je-laenger-der-weg-wird-desto-mueder-werden-die-reisenden",
			"de/je-ruhiger-die-see-war-desto-schneller-kamen-wir-voran",
			"de/je-laenger-wir-warteten-desto-unruhiger-wurden-die-kinder",
			"de/je-frueher-desto-besser",
			"de/je-waermer-desto-schoener",
			"de/je-laenger-der-weg-desto-mueder-die-reisenden",
			"de/je-genauer-wir-messen-umso-sicherer-wird-das-ergebnis",
			"de/je-spaeter-der-abend-wurde-umso-leiser-sprach-die-runde",
			"de/je-mehr-er-versprach-je-weniger-glaubte-man-ihm",
			"de/sie-trinkt-weder-tee-noch-kaffee",
			"de/ich-gehe-tomaten-kaufen-um-einen-salat-zu-machen",
			"de/der-plan-ist-einerseits-guenstig-andererseits-riskant",
			"de/mara-telefonierte-anstatt-den-bericht-sorgfaeltig-zu",
			"de/lina-schwieg-statt-offen-zu-widersprechen",
			"de/er-ging-ohne-sich-zu-verabschieden",
		],
	},
	{
		id: "de/dass-conjunction",
		statement:
			"A preposition that joins dass into one subordinator is one Locution SCONJ over both words, and the clause it opens resolves on its own: ohne dass jemand es bemerkte gives [ohne, dass] SCONJ ohne dass. dumspec lists which ones are in germanConjunctionLocutions. statt and anstatt forms are two Lemmas, related as synonyms, here and in the zu-infinitive conjunctions. sodass is a Lexeme SCONJ, and so dass is its Licensed Variant spelling over two members; so and dass apart are the correlator so … dass (de/correlator-anchors).",
		adrs: ["ADR-0039", "ADR-0041"],
		routes: [...lexeme("SCONJ"), ...locution("SCONJ")],
		records: [
			"de/sie-ging-ohne-dass-jemand-es-bemerkte",
			"de/anstatt-dass-er-klagte-half-er-sofort",
			"de/jemand-musste-josef-k-verleumdet-haben-denn-ohne-dass-er",
			"de/es-schneite-stark-sodass-die-strasse-gesperrt-wurde",
			"de/es-schneite-stark-so-dass-die-strasse-gesperrt-wurde",
			"de/die-tuer-klemmte-so-dass-wir-warten-mussten",
			"de/es-kam-auch-vor-dass-ihn-mitten-im-sprechen-eine-welle-der",
			"de/im-alten-druck-stand-er-sprach-so-leise-dass-ihn-niemand",
		],
	},
	{
		id: "de/bare-infinitive-zu",
		statement:
			"zu before an infinitive, without um, ohne or statt, is a single-member PART and never joins the infinitive: versucht zu schlafen gives [zu] PART and [schlafen] VERB.",
		adrs: [],
		routes: lexeme("PART"),
		records: ["de/das-ist-schwer-zu-erklaeren"],
	},
	{
		id: "de/comparison-als",
		statement:
			"Comparison als, after a comparative or a word of difference or exception (anders, nichts), fills no slot in its clause: it is CCONJ before a phrase (tiefer als der alte) and SCONJ before a clause, a zu-infinitive included (nichts übrig, als ein Ende zu machen).",
		adrs: [],
		routes: lexeme("CCONJ", "SCONJ"),
		records: [
			"de/der-neue-brunnen-ist-tiefer-als-der-alte",
			"de/mira-ist-groesser-als-ihre-schwester",
			"de/heute-kamen-mehr-gaeste-als-gestern",
			"de/der-weg-dauerte-laenger-als-wir-erwartet-hatten",
			"de/die-reparatur-dauerte-kuerzer-als-der-meister-vorausgesagt",
			"de/als-er-die-treppe-hinunterging-wusste-er-dass-ihm-nichts-zu",
		],
	},
	{
		id: "de/nicht-is-part",
		statement:
			"nicht is a PART with polarity Neg, never an ADV, wherever it stands and whatever it negates: Das ist nicht mein Problem gives [nicht] PART nicht, and so do sentence negation (Er kommt nicht) and constituent negation (nicht heute, sondern morgen). It is a single-member target of its own, and it never joins the verb or the word it negates. Where nicht is a fixed member of a Locution or Saying (nicht nur … sondern auch, Der Apfel fällt nicht weit vom Stamm), the Locution and Saying Rules decide the unit.",
		adrs: [],
		routes: lexeme("PART"),
		records: [
			"de/das-ist-nicht-mein-problem",
			"de/heute-faehrt-der-letzte-bus-nicht",
			"de/der-wartungsbericht-wurde-gestern-nicht-veroeffentlicht",
			"de/nicht-jeder-vorschlag-wurde-angenommen",
			"de/die-datei-wurde-nciht-rechtzeitig-gespeichert",
			"de/das-dialektwoerterbuch-bezeichnet-nich-als-regionale",
			"de/das-regionalwoerterbuch-nennt-nedd-ausdruecklich-eine",
		],
	},
];

const locutionsAndSayings: Rule[] = [
	{
		id: "de/fixed-member-test",
		statement:
			"A word is a fixed member of an expression when the expression needs this word, or one of a narrow set, in its slot: an ordinary synonym would break it. A fixed article or preposition counts through the word that carries it (ins Feuer, zur Verfügung). A preposition the expression governs for a free complement (weiß Bescheid über die Pläne) is valency, not a fixed member. A non-referential object es is fixed when das cannot replace it: es gut meinen.",
		adrs: ["ADR-0034", "dumgen/ADR-0007"],
		routes: everyMultiword,
		records: [
			"de/bei-dieser-formel-verstehe-ich-nur-bahnhof",
			"de/damit-triffst-du-den-nagel-auf-den-kopf",
			"de/genau-da-liegt-der-hase-im-pfeffer",
			"de/ihnen-kann-es-keiner-recht-machen-und-am-wenigsten-die",
			"de/sie-meint-es-gut-mit-dir",
		],
	},
	{
		id: "de/funktionsverbgefuege-are-collocations",
		statement:
			"A Collocation is a Locution VERB whose verb only supports its noun or adjective predicate: a Funktionsverbgefüge (zur Verfügung stellen) or a verb with an adjective predicate (ernst nehmen). Its members are the verb, the predicate, the noun's own article or both pieces of its fused word, a reflexive by de/verb-owns-its-scattered-members (sich Sorgen machen), and a preposition the noun or the expression governs; free arguments and adverbs stay outside. A weak collocation with a literal meaning is separate Lexemes. Collocation is the Reading's Locution Type, never part of the Lemma.",
		adrs: ["ADR-0039", "ADR-0034", "dumgen/ADR-0007"],
		routes: locution("VERB"),
		records: [
			"de/wir-stellen-die-daten-zur-verfuegung",
			"de/der-ausschuss-trifft-eine-entscheidung",
			"de/die-ausschuesse-treffen-entscheidungen",
			"de/er-weiss-bescheid-ueber-die-plaene",
			"de/die-peitsche-hat-er-mitgebracht",
			"de/sie-hat-angst-vor-hunden",
			"de/sie-macht-ihre-ansprueche-geltend",
			"de/er-ist-ein-starker-raucher",
			"de/der-kellner-bringt-eine-cola",
			"de/seit-wochen-macht-sich-meine-mutter-sorgen-um-ihre-gesundheit",
		],
	},
	{
		id: "de/idiom",
		statement:
			"An established expression whose meaning here is not the sum of its words is an Idiom, a Locution whose Kind is the part of speech the whole acts as: den Faden verlieren and es in sich haben are VERB, weißer Rabe is NOUN, ganz und gar and unter vier Augen are ADV. A VERB or NOUN Idiom inflects like its verb or noun (hat den Faden verloren). The same words used literally are separate units. A click on any fixed member, a fixed article or preposition included, selects the whole Locution. Idiom is the Reading's Locution Type, never part of the Lemma.",
		adrs: ["ADR-0039", "dumgen/ADR-0007"],
		routes: everyLocution,
		records: [
			"de/mitten-in-der-erklaerung-hat-er-voellig-den-faden-verloren",
			"de/verbrannt-ist-alles-ganz-und-gar",
			"de/im-woerterbuch-steht-der-eintrag-ins-gras-beissen",
			"de/bei-dieser-formel-verstehe-ich-nur-bahnhof",
			"de/damit-triffst-du-den-nagel-auf-den-kopf",
			"de/genau-da-liegt-der-hase-im-pfeffer",
		],
	},
	{
		id: "de/complex-preposition",
		statement:
			"A preposition, a bare noun and a second preposition that work together as one preposition, the noun taking no article or attribute of its own, are one Locution ADP over all their words, both pieces of a fused word included: im Vergleich zu seinem Umfang gives [i, m, Vergleich, zu] ADP im Vergleich zu. The phrase it governs is free.",
		adrs: ["ADR-0039", "ADR-0035"],
		routes: locution("ADP"),
		records: ["de/seine-vielen-im-vergleich-zu-seinem-sonstigen-umfang"],
	},
	{
		id: "de/routine-formula-is-intj",
		statement:
			"A routine formula, a fixed conversational routine such as a greeting, farewell, thanks, apology or wish (guten Morgen), is an INTJ: a Lexeme when it is one word (danke), a Locution otherwise. What it does in conversation is its Formula Role, Reading Knowledge, so one Lemma may carry several Readings. An expression that also serves as an adverbial inside a clause, with the same meaning, keeps Kind ADV even standing alone (Gott sei Dank). Words that only stand together are no formula, and each resolves on its own.",
		adrs: ["ADR-0039"],
		routes: [...lexeme("INTJ"), ...locution("INTJ", "ADV")],
		records: [
			"de/obwohl-am-empfang-schon-jemand-hallo-gerufen-hatte",
			"de/nach-dem-lockeren-zuruf-hallo-trat-die-gastgeberin-ans",
			"de/gibst-du-ihm-das-original-ohne-quittung-auf-keinen-fall",
			"de/nach-dem-einwand-und-dem-zitierten-spruch-morgenstund-hat",
			"de/als-beide-kisten-endlich-oben-standen-erwiderte-der",
			"de/moechten-sie-noch-kuchen-nein-danke-ich-bin-satt",
			"de/herr-keller-betritt-um-sieben-uhr-das-buero-und-gruesst",
			"de/guten-tag-ich-habe-einen-termin",
			"de/na-ja-ganz-ueberzeugt-bin-ich-nicht",
			"de/wie-geht-s-dir-heute",
			"de/gott-sei-dank-ist-niemand-verletzt-worden",
			"de/sie-besteht-auf-einer-entschuldigung",
			"de/entschuldigung-ist-hier-noch-frei",
			"de/draussen-faellt-starker-regen",
		],
	},
	{
		id: "de/interjection-counts-its-words",
		statement:
			"An interjection stands outside the clause to exclaim, answer or imitate a sound and is an INTJ Lexeme, with partType Res for a response particle answering a question, else none. Until punctuation splits them, interjection pieces are one call and one target, cited as written in lexical casing: a Lexeme if a piece is no German word, else a Locution INTJ (ha ha). So is an established exclamation whose meaning is not the sum of its words. Spacing is never a Variant or a Typo: each written shape is its own Lemma. An answer before a formula and a dative after an interjection resolve on their own.",
		adrs: ["ADR-0039", "ADR-0041"],
		routes: [...lexeme("INTJ"), ...locution("INTJ")],
		records: [
			"de/igitt-da-krabbelt-eine-spinne-ueber-den-tisch",
			"de/au-weia-das-gibt-aerger",
			"de/auweia-jetzt-ist-die-milch-uebergekocht",
			"de/oh-la-la-du-hast-dich-aber-schick-gemacht",
			"de/oje-der-letzte-bus-ist-schon-weg",
			"de/o-je-jetzt-faengt-es-auch-noch-an-zu-regnen",
			"de/o-weh-ich-habe-den-schluessel-vergessen",
			"de/ach-je-das-arme-kind",
			"de/ha-ha-sehr-witzig",
			"de/der-zauberer-lachte-ha-ha-und-verbeugte-sich",
			"de/haha-der-war-gut",
			"de/vor-dem-schmutzigen-becken-rief-sie-igitt-igitt",
			"de/sie-warnte-ihn-mit-einem-he-he-vor-dem-schritt",
			"de/pfui-pfui-schaem-dich",
			"de/moechten-sie-noch-kuchen-nein-danke-ich-bin-satt",
			"de/peng-da-war-der-reifen-geplatzt",
			"de/er-stiess-sich-am-tisch-und-rief-au",
			"de/nach-dem-sieg-riefen-alle-hurra",
			"de/als-sie-den-zusammenhang-verstand-sagte-sie-aha",
			"de/nach-dem-letzten-fehlschlag-sagte-sie-tja-und-ging",
			"de/die-katze-sprang-aufs-fensterbrett-miau",
			"de/sie-fragte-ob-er-komme-er-antwortete-ja",
			"de/sie-fragte-kommst-du-nicht-er-antwortete-doch",
			"de/der-offizier-fragte-nach-dem-auftrag-sie-antwortete-jawohl",
			"de/pfui-teufel-wie-das-hier-stinkt",
			"de/ach-du-liebe-zeit-ist-es-schon-so-spaet",
			"de/weh-mir-was-habe-ich-getan",
			"de/wehe-dir-wenn-du-das-verraetst",
			"de/die-schoss-das-haeschen-ganz-entzwei",
			"de/fort-geht-nun-die-mutter-und",
			"de/sieh-einmal-hier-steht-er",
		],
	},
	{
		id: "de/saying-needs-uptake",
		statement:
			"A Saying is a complete saying that speakers have taken up, one target over all its words: a Proverb (Morgenstund hat Gold im Mund) or a Winged Word, a line from a known source used apart from it. A line is taken up when a reference collection lists it (Büchmann, Duden's Zitate und Aussprüche, OWID, DWDS), and a Reviewed Saying record cites that collection. A maxim nobody quotes resolves word by word. The Canonical Form is written as a sentence that keeps its internal punctuation and drops the final one. Proverb or Winged Word is the Reading's Saying Type, never part of the Lemma.",
		adrs: ["ADR-0039"],
		routes: saying,
		records: [
			"de/morgenstund-hat-gold-im-mund-sagte-sie-verschlafen",
			"de/nach-der-winterpause-begann-die-laufgruppe-wieder-zu",
			"de/wer-zuerst-kommt-mahlt-zuerst",
			"de/es-gilt-der-weg-ist-das-ziel",
		],
	},
	{
		id: "de/modification-attests-partially",
		statement:
			"A changed wording still attests the unit, with Partial coverage, as long as speakers still recognize it: the kept words are its members, and the replacing words resolve on their own. A Saying survives any such change; a Locution breaks when a word that carries its meaning is replaced.",
		adrs: ["ADR-0039", "ADR-0003"],
		routes: everyMultiword,
		records: [
			"de/herr-keller-betritt-um-sieben-uhr-das-buero-und-gruesst",
			"de/kaffee-oder-tee-das-ist-hier-die-frage",
			"de/wer-rastet-rostet",
			"de/er-biss-ins-kunstgras",
			"de/er-biss-in-den-rasen",
		],
	},
];

/** What an Attestation of a unit records: its Lemma, Surface and members. */
const attestations: Rule[] = [
	{
		id: "de/core-features-are-identity",
		statement:
			"Each route splits the Feature Pool between Core Features, which are the Lemma's identity, and its Surfaces' inflection, choosing for the learner: a pillar such as the der table or the personal pronouns has one Lemma per cell, and a stem word such as dieser or mein is one Lemma whose forms are Surfaces. A value a learner's dictionary gives only as a usage line under one headword is not identity. A value that is neither leaves the pool and is restated in another layer's own terms: Attestation evidence for what one occurrence shows (a realized case), Reading Knowledge for a fact about a sense or a class (an inflection class), a dumspec table for what the language allows. Where an adposition stands is not identity: wegen des Sturms and des Nebels wegen attest one Lemma, and the ADP Case Table lists the positions wegen takes.",
		adrs: ["ADR-0002", "ADR-0032", "ADR-0034", "ADR-0044"],
		routes: [],
		records: [
			"de/das-rote-band-lag-auf-dem-geschenk",
			"de/der-dritte-band-ist-laengst-vergriffen",
			"de/die-band-spielt-heute-im-kellerclub",
			"de/das-schloss-an-der-tuer-klemmt",
			"de/das-schloss-ueber-dem-fluss-wurde-renoviert",
			"de/die-mutter-passt-nicht-auf-diese-schraube",
			"de/meine-mutter-ruft-jeden-sonntag-an",
			"de/der-kiefer-schmerzte-nach-der-operation",
			"de/die-alte-kiefer-steht-am-hang",
			"de/der-leiter-der-werkstatt-kam-spaeter",
			"de/die-leiter-wackelte-auf-dem-nassen-boden",
			"de/auf-der-karte-sind-drei-seen-eingezeichnet",
			"de/der-faehrmann-hat-uns-uebergesetzt",
			"de/sie-uebersetzt-den-vertrag-ins-deutsche",
			"de/der-laster-fuhr-das-schild-um",
			"de/sie-umfuhr-die-baustelle-weitraeumig",
			"de/bitte-folgen-sie-ihrem-ansprechpartner",
			"de/der-autor-dessen-buch-fehlt-wartet-draussen",
			"de/die-zeugin-deren-aussage-zaehlt-bleibt-anonym",
			"de/er-vergass-seinen-schluessel-im-buero",
			"de/mit-keinem-wort-erwaehnte-sie-den-plan",
			"de/nach-manchem-fehler-lernt-man-schneller",
			"de/viele-kamen-zu-spaet",
			"de/wer-war-das",
			"de/wer-mitkommen-will-meldet-sich-bis-freitag",
			"de/wegen-des-sturms-blieb-die-faehre-im-hafen",
			"de/des-dichten-nebels-wegen-fiel-der-flug-aus",
		],
	},
	{
		id: "de/canonical-form-is-the-headword",
		statement:
			"A Lemma's Canonical Form is its dictionary headword and may differ from the sentence's words. Where Duden lists two spellings, the Canonical Form is Duden's recommended one. An interjection written in pieces is cited as written instead (de/interjection-counts-its-words): ha ha, o je. Identity ignores case, but the Canonical Form keeps the dictionary's casing (Haus, LOL, Sie), never the word's position: sentence-initial Wegen is wegen. A noun's is the bare noun. An open slot is written … (U+2026) with a space on each side (um … willen). A Surface spelled Canonical need not be the Grundform.",
		adrs: ["ADR-0002", "ADR-0035"],
		routes: [],
		records: [
			"de/die-linke-hand-zitterte",
			"de/die-angestellten-streikten-gestern",
			"de/wir-danken-den-angestellten-fuer-ihre-hilfe",
			"de/die-reisenden-steigen-am-bahnhof-aus",
			"de/auf-dem-bahnsteig-warten-dreizehn-reisende",
			"de/der-reisende-wartete-draussen",
			"de/der-reisende-haendler-wartete-draussen",
			"de/ein-verletzter-lag-am-strassenrand",
			"de/sie-uebersetzt-den-vertrag-ins-deutsche",
			"de/ich-suche-einen-besseren-ansatz",
			"de/unter-falschem-namen-mietete-er-das-zimmer",
			"de/am-naechsten-morgen-war-alles-anders",
			"de/das-rennen-hat-spass-gemacht",
			"de/schwimmen-ist-gesund",
			"de/sein-staendiges-meckern-nervt",
			"de/morgen-fahren-wir-nach-hamburg",
			"de/herr-keller-betritt-um-sieben-uhr-das-buero-und-gruesst",
			"de/wegen-dem-regen-kamen-wir-zu-spaet",
			"de/guten-tag-ich-habe-einen-termin",
			"de/ich-gehe-tomaten-kaufen-um-einen-salat-zu-machen",
			"de/genau-da-liegt-der-hase-im-pfeffer",
			"de/auf-die-pointe-antwortete-sie-im-chat-nur-mit-lol",
			"de/er-antwortete-im-chat-nur-mit-lol",
			"de/als-er-die-treppe-hinunterging-wusste-er-dass-ihm-nichts-zu",
		],
	},
	{
		id: "de/member-orthography",
		statement:
			"Each member records how it is written. Standard covers sentence-initial capitals, casing the word leaves free (lol for LOL) and the spelling of a Variant Surface, whatever its tags; Typo is a real spelling or casing error, a spelling no Variant tag covers; Fused is one piece of a written word that holds several words (m in im, 's in geht's); Shorthand is a standalone shortened word ('ne, z.B., wo for irgendwo). Members stay aligned with the sentence: none is added, dropped or modernized.",
		adrs: ["ADR-0003", "ADR-0035"],
		routes: [],
		records: [
			"de/im-heft-stand-filosofie-statt-philosophie",
			"de/der-hockte-da-im-gruenen-gras",
			"de/er-antwortete-im-chat-nur-mit-lol",
		],
	},
	{
		id: "de/variant-and-historical-status",
		statement:
			"A Surface is spelled Canonical when it has the dictionary's main spelling of its form, and Variant when it has any other spelling of that form that is no mistake; a mistake is a Typo member. Spelling is judged against the same form, never the citation: gingen is Canonical for gehen. A Variant names every tag that applies: Licensed when a current standard accepts it, Historical when only an earlier one did, Regional for a dialect or regional form, Expressive for letters stretched for effect. Historical status marks an archaic form, not old spelling or syntax: ward is Canonical and Archaic.",
		adrs: ["ADR-0041"],
		routes: [],
		records: [
			"de/im-heft-stand-filosofie-statt-philosophie",
			"de/der-hockte-da-im-gruenen-gras",
			"de/die-peitsche-hat-er-mitgebracht",
			"de/einst-ging-er-an-ufers-rand",
			"de/jetzt-schien-die-sonne-gar-zu-sehr",
			"de/im-funkverkehr-meldete-die-pilotin-zwo-kontakte",
			"de/das-regionalwoerterbuch-nennt-nedd-ausdruecklich-eine",
			"de/beim-blick-ins-tal-rief-er-boahhh",
			"de/im-alten-brief-steht-er-muss-morgen-abreisen",
			"de/im-alten-druck-stand-er-sprach-so-leise-dass-ihn-niemand",
			"de/die-stadtpolizei-zuerich-meldet-die-strasse-zum-hauptbahnhof",
			"de/neeee-des-mach-i-ned",
			"de/es-sol-ein-jeglicher-des-auffgelegten-brots-vnnd-speise-zu",
			"de/es-war-gegen-halb-12-uhr-die-badegaeste-mussten-sich-noch-am",
			"de/als-gregor-samsa-eines-morgens-aus-unruhigen-traeumen",
		],
	},
	{
		id: "de/digits-spell-the-numeral",
		statement:
			"A number written in digits is the numeral word it spells, never a Lemma of its own: 12 gives NUM zwölf, its Surface a Licensed Variant spelling. Digits and letters are two ways to write one word.",
		adrs: ["ADR-0041", "ADR-0002"],
		routes: lexeme("NUM", "ADJ"),
		records: [
			"de/es-war-gegen-halb-12-uhr-die-badegaeste-mussten-sich-noch-am",
			"de/das-trikot-traegt-die-nummer-73",
			"de/auf-der-anzeigetafel-steht-7",
			"de/die-gleichung-lautet-drei-plus-vier-gleich-7",
		],
	},
	{
		id: "de/empty-inflection-is-structural",
		statement:
			"A Surface leaves its inflection empty only for a dictionary citation, or for an invariant use its route leaves unmarked. A noun leaves its case empty and marks its number only as a vocative (Ach, Treibel) or as a bare noun after voll (voll Wasser). An empty inflection or case states that structure; it never stands for uncertainty.",
		adrs: ["ADR-0032"],
		routes: [],
		records: [
			"de/einst-ging-er-an-ufers-rand",
			"de/ach-treibel-sie-sind-ewig-ein-spoetter",
			"de/findest-du-dass-sie-wirklich-eine-gefaehrliche-person-ist",
			"de/aber-wie-es-auch-liegen-mag-marcell-wir-muessen-uns-nun",
		],
	},
	{
		id: "de/suspended-compound-completion",
		statement:
			"A fragment with a trailing hyphen is completed only in a two-part und or oder coordination with a full compound that shares its literal ending: in Ein- und Ausgang, Ein- is completed to Eingang, with Full coverage.",
		adrs: ["ADR-0003"],
		routes: lexeme("NOUN"),
		records: [
			"de/kinder-und-jugendbuecher-sind-beliebt",
			"de/sie-verkauft-kinder-und-jugendbuecher",
			"de/sie-kauft-ein-kinder-oder-jugendbuch",
			"de/auf-dem-zettel-steht-kinder",
		],
	},
	{
		id: "de/verbal-surface-is-whole",
		statement:
			"A verbal Surface describes its whole target. Perfect, future, passive and causative belong to the whole verbal unit and stay empty on an auxiliary's own Surface, and tense describes the finite verb only.",
		adrs: ["ADR-0022", "ADR-0026"],
		routes: lexeme("VERB", "AUX"),
		records: [
			"de/der-faehrmann-hat-uns-uebergesetzt",
			"de/sie-wurde-um-geduld-gebeten",
			"de/das-waere-schoen-gewesen",
			"de/das-waere-fast-schief-gewesen",
			"de/die-peitsche-hat-er-mitgebracht",
			"de/verbrannt-ist-alles-ganz-und-gar",
		],
	},
	{
		id: "de/verb-core-features",
		statement:
			"A VERB's hasSepPrefix names only its separable prefix, never a governed preposition or a preposition with its own complement. verbType Mod marks a modal, one Lemma whether it governs an infinitive or an object.",
		adrs: ["ADR-0026", "ADR-0029"],
		routes: lexeme("VERB"),
		records: [
			"de/der-faehrmann-hat-uns-uebergesetzt",
			"de/er-muss-heute-arbeiten",
			"de/sie-uebersetzt-den-vertrag-ins-deutsche",
			"de/der-laster-fuhr-das-schild-um",
			"de/sie-umfuhr-die-baustelle-weitraeumig",
			"de/er-versucht-hinauszulaufen",
			"de/wir-liefen-den-fluss-entlang",
			"de/sieh-mal-an-die-kleine-von-nebenan",
		],
	},
	{
		id: "de/partial-coverage",
		statement:
			"An Attestation is Partial only when fixed material is really missing from the sentence and the whole identity is still clear: a noun sharing another noun's article, a verb sharing the auxiliary or finite verb a coordinated verb nearer to it owns, or a Locution or Saying with a fixed word left out or deliberately changed (Rule de/modification-attests-partially). The shared word counts toward the Partial unit's features, not its members: in stieg aus und wieder ein, [ein] einsteigen is Past. A split target, or one with free words between its members, is still Full.",
		adrs: ["ADR-0003", "ADR-0039", "ADR-0041", "ADR-0022"],
		routes: [...lexeme("NOUN", "VERB"), ...everyMultiword],
		records: [
			"de/herr-keller-betritt-um-sieben-uhr-das-buero-und-gruesst",
			"de/sie-hatte-ihren-grossen-strohhut-aufgesetzt-und-ihren",
			"de/er-stieg-aus-und-gleich-wieder-ein",
		],
	},
];

/**
 * The German classification Rules (ADR 0037), grouped by topic. A Rule with
 * no routes applies to every German route. A Rule with no records still needs
 * a Spec Record that shows it.
 */
export const germanRules: readonly Rule[] = [
	...units,
	...verbs,
	...participles,
	...nouns,
	...fusedWords,
	...pronounsAndAdjectives,
	...conjunctionsAndParticles,
	...locutionsAndSayings,
	...attestations,
];
