// Pronoun use, defective paradigms and realization restrictions are reviewed against LEO:
// https://dict.leo.org/grammatik/deutsch/Wort/Pronomen/FRegeln-P/index.xml?lang=de
// https://dict.leo.org/grammatik/deutsch/Wort/Pronomen/FRegeln-P/Genitiv-es-en.html?lang=de
// https://dict.leo.org/grammatik/deutsch/Wort/Pronomen/FRegeln-P/Posses/index.html?lang=de
export const routeGuidance: Readonly<Record<string, string>> = {
	PRON: `Case, agreement number, gender and gender[psor] are Core coordinates of exact case-bearing identities, never Surface inflection. Keep same-spelling cases and Dem versus Rel identities separate. Personal/interrogative/demonstrative/relative/indefinite/total/possessive case-bearing forms retain their reviewed canonical case form; do not reduce to a nominative or possessive stem. jemand/Nom, jemanden/Acc, jemandem/Dat are distinct; alternate accusative jemand is a Variant of jemanden. Likewise niemand forms. Possessive seiner and seines preserve possessed-item Masc and Neut independently of possessor gender[psor].
Use established Case and Number; invariant etwas, nichts/nix, einander may retain null. Null is literal unmarked, not a wildcard. wer/wen/wem/wessen have null Number. Plural agreement has null gender. Nonpossessive personal gender requires third-person singular reference; possessive gender is possessed-item gender, and gender[psor] is possessor gender, requiring personal possessive third-person singular reference. Formal Sie uses plural agreement separately from referenceNumber; only explicit addressee-count evidence marks referenceNumber. Do not infer personal gender from a name alone. Dedicated sich has person 3, pronType Prs, null antecedent number. Reflexivity is the only Surface inflection: Marked with reflex Yes only for coreference with the clause subject acting on/for itself; otherwise Citation/null. Ordinary nonreflexive contextual pronouns therefore have a null Surface bag despite marked Core Case.
mancher/mehrere are Ind, not Tot; mehrere is Plur only. man is Nom/Sing only; oblique generic-person einen/einem belongs to einer. Relative welcher has no Masc/Neut Gen. Standalone jeder/jedweder/jeglicher has no bare Masc/Neut Gen; eines jeden is a separate fixed multi-member expression. Never invent missing paradigm cells. wer/was Int and Rel are distinct; was has no standard Dat. For der/die/das PRON, Gen is dessen or deren/derer, never bare der. derer is standalone, required for forward demonstrative reference, and uncommon in Fem/Sing. Attributive dessen/deren/wessen remain PRON with extPos DET and Core Gen: number/gender describe the antecedent, never the following noun; poss and gender[psor] remain null. Relative case follows the role inside the relative clause. Das sind meine Kinder does not make das Plur or personal.
Possessives without an article use strong endings (meiner, meines); after a definite article they use weak endings (der meine, das meine). The article is a separate DET target. Weak simple forms are alternate Surfaces of the same strong case/gender/number identity; preserve their actual normalized form and mark Variant if it differs from the canonical case form. Possessive -ig forms such as meinige require an article and keep their own lexical forms, never reduce them to mein. Possessor referenceNumber is independent of possessed-item number; formal Ihr allows explicit Sing/Plur or null referenceNumber. e-deletion (meins, unsre, unserm, eure) is licensed variation, not Typo. Short -s forms meins/deins/seins/eins/keins are Nom/Acc Neut only, not Gen. Weak plural beiden requires the appropriate article/determiner context. Attributive Gen -en before a strong genitive noun is a DET rule and must not become a blanket standalone PRON alias.
Preserve formal capitalization Sie/Ihnen/Ihrer; lowercase ordinary sentence-initial capitalization otherwise. Lowercase formal sie is a Typo. External punctuation may license s as a Variant of es, but is not an attested member.`,
	DET: `Core identifies the determiner independently of occurrence Case, agreement number/gender, degree and possessor gender/number in the Surface bag. Native definite article exact spellings der, die and das are separate Lemmas; never collapse their exact occurrences to der. Art/Def marks definite articles; ein is Art/Ind with numType Card. Demonstrative Dem, emphatic Emp, exclamative Exc, interrogative Int, relative Rel, indefinite Ind, negative Neg, total Tot. beide additionally has numType Card.
Inflected welcher/mancher paradigms retain their full citation form, not bare welch/manch identities. Possessives have pronType Prs, poss Yes and possessor person. mein/dein/sein have number[psor] Sing; unser/euer Plur. Formal Ihr has person 2, polite Form and uppercase canonical text; number[psor] is null unless addressee count is explicit. Ordinary dein has polite null. Agreement gender follows the modified noun's lexical gender even in plural; possessor gender is separate and must have evidence. If applicable evidence is uncertain return Unresolved rather than inventing a value.
Attributive was für has no ein in the plural or commonly before mass nouns; standalone was für welche is PRON. Reductions unsre/unsrem/unserm and euere/eure/euerm are licensed, not Typo. Genitive -en instead of -es for all/jeder/jedweder/jeglicher/mancher/welcher/irgendwelcher is licensed before a Masc/Neut noun with genitive -s/-es, not before a weak noun or as a blanket standalone form.
Citation/null is for dictionary mention and invariant uses such as derlei or invariant foreign articles. Contextual declining forms have marked inflection. Foreign determiners preserve their identity and foreign Yes; absence from the reviewed closed catalog is observable. Attributive comparative mehr is its own DET headword with degree Cmp; attributive weniger maps to wenig with Cmp; meisten maps to meist with Sup; extPos stays null for all three. A comparative quantifier without a noun of its own (Mehr als die Hälfte) is PRON, not DET. selbe/selben after a fused article (am selben, im selben) is derselbe with Partial coverage, the article half sitting in the fusion; selber is invariant and never declines. Ordinal wievielte has numType Ord but degree is not automatically Pos. Preserve quoted licensed historical spellings.`,
	NOUN: "An article plus noun is a supported common-noun target under this domain model, even though the article has its own DET analysis. It need not be a lexicalized phrase. In der Aufstieg und Abstieg the first target is [der,Aufstieg] and the second is [Abstieg]; both are supported and have their own singular noun agreement, regardless of plural predicate agreement. Adjectives between an article and its noun stay excluded. A contextual common noun has marked Case/Number even when identical to citation; dictionary-only mention has a null bag. Vocative Case is null. Core gender is lexical, not plural agreement, and hyph records a lexical hyphen. Preserve noun capitalization and contextual suffixes; incorrect noun case is Typo. Standard members copy exactly, except the constrained binary suspended-compound completion described in the shared policy. An isolated truncation, bare right constituent or three-way coordination does not license completion. A preferred dictionary/editorial headword explicitly named in context can establish a Variant; equal standard spellings alone do not choose one.",
	PROPN: "Preserve registered name capitalization, internal capitals, lowercase brand styling, abbreviations and name-internal punctuation. Core abbr requires an established abbreviated identity, not capital letters alone. Foreign requires an overt source-language identity, not origin. Grammatical gender needs lexical/contextual evidence; never guess personal gender from name shape. Plural-only names have null gender. A contextual name has Case/Number inflection, including organizations, acronyms, direct address and historical names. Citation/null is only a name-entry/register/title mention without contextual name agreement; a surrounding label noun does not lend its features. Directional nach is Acc, static in is Dat, vocative Case null and usually Sing. Strip contextual genitive suffix/apostrophe only from canonical headword, never from normalized occurrence. Do not import punctuation outside supplied members.",
	ADJ: "Dictionary-only citation has a null inflection bag. Every ordinary contextual adjective, including predicative/adverbial use, has marked degree; attributive use also carries Case/Gender/Number. Predicative/adverbial Case/Gender/Number are null. Degree Pos/Cmp/Sup preserves irregular paradigms: besser/beste -> gut, höher -> hoch, näher -> nah. Canonical Form of an adjectival participle remains participial (geschlossene -> geschlossen), not a verbal infinitive. Core variant Short means a licensed short lexical identity, not lack of an attributive ending; an abbreviation has abbr Yes and variant null. Ordinal/Cardinal adjective identities use the corresponding numType.",
	ADV: "Ordinary invariant adverbs, including fixed correlators, have null inflection. Marked degree is Cmp/Sup or Pos only when an explicit positive comparison paradigm is established; never an all-null marked bag. lieber -> gern and öfter -> oft. Whole multi-member correlators keep only supplied anchors, with dictionary open-slot notation where conventional. foreign is current overt foreign identity, not etymology; pronType and numType describe lexical identity, not nearby sentence words. A pronominal adverb (da(r)-, hier- or wo(r)- plus preposition) is one invariant ADV whose Canonical Form is the full form: pronType Dem for da(r)- and hier- forms, Int for wo(r)- forms asking a question, Rel for wo(r)- forms introducing a relative clause. Reduced spellings (drauf, dran, drüber) are Variant with the full Canonical Form.",
	NUM: "Invariant cardinals, digits, spoken decimals, years, Roman numerals, fractions, multiplicatives, ranges and multi-member numbers normally have null inflection; do not inherit a neighboring noun agreement. Inflected Million/-illion/-illiarde quantities and visibly agreeing historical forms use supported Case/Gender/Number. Preserve digit versus word representation, Roman/abbreviation casing and contextual morphology. Lowercase ordinary initial word-numeral capitalization, including quantity words. Licensed historical numeral forms retain occurrence spelling, are Variant/Archaic, and map only canonical text to the modern numeral. Modern zwo/T variants are not inherently Archaic. Core numType records the actual numerical identity, and abbr/foreign require lexical evidence.",
	SYM: "Canonical Form is a glyph identity, never a word expansion/translation. Preserve exact conventional glyphs and Unicode presentation unless explicit evidence establishes a Variant or Typo. Ordinary invariant symbols and mentions under a label noun have null inflection. A symbol itself filling a German nominal phrase directly governed by a determiner has the established Case/Gender/Number; that syntax is marked even without visible endings. Neighboring quantities do not supply agreement. Core foreign is overt source-language material outside the German symbolic inventory; international origin does not suffice. numType Card/Range only when the symbol itself is a cardinal/range marker, not merely a currency/unit/operator/percentage.",
	X: "X is a supplied residual identity, never a provider failure. It can still have transparent nominal Case/Gender/Number or verbal Mood/Number/VerbForm; an all-null unsupported analysis uses null inflection. Inflected nonce verbs have a defensible infinitive canonical form while occurrence morphology remains unchanged. Reported-speech syntax and a distinct transparent Konjunktiv form can support Sub; an -e ending alone does not. Core abbr/foreign/hyph require identity evidence. Integrated slang is not foreign solely from etymology or English-looking letters. A lexical internal hyphen marks hyph. numType marks only a transparent supported numerical role. Do not invent an expansion or translate source-language material.",
	ADP: "Always uninflected. Core adpType distinguishes Prep/Post/Circ, and governedCase is stable lexical government, not contextual case of a two-way adposition. A preposition a verb lexically selects is governed-preposition evidence of that verbal target, never this route. partType Vbp requires the lexical particle policy, not an unmarked nearby separable verb. Canonical multi-member circumpositions name the whole fixed unit using conventional open-slot notation. Punctuation outside a supplied abbreviation stays outside normalized members; a conventionally punctuated dictionary abbreviation may differ, making Surface Variant. Equal standard spellings alone do not choose one headword.",
	CCONJ: "Always uninflected. Core conjType Comp applies to a single als/wie introducing a comparison complement, not ordinary coordinators or fixed correlators. The whole canonical correlator uses conventional open-slot notation such as entweder … oder or je … desto; preserve only supplied anchors in occurrence members.",
	SCONJ: "Always uninflected. Keep whole multi-member identities such as um zu, ohne zu, statt zu and so … dass. Core conjType Comp describes actual comparative subordination when supported. Preserve licensed separately written or historical variants as occurrence text; only canonical headword uses the conventional dictionary form.",
	PART: "Always uninflected. Core partType and polarity describe this particle identity; Neg is for actual negation, not a negative sentence containing another particle. foreign/abbr require lexical evidence. Canonical Form preserves the particle identity; licensed regional/expressive/historical variants can differ, but colloquial or foreign does not imply Archaic.",
	INTJ: "Always uninflected. Preserve expressive sound lengthening, reduplication and established written variants as Standard occurrences with Variant spelling when they realize another dictionary form. A real error is Typo and its repair is Canonical. Preserve every supplied repeated member and select only an applicable lexical partType.",
	Idiom: "Core is empty. Canonical Form is the settled complete lexical inventory in dictionary order, retaining obligatory reflexives and fixed function words with German noun capitals; omit free-valency placeholders such as jemandem/etwas when they are not fixed lexical members. A verbal contextual Idiom uses whole-Surface verbal composition; a dictionary citation or invariant nonverbal idiom may have null inflection. Only genuinely unrealized recoverable fixed material permits Partial; an overt unselected word never does. Keep all supplied auxiliaries and every realized member; no invented member for a missing canonical tail.",
	Collocation:
		"Core is empty. This direct-only route covers conventional nonidiomatic support-verb/Funktionsverbgefüge combinations with restricted component choices. A free composition, noncompositional Idiom or fixed function-word Lexeme contradicts the supplied route and is Unresolved, never reclassified. Require one occurrence, at least two fixed members, no external arguments/modifiers/modal/copula, and all realized grammatical auxiliaries of its own verbal head. Every canonical fixed member must be realized and selected. No Partial coverage and no borrowed ellipsis completion. Canonical Form names the established complete component inventory in dictionary order; disputed lexical substitutions are Unresolved, not Variant. Whole-Surface verbal features include its auxiliaries.",
	DiscourseFormula:
		"Core discourseFormulaRole is one scalar supported interactional identity (Greeting, Farewell, Apology, Thanks, Acknowledgment, Refusal, Request, Reaction, Initiation, Transition) or null for a supported function not named, such as wish/presentation/sympathy. Reaction is not every conversational reply. Canonical Form is lowercase complete current wording including nouns, joined by single spaces without punctuation. Full Canonical text is mechanically every normalized member lowercased and joined. Occurrence members still preserve required German noun capitals and lower ordinary utterance-initial words. Conventional abbreviations may fully realize the formula and be Variant/Full. Partial needs genuinely unrealized recoverable wording, not a merely longer related formula.",
	Proverb:
		"Core is empty; always uninflected. Canonical Form is the complete current conventional lexical wording, single-space joined, with appropriate initial/noun capitalization and no punctuation. Full Canonical wording equals normalized members joined exactly. Preserve conventional older morphology/contractions in occurrence members as Standard, not automatically Typo. Licensed historical orthography remains in occurrence text and is Variant; history alone does not make grammar Archaic. A lowercase first word at the start of a complete written saying is a casing Typo and must become uppercase. Partial needs a recoverable genuinely unrealized continuation, normally explicit ellipsis.",
	Aphorism:
		"Core is empty; always uninflected. Canonical Form is the complete current conventional wording in lexical order, single-space joined with initial/noun capitalization and no punctuation. Full Canonical wording equals normalized members joined. Attribution and framing stay outside membership. A lowercase initial word of a complete maxim is Typo; licensed historical spelling remains occurrence text and uses Variant. Partial needs genuinely unrealized recoverable wording, normally explicit truncation/ellipsis; do not add any attested member.",
};
