import type { z } from "../../../../../node_modules/zod/index.js";
import type { DeConstructionFusionFeatureBagsSchema as S0 } from "../../../src/schemas/concrete-language/de/construction/fusion.js";
import type { DeAdjectiveFeatureBagsSchema as S1 } from "../../../src/schemas/concrete-language/de/lexeme/adjective.js";
import type { DeAdpositionFeatureBagsSchema as S2 } from "../../../src/schemas/concrete-language/de/lexeme/adposition.js";
import type { DeAdverbFeatureBagsSchema as S3 } from "../../../src/schemas/concrete-language/de/lexeme/adverb.js";
import type { DeAuxiliaryFeatureBagsSchema as S4 } from "../../../src/schemas/concrete-language/de/lexeme/auxiliary.js";
import type { DeCoordinatingConjunctionFeatureBagsSchema as S5 } from "../../../src/schemas/concrete-language/de/lexeme/coordinating-conjunction.js";
import type { DeDeterminerFeatureBagsSchema as S6 } from "../../../src/schemas/concrete-language/de/lexeme/determiner.js";
import type { DeInterjectionFeatureBagsSchema as S7 } from "../../../src/schemas/concrete-language/de/lexeme/interjection.js";
import type { DeNounFeatureBagsSchema as S8 } from "../../../src/schemas/concrete-language/de/lexeme/noun.js";
import type { DeNumeralFeatureBagsSchema as S9 } from "../../../src/schemas/concrete-language/de/lexeme/numeral.js";
import type { DeOtherFeatureBagsSchema as S10 } from "../../../src/schemas/concrete-language/de/lexeme/other.js";
import type { DeParticleFeatureBagsSchema as S11 } from "../../../src/schemas/concrete-language/de/lexeme/particle.js";
import type { DePronounFeatureBagsSchema as S12 } from "../../../src/schemas/concrete-language/de/lexeme/pronoun.js";
import type { DeProperNounFeatureBagsSchema as S13 } from "../../../src/schemas/concrete-language/de/lexeme/proper-noun.js";
import type { DePunctuationFeatureBagsSchema as S14 } from "../../../src/schemas/concrete-language/de/lexeme/punctuation.js";
import type { DeSubordinatingConjunctionFeatureBagsSchema as S15 } from "../../../src/schemas/concrete-language/de/lexeme/subordinating-conjunction.js";
import type { DeSymbolFeatureBagsSchema as S16 } from "../../../src/schemas/concrete-language/de/lexeme/symbol.js";
import type { DeVerbFeatureBagsSchema as S17 } from "../../../src/schemas/concrete-language/de/lexeme/verb.js";
import type { DeCircumfixMorphemeFeatureBagsSchema as S18 } from "../../../src/schemas/concrete-language/de/morpheme/circumfix.js";
import type { DeCliticMorphemeFeatureBagsSchema as S19 } from "../../../src/schemas/concrete-language/de/morpheme/clitic.js";
import type { DeDuplifixMorphemeFeatureBagsSchema as S20 } from "../../../src/schemas/concrete-language/de/morpheme/duplifix.js";
import type { DeInfixMorphemeFeatureBagsSchema as S21 } from "../../../src/schemas/concrete-language/de/morpheme/infix.js";
import type { DeInterfixMorphemeFeatureBagsSchema as S22 } from "../../../src/schemas/concrete-language/de/morpheme/interfix.js";
import type { DePrefixMorphemeFeatureBagsSchema as S23 } from "../../../src/schemas/concrete-language/de/morpheme/prefix.js";
import type { DeRootMorphemeFeatureBagsSchema as S24 } from "../../../src/schemas/concrete-language/de/morpheme/root.js";
import type { DeSuffixMorphemeFeatureBagsSchema as S25 } from "../../../src/schemas/concrete-language/de/morpheme/suffix.js";
import type { DeSuffixoidMorphemeFeatureBagsSchema as S26 } from "../../../src/schemas/concrete-language/de/morpheme/suffixoid.js";
import type { DeToneMarkingMorphemeFeatureBagsSchema as S27 } from "../../../src/schemas/concrete-language/de/morpheme/tone-marking.js";
import type { DeTransfixMorphemeFeatureBagsSchema as S28 } from "../../../src/schemas/concrete-language/de/morpheme/transfix.js";
import type { DeAphorismPhrasemeFeatureBagsSchema as S29 } from "../../../src/schemas/concrete-language/de/phraseme/aphorism.js";
import type { DeCollocationPhrasemeFeatureBagsSchema as S30 } from "../../../src/schemas/concrete-language/de/phraseme/collocation.js";
import type { DeDiscourseFormulaPhrasemeFeatureBagsSchema as S31 } from "../../../src/schemas/concrete-language/de/phraseme/discourse-formula.js";
import type { DeIdiomPhrasemeFeatureBagsSchema as S32 } from "../../../src/schemas/concrete-language/de/phraseme/idiom.js";
import type { DeProverbPhrasemeFeatureBagsSchema as S33 } from "../../../src/schemas/concrete-language/de/phraseme/proverb.js";
import type { EnConstructionFusionFeatureBagsSchema as S34 } from "../../../src/schemas/concrete-language/en/construction/fusion.js";
import type { EnAdjectiveFeatureBagsSchema as S35 } from "../../../src/schemas/concrete-language/en/lexeme/adjective.js";
import type { EnAdpositionFeatureBagsSchema as S36 } from "../../../src/schemas/concrete-language/en/lexeme/adposition.js";
import type { EnAdverbFeatureBagsSchema as S37 } from "../../../src/schemas/concrete-language/en/lexeme/adverb.js";
import type { EnAuxiliaryFeatureBagsSchema as S38 } from "../../../src/schemas/concrete-language/en/lexeme/auxiliary.js";
import type { EnCoordinatingConjunctionFeatureBagsSchema as S39 } from "../../../src/schemas/concrete-language/en/lexeme/coordinating-conjunction.js";
import type { EnDeterminerFeatureBagsSchema as S40 } from "../../../src/schemas/concrete-language/en/lexeme/determiner.js";
import type { EnInterjectionFeatureBagsSchema as S41 } from "../../../src/schemas/concrete-language/en/lexeme/interjection.js";
import type { EnNounFeatureBagsSchema as S42 } from "../../../src/schemas/concrete-language/en/lexeme/noun.js";
import type { EnNumeralFeatureBagsSchema as S43 } from "../../../src/schemas/concrete-language/en/lexeme/numeral.js";
import type { EnOtherFeatureBagsSchema as S44 } from "../../../src/schemas/concrete-language/en/lexeme/other.js";
import type { EnParticleFeatureBagsSchema as S45 } from "../../../src/schemas/concrete-language/en/lexeme/particle.js";
import type { EnPronounFeatureBagsSchema as S46 } from "../../../src/schemas/concrete-language/en/lexeme/pronoun.js";
import type { EnProperNounFeatureBagsSchema as S47 } from "../../../src/schemas/concrete-language/en/lexeme/proper-noun.js";
import type { EnPunctuationFeatureBagsSchema as S48 } from "../../../src/schemas/concrete-language/en/lexeme/punctuation.js";
import type { EnSubordinatingConjunctionFeatureBagsSchema as S49 } from "../../../src/schemas/concrete-language/en/lexeme/subordinating-conjunction.js";
import type { EnSymbolFeatureBagsSchema as S50 } from "../../../src/schemas/concrete-language/en/lexeme/symbol.js";
import type { EnVerbFeatureBagsSchema as S51 } from "../../../src/schemas/concrete-language/en/lexeme/verb.js";
import type { EnCircumfixMorphemeFeatureBagsSchema as S52 } from "../../../src/schemas/concrete-language/en/morpheme/circumfix.js";
import type { EnCliticMorphemeFeatureBagsSchema as S53 } from "../../../src/schemas/concrete-language/en/morpheme/clitic.js";
import type { EnDuplifixMorphemeFeatureBagsSchema as S54 } from "../../../src/schemas/concrete-language/en/morpheme/duplifix.js";
import type { EnInfixMorphemeFeatureBagsSchema as S55 } from "../../../src/schemas/concrete-language/en/morpheme/infix.js";
import type { EnInterfixMorphemeFeatureBagsSchema as S56 } from "../../../src/schemas/concrete-language/en/morpheme/interfix.js";
import type { EnPrefixMorphemeFeatureBagsSchema as S57 } from "../../../src/schemas/concrete-language/en/morpheme/prefix.js";
import type { EnRootMorphemeFeatureBagsSchema as S58 } from "../../../src/schemas/concrete-language/en/morpheme/root.js";
import type { EnSuffixMorphemeFeatureBagsSchema as S59 } from "../../../src/schemas/concrete-language/en/morpheme/suffix.js";
import type { EnSuffixoidMorphemeFeatureBagsSchema as S60 } from "../../../src/schemas/concrete-language/en/morpheme/suffixoid.js";
import type { EnToneMarkingMorphemeFeatureBagsSchema as S61 } from "../../../src/schemas/concrete-language/en/morpheme/tone-marking.js";
import type { EnTransfixMorphemeFeatureBagsSchema as S62 } from "../../../src/schemas/concrete-language/en/morpheme/transfix.js";
import type { EnAphorismPhrasemeFeatureBagsSchema as S63 } from "../../../src/schemas/concrete-language/en/phraseme/aphorism.js";
import type { EnDiscourseFormulaPhrasemeFeatureBagsSchema as S64 } from "../../../src/schemas/concrete-language/en/phraseme/discourse-formula.js";
import type { EnIdiomPhrasemeFeatureBagsSchema as S65 } from "../../../src/schemas/concrete-language/en/phraseme/idiom.js";
import type { EnProverbPhrasemeFeatureBagsSchema as S66 } from "../../../src/schemas/concrete-language/en/phraseme/proverb.js";
import type { HeConstructionFusionFeatureBagsSchema as S67 } from "../../../src/schemas/concrete-language/he/construction/fusion.js";
import type { HeAdjectiveFeatureBagsSchema as S68 } from "../../../src/schemas/concrete-language/he/lexeme/adjective.js";
import type { HeAdpositionFeatureBagsSchema as S69 } from "../../../src/schemas/concrete-language/he/lexeme/adposition.js";
import type { HeAdverbFeatureBagsSchema as S70 } from "../../../src/schemas/concrete-language/he/lexeme/adverb.js";
import type { HeAuxiliaryFeatureBagsSchema as S71 } from "../../../src/schemas/concrete-language/he/lexeme/auxiliary.js";
import type { HeCoordinatingConjunctionFeatureBagsSchema as S72 } from "../../../src/schemas/concrete-language/he/lexeme/coordinating-conjunction.js";
import type { HeDeterminerFeatureBagsSchema as S73 } from "../../../src/schemas/concrete-language/he/lexeme/determiner.js";
import type { HeInterjectionFeatureBagsSchema as S74 } from "../../../src/schemas/concrete-language/he/lexeme/interjection.js";
import type { HeNounFeatureBagsSchema as S75 } from "../../../src/schemas/concrete-language/he/lexeme/noun.js";
import type { HeNumeralFeatureBagsSchema as S76 } from "../../../src/schemas/concrete-language/he/lexeme/numeral.js";
import type { HeOtherFeatureBagsSchema as S77 } from "../../../src/schemas/concrete-language/he/lexeme/other.js";
import type { HeParticleFeatureBagsSchema as S78 } from "../../../src/schemas/concrete-language/he/lexeme/particle.js";
import type { HePronounFeatureBagsSchema as S79 } from "../../../src/schemas/concrete-language/he/lexeme/pronoun.js";
import type { HeProperNounFeatureBagsSchema as S80 } from "../../../src/schemas/concrete-language/he/lexeme/proper-noun.js";
import type { HePunctuationFeatureBagsSchema as S81 } from "../../../src/schemas/concrete-language/he/lexeme/punctuation.js";
import type { HeSubordinatingConjunctionFeatureBagsSchema as S82 } from "../../../src/schemas/concrete-language/he/lexeme/subordinating-conjunction.js";
import type { HeSymbolFeatureBagsSchema as S83 } from "../../../src/schemas/concrete-language/he/lexeme/symbol.js";
import type { HeVerbFeatureBagsSchema as S84 } from "../../../src/schemas/concrete-language/he/lexeme/verb.js";
import type { HeCircumfixMorphemeFeatureBagsSchema as S85 } from "../../../src/schemas/concrete-language/he/morpheme/circumfix.js";
import type { HeCliticMorphemeFeatureBagsSchema as S86 } from "../../../src/schemas/concrete-language/he/morpheme/clitic.js";
import type { HeDuplifixMorphemeFeatureBagsSchema as S87 } from "../../../src/schemas/concrete-language/he/morpheme/duplifix.js";
import type { HeInfixMorphemeFeatureBagsSchema as S88 } from "../../../src/schemas/concrete-language/he/morpheme/infix.js";
import type { HeInterfixMorphemeFeatureBagsSchema as S89 } from "../../../src/schemas/concrete-language/he/morpheme/interfix.js";
import type { HePrefixMorphemeFeatureBagsSchema as S90 } from "../../../src/schemas/concrete-language/he/morpheme/prefix.js";
import type { HeRootMorphemeFeatureBagsSchema as S91 } from "../../../src/schemas/concrete-language/he/morpheme/root.js";
import type { HeSuffixMorphemeFeatureBagsSchema as S92 } from "../../../src/schemas/concrete-language/he/morpheme/suffix.js";
import type { HeSuffixoidMorphemeFeatureBagsSchema as S93 } from "../../../src/schemas/concrete-language/he/morpheme/suffixoid.js";
import type { HeToneMarkingMorphemeFeatureBagsSchema as S94 } from "../../../src/schemas/concrete-language/he/morpheme/tone-marking.js";
import type { HeTransfixMorphemeFeatureBagsSchema as S95 } from "../../../src/schemas/concrete-language/he/morpheme/transfix.js";
import type { HeAphorismPhrasemeFeatureBagsSchema as S96 } from "../../../src/schemas/concrete-language/he/phraseme/aphorism.js";
import type { HeDiscourseFormulaPhrasemeFeatureBagsSchema as S97 } from "../../../src/schemas/concrete-language/he/phraseme/discourse-formula.js";
import type { HeIdiomPhrasemeFeatureBagsSchema as S98 } from "../../../src/schemas/concrete-language/he/phraseme/idiom.js";
import type { HeProverbPhrasemeFeatureBagsSchema as S99 } from "../../../src/schemas/concrete-language/he/phraseme/proverb.js";
export type Bags = {
 de: {
  Construction: { Fusion: z.output<typeof S0>; };
  Lexeme: { ADJ: z.output<typeof S1>; ADP: z.output<typeof S2>; ADV: z.output<typeof S3>; AUX: z.output<typeof S4>; CCONJ: z.output<typeof S5>; DET: z.output<typeof S6>; INTJ: z.output<typeof S7>; NOUN: z.output<typeof S8>; NUM: z.output<typeof S9>; X: z.output<typeof S10>; PART: z.output<typeof S11>; PRON: z.output<typeof S12>; PROPN: z.output<typeof S13>; PUNCT: z.output<typeof S14>; SCONJ: z.output<typeof S15>; SYM: z.output<typeof S16>; VERB: z.output<typeof S17>; };
  Morpheme: { Circumfix: z.output<typeof S18>; Clitic: z.output<typeof S19>; Duplifix: z.output<typeof S20>; Infix: z.output<typeof S21>; Interfix: z.output<typeof S22>; Prefix: z.output<typeof S23>; Root: z.output<typeof S24>; Suffix: z.output<typeof S25>; Suffixoid: z.output<typeof S26>; ToneMarking: z.output<typeof S27>; Transfix: z.output<typeof S28>; };
  Phraseme: { Aphorism: z.output<typeof S29>; Collocation: z.output<typeof S30>; DiscourseFormula: z.output<typeof S31>; Idiom: z.output<typeof S32>; Proverb: z.output<typeof S33>; };
 };
 en: {
  Construction: { Fusion: z.output<typeof S34>; };
  Lexeme: { ADJ: z.output<typeof S35>; ADP: z.output<typeof S36>; ADV: z.output<typeof S37>; AUX: z.output<typeof S38>; CCONJ: z.output<typeof S39>; DET: z.output<typeof S40>; INTJ: z.output<typeof S41>; NOUN: z.output<typeof S42>; NUM: z.output<typeof S43>; X: z.output<typeof S44>; PART: z.output<typeof S45>; PRON: z.output<typeof S46>; PROPN: z.output<typeof S47>; PUNCT: z.output<typeof S48>; SCONJ: z.output<typeof S49>; SYM: z.output<typeof S50>; VERB: z.output<typeof S51>; };
  Morpheme: { Circumfix: z.output<typeof S52>; Clitic: z.output<typeof S53>; Duplifix: z.output<typeof S54>; Infix: z.output<typeof S55>; Interfix: z.output<typeof S56>; Prefix: z.output<typeof S57>; Root: z.output<typeof S58>; Suffix: z.output<typeof S59>; Suffixoid: z.output<typeof S60>; ToneMarking: z.output<typeof S61>; Transfix: z.output<typeof S62>; };
  Phraseme: { Aphorism: z.output<typeof S63>; DiscourseFormula: z.output<typeof S64>; Idiom: z.output<typeof S65>; Proverb: z.output<typeof S66>; };
 };
 he: {
  Construction: { Fusion: z.output<typeof S67>; };
  Lexeme: { ADJ: z.output<typeof S68>; ADP: z.output<typeof S69>; ADV: z.output<typeof S70>; AUX: z.output<typeof S71>; CCONJ: z.output<typeof S72>; DET: z.output<typeof S73>; INTJ: z.output<typeof S74>; NOUN: z.output<typeof S75>; NUM: z.output<typeof S76>; X: z.output<typeof S77>; PART: z.output<typeof S78>; PRON: z.output<typeof S79>; PROPN: z.output<typeof S80>; PUNCT: z.output<typeof S81>; SCONJ: z.output<typeof S82>; SYM: z.output<typeof S83>; VERB: z.output<typeof S84>; };
  Morpheme: { Circumfix: z.output<typeof S85>; Clitic: z.output<typeof S86>; Duplifix: z.output<typeof S87>; Infix: z.output<typeof S88>; Interfix: z.output<typeof S89>; Prefix: z.output<typeof S90>; Root: z.output<typeof S91>; Suffix: z.output<typeof S92>; Suffixoid: z.output<typeof S93>; ToneMarking: z.output<typeof S94>; Transfix: z.output<typeof S95>; };
  Phraseme: { Aphorism: z.output<typeof S96>; DiscourseFormula: z.output<typeof S97>; Idiom: z.output<typeof S98>; Proverb: z.output<typeof S99>; };
 };
};

export type Language = keyof Bags;
export type Family<L extends Language> = L extends Language ? keyof Bags[L] : never;
export type Kind<L extends Language,F extends Family<L>> = L extends Language ? F extends keyof Bags[L] ? keyof Bags[L][F] : never : never;
type Bag<L extends Language,F extends Family<L>,K extends Kind<L,F>> = F extends keyof Bags[L] ? K extends keyof Bags[L][F] ? Bags[L][F][K] : never : never;
type Core<B> = B extends {core: infer C} ? C : never;
type Infl<B> = B extends {inflectional: infer I} ? I : never;
type Pretty<T> = T extends object ? {[P in keyof T]: Pretty<T[P]>} : T;
type LeafLemma<L,F,K,B> = Pretty<{language:L; family:F; kind:K; canonicalForm:string; coreFeatures:Core<B>}>;
type LeafSurface<L,F,K,B> = { language:L; normalizedSurface:string; spelling:'Canonical'|'Variant'; lemma: LeafLemma<L,F,K,B> } & ({ surfaceKind:'Citation' } | {surfaceKind:'Inflection'; inflectionalFeatures:Infl<B>});
type Wrap<U,L,F,K,B> = U extends 'Lemma' ? LeafLemma<L,F,K,B> : U extends 'Reading' ? {lemma: LeafLemma<L,F,K,B>;emojiDescription:string} : U extends 'Surface' ? Pretty<LeafSurface<L,F,K,B>> : {surface:Pretty<LeafSurface<L,F,K,B>>;members: readonly [{attested:string;orthography:string},...{attested:string;orthography:string}[]];realizationCoverage:'Full'|'Partial'};
export type UnitKind='Lemma'|'Reading'|'Surface'|'Attestation';
export type Unit<U extends UnitKind,L extends Language=Language,F extends Family<L>=Family<L>,K extends Kind<L,F>=Kind<L,F>> = L extends Language ? F extends Family<L> ? K extends Kind<L,F> ? Wrap<U,L,F,K,Bag<L,F,K>> : never : never : never;
export type Lemma<L extends Language=Language,F extends Family<L>=Family<L>,K extends Kind<L,F>=Kind<L,F>> = Unit<'Lemma',L,F,K>;
export type Surface<L extends Language=Language,F extends Family<L>=Family<L>,K extends Kind<L,F>=Kind<L,F>> = Unit<'Surface',L,F,K>;
export type Reading<L extends Language=Language,F extends Family<L>=Family<L>,K extends Kind<L,F>=Kind<L,F>> = {lemma:Lemma<L,F,K>;emojiDescription:string};
export type AbstractLemma<L extends Language=Language> = {language:L;family:Family<L>;kind:Kind<L,Family<L>>;canonicalForm:string;coreFeatures:Record<string,unknown>};
export type AbstractSurface<L extends Language=Language> = {language:L;lemma:AbstractLemma<L>;normalizedSurface:string;spelling:'Canonical'|'Variant'} & ({surfaceKind:'Citation'}|{surfaceKind:'Inflection';inflectionalFeatures:Record<string,unknown>});
export type AbstractUnit<L extends Language=Language> = AbstractLemma<L>|AbstractSurface<L>|{lemma:AbstractLemma<L>;emojiDescription:string}|{surface:AbstractSurface<L>;members:readonly object[];realizationCoverage:'Full'|'Partial'};
