// Generated direct-Zod control with the same wrappers and static imports.
import { z } from "zod";
import { DeConstructionFusionFeatureBagsSchema as bag0 } from "../../src/schemas/concrete-language/de/construction/fusion.ts";
import { DeAdjectiveFeatureBagsSchema as bag1 } from "../../src/schemas/concrete-language/de/lexeme/adjective.ts";
import { DeAdpositionFeatureBagsSchema as bag2 } from "../../src/schemas/concrete-language/de/lexeme/adposition.ts";
import { DeAdverbFeatureBagsSchema as bag3 } from "../../src/schemas/concrete-language/de/lexeme/adverb.ts";
import { DeAuxiliaryFeatureBagsSchema as bag4 } from "../../src/schemas/concrete-language/de/lexeme/auxiliary.ts";
import { DeCoordinatingConjunctionFeatureBagsSchema as bag5 } from "../../src/schemas/concrete-language/de/lexeme/coordinating-conjunction.ts";
import { DeDeterminerFeatureBagsSchema as bag6 } from "../../src/schemas/concrete-language/de/lexeme/determiner.ts";
import { DeInterjectionFeatureBagsSchema as bag7 } from "../../src/schemas/concrete-language/de/lexeme/interjection.ts";
import { DeNounFeatureBagsSchema as bag8 } from "../../src/schemas/concrete-language/de/lexeme/noun.ts";
import { DeNumeralFeatureBagsSchema as bag9 } from "../../src/schemas/concrete-language/de/lexeme/numeral.ts";
import { DeOtherFeatureBagsSchema as bag10 } from "../../src/schemas/concrete-language/de/lexeme/other.ts";
import { DeParticleFeatureBagsSchema as bag11 } from "../../src/schemas/concrete-language/de/lexeme/particle.ts";
import { DePronounFeatureBagsSchema as bag12 } from "../../src/schemas/concrete-language/de/lexeme/pronoun.ts";
import { DeProperNounFeatureBagsSchema as bag13 } from "../../src/schemas/concrete-language/de/lexeme/proper-noun.ts";
import { DePunctuationFeatureBagsSchema as bag14 } from "../../src/schemas/concrete-language/de/lexeme/punctuation.ts";
import { DeSubordinatingConjunctionFeatureBagsSchema as bag15 } from "../../src/schemas/concrete-language/de/lexeme/subordinating-conjunction.ts";
import { DeSymbolFeatureBagsSchema as bag16 } from "../../src/schemas/concrete-language/de/lexeme/symbol.ts";
import { DeVerbFeatureBagsSchema as bag17 } from "../../src/schemas/concrete-language/de/lexeme/verb.ts";
import { DeCircumfixMorphemeFeatureBagsSchema as bag18 } from "../../src/schemas/concrete-language/de/morpheme/circumfix.ts";
import { DeCliticMorphemeFeatureBagsSchema as bag19 } from "../../src/schemas/concrete-language/de/morpheme/clitic.ts";
import { DeDuplifixMorphemeFeatureBagsSchema as bag20 } from "../../src/schemas/concrete-language/de/morpheme/duplifix.ts";
import { DeInfixMorphemeFeatureBagsSchema as bag21 } from "../../src/schemas/concrete-language/de/morpheme/infix.ts";
import { DeInterfixMorphemeFeatureBagsSchema as bag22 } from "../../src/schemas/concrete-language/de/morpheme/interfix.ts";
import { DePrefixMorphemeFeatureBagsSchema as bag23 } from "../../src/schemas/concrete-language/de/morpheme/prefix.ts";
import { DeRootMorphemeFeatureBagsSchema as bag24 } from "../../src/schemas/concrete-language/de/morpheme/root.ts";
import { DeSuffixMorphemeFeatureBagsSchema as bag25 } from "../../src/schemas/concrete-language/de/morpheme/suffix.ts";
import { DeSuffixoidMorphemeFeatureBagsSchema as bag26 } from "../../src/schemas/concrete-language/de/morpheme/suffixoid.ts";
import { DeToneMarkingMorphemeFeatureBagsSchema as bag27 } from "../../src/schemas/concrete-language/de/morpheme/tone-marking.ts";
import { DeTransfixMorphemeFeatureBagsSchema as bag28 } from "../../src/schemas/concrete-language/de/morpheme/transfix.ts";
import { DeAphorismPhrasemeFeatureBagsSchema as bag29 } from "../../src/schemas/concrete-language/de/phraseme/aphorism.ts";
import { DeCollocationPhrasemeFeatureBagsSchema as bag30 } from "../../src/schemas/concrete-language/de/phraseme/collocation.ts";
import { DeDiscourseFormulaPhrasemeFeatureBagsSchema as bag31 } from "../../src/schemas/concrete-language/de/phraseme/discourse-formula.ts";
import { DeIdiomPhrasemeFeatureBagsSchema as bag32 } from "../../src/schemas/concrete-language/de/phraseme/idiom.ts";
import { DeProverbPhrasemeFeatureBagsSchema as bag33 } from "../../src/schemas/concrete-language/de/phraseme/proverb.ts";
import { EnConstructionFusionFeatureBagsSchema as bag34 } from "../../src/schemas/concrete-language/en/construction/fusion.ts";
import { EnAdjectiveFeatureBagsSchema as bag35 } from "../../src/schemas/concrete-language/en/lexeme/adjective.ts";
import { EnAdpositionFeatureBagsSchema as bag36 } from "../../src/schemas/concrete-language/en/lexeme/adposition.ts";
import { EnAdverbFeatureBagsSchema as bag37 } from "../../src/schemas/concrete-language/en/lexeme/adverb.ts";
import { EnAuxiliaryFeatureBagsSchema as bag38 } from "../../src/schemas/concrete-language/en/lexeme/auxiliary.ts";
import { EnCoordinatingConjunctionFeatureBagsSchema as bag39 } from "../../src/schemas/concrete-language/en/lexeme/coordinating-conjunction.ts";
import { EnDeterminerFeatureBagsSchema as bag40 } from "../../src/schemas/concrete-language/en/lexeme/determiner.ts";
import { EnInterjectionFeatureBagsSchema as bag41 } from "../../src/schemas/concrete-language/en/lexeme/interjection.ts";
import { EnNounFeatureBagsSchema as bag42 } from "../../src/schemas/concrete-language/en/lexeme/noun.ts";
import { EnNumeralFeatureBagsSchema as bag43 } from "../../src/schemas/concrete-language/en/lexeme/numeral.ts";
import { EnOtherFeatureBagsSchema as bag44 } from "../../src/schemas/concrete-language/en/lexeme/other.ts";
import { EnParticleFeatureBagsSchema as bag45 } from "../../src/schemas/concrete-language/en/lexeme/particle.ts";
import { EnPronounFeatureBagsSchema as bag46 } from "../../src/schemas/concrete-language/en/lexeme/pronoun.ts";
import { EnProperNounFeatureBagsSchema as bag47 } from "../../src/schemas/concrete-language/en/lexeme/proper-noun.ts";
import { EnPunctuationFeatureBagsSchema as bag48 } from "../../src/schemas/concrete-language/en/lexeme/punctuation.ts";
import { EnSubordinatingConjunctionFeatureBagsSchema as bag49 } from "../../src/schemas/concrete-language/en/lexeme/subordinating-conjunction.ts";
import { EnSymbolFeatureBagsSchema as bag50 } from "../../src/schemas/concrete-language/en/lexeme/symbol.ts";
import { EnVerbFeatureBagsSchema as bag51 } from "../../src/schemas/concrete-language/en/lexeme/verb.ts";
import { EnCircumfixMorphemeFeatureBagsSchema as bag52 } from "../../src/schemas/concrete-language/en/morpheme/circumfix.ts";
import { EnCliticMorphemeFeatureBagsSchema as bag53 } from "../../src/schemas/concrete-language/en/morpheme/clitic.ts";
import { EnDuplifixMorphemeFeatureBagsSchema as bag54 } from "../../src/schemas/concrete-language/en/morpheme/duplifix.ts";
import { EnInfixMorphemeFeatureBagsSchema as bag55 } from "../../src/schemas/concrete-language/en/morpheme/infix.ts";
import { EnInterfixMorphemeFeatureBagsSchema as bag56 } from "../../src/schemas/concrete-language/en/morpheme/interfix.ts";
import { EnPrefixMorphemeFeatureBagsSchema as bag57 } from "../../src/schemas/concrete-language/en/morpheme/prefix.ts";
import { EnRootMorphemeFeatureBagsSchema as bag58 } from "../../src/schemas/concrete-language/en/morpheme/root.ts";
import { EnSuffixMorphemeFeatureBagsSchema as bag59 } from "../../src/schemas/concrete-language/en/morpheme/suffix.ts";
import { EnSuffixoidMorphemeFeatureBagsSchema as bag60 } from "../../src/schemas/concrete-language/en/morpheme/suffixoid.ts";
import { EnToneMarkingMorphemeFeatureBagsSchema as bag61 } from "../../src/schemas/concrete-language/en/morpheme/tone-marking.ts";
import { EnTransfixMorphemeFeatureBagsSchema as bag62 } from "../../src/schemas/concrete-language/en/morpheme/transfix.ts";
import { EnAphorismPhrasemeFeatureBagsSchema as bag63 } from "../../src/schemas/concrete-language/en/phraseme/aphorism.ts";
import { EnDiscourseFormulaPhrasemeFeatureBagsSchema as bag64 } from "../../src/schemas/concrete-language/en/phraseme/discourse-formula.ts";
import { EnIdiomPhrasemeFeatureBagsSchema as bag65 } from "../../src/schemas/concrete-language/en/phraseme/idiom.ts";
import { EnProverbPhrasemeFeatureBagsSchema as bag66 } from "../../src/schemas/concrete-language/en/phraseme/proverb.ts";
import { HeConstructionFusionFeatureBagsSchema as bag67 } from "../../src/schemas/concrete-language/he/construction/fusion.ts";
import { HeAdjectiveFeatureBagsSchema as bag68 } from "../../src/schemas/concrete-language/he/lexeme/adjective.ts";
import { HeAdpositionFeatureBagsSchema as bag69 } from "../../src/schemas/concrete-language/he/lexeme/adposition.ts";
import { HeAdverbFeatureBagsSchema as bag70 } from "../../src/schemas/concrete-language/he/lexeme/adverb.ts";
import { HeAuxiliaryFeatureBagsSchema as bag71 } from "../../src/schemas/concrete-language/he/lexeme/auxiliary.ts";
import { HeCoordinatingConjunctionFeatureBagsSchema as bag72 } from "../../src/schemas/concrete-language/he/lexeme/coordinating-conjunction.ts";
import { HeDeterminerFeatureBagsSchema as bag73 } from "../../src/schemas/concrete-language/he/lexeme/determiner.ts";
import { HeInterjectionFeatureBagsSchema as bag74 } from "../../src/schemas/concrete-language/he/lexeme/interjection.ts";
import { HeNounFeatureBagsSchema as bag75 } from "../../src/schemas/concrete-language/he/lexeme/noun.ts";
import { HeNumeralFeatureBagsSchema as bag76 } from "../../src/schemas/concrete-language/he/lexeme/numeral.ts";
import { HeOtherFeatureBagsSchema as bag77 } from "../../src/schemas/concrete-language/he/lexeme/other.ts";
import { HeParticleFeatureBagsSchema as bag78 } from "../../src/schemas/concrete-language/he/lexeme/particle.ts";
import { HePronounFeatureBagsSchema as bag79 } from "../../src/schemas/concrete-language/he/lexeme/pronoun.ts";
import { HeProperNounFeatureBagsSchema as bag80 } from "../../src/schemas/concrete-language/he/lexeme/proper-noun.ts";
import { HePunctuationFeatureBagsSchema as bag81 } from "../../src/schemas/concrete-language/he/lexeme/punctuation.ts";
import { HeSubordinatingConjunctionFeatureBagsSchema as bag82 } from "../../src/schemas/concrete-language/he/lexeme/subordinating-conjunction.ts";
import { HeSymbolFeatureBagsSchema as bag83 } from "../../src/schemas/concrete-language/he/lexeme/symbol.ts";
import { HeVerbFeatureBagsSchema as bag84 } from "../../src/schemas/concrete-language/he/lexeme/verb.ts";
import { HeCircumfixMorphemeFeatureBagsSchema as bag85 } from "../../src/schemas/concrete-language/he/morpheme/circumfix.ts";
import { HeCliticMorphemeFeatureBagsSchema as bag86 } from "../../src/schemas/concrete-language/he/morpheme/clitic.ts";
import { HeDuplifixMorphemeFeatureBagsSchema as bag87 } from "../../src/schemas/concrete-language/he/morpheme/duplifix.ts";
import { HeInfixMorphemeFeatureBagsSchema as bag88 } from "../../src/schemas/concrete-language/he/morpheme/infix.ts";
import { HeInterfixMorphemeFeatureBagsSchema as bag89 } from "../../src/schemas/concrete-language/he/morpheme/interfix.ts";
import { HePrefixMorphemeFeatureBagsSchema as bag90 } from "../../src/schemas/concrete-language/he/morpheme/prefix.ts";
import { HeRootMorphemeFeatureBagsSchema as bag91 } from "../../src/schemas/concrete-language/he/morpheme/root.ts";
import { HeSuffixMorphemeFeatureBagsSchema as bag92 } from "../../src/schemas/concrete-language/he/morpheme/suffix.ts";
import { HeSuffixoidMorphemeFeatureBagsSchema as bag93 } from "../../src/schemas/concrete-language/he/morpheme/suffixoid.ts";
import { HeToneMarkingMorphemeFeatureBagsSchema as bag94 } from "../../src/schemas/concrete-language/he/morpheme/tone-marking.ts";
import { HeTransfixMorphemeFeatureBagsSchema as bag95 } from "../../src/schemas/concrete-language/he/morpheme/transfix.ts";
import { HeAphorismPhrasemeFeatureBagsSchema as bag96 } from "../../src/schemas/concrete-language/he/phraseme/aphorism.ts";
import { HeDiscourseFormulaPhrasemeFeatureBagsSchema as bag97 } from "../../src/schemas/concrete-language/he/phraseme/discourse-formula.ts";
import { HeIdiomPhrasemeFeatureBagsSchema as bag98 } from "../../src/schemas/concrete-language/he/phraseme/idiom.ts";
import { HeProverbPhrasemeFeatureBagsSchema as bag99 } from "../../src/schemas/concrete-language/he/phraseme/proverb.ts";
const registry = new Map<string, z.ZodType>([["de/Construction/Fusion", z.strictObject({ language:z.literal("de"), family:z.literal("Construction"), kind:z.literal("Fusion"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag0 })],
["de/Lexeme/ADJ", z.strictObject({ language:z.literal("de"), family:z.literal("Lexeme"), kind:z.literal("ADJ"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag1 })],
["de/Lexeme/ADP", z.strictObject({ language:z.literal("de"), family:z.literal("Lexeme"), kind:z.literal("ADP"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag2 })],
["de/Lexeme/ADV", z.strictObject({ language:z.literal("de"), family:z.literal("Lexeme"), kind:z.literal("ADV"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag3 })],
["de/Lexeme/AUX", z.strictObject({ language:z.literal("de"), family:z.literal("Lexeme"), kind:z.literal("AUX"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag4 })],
["de/Lexeme/CCONJ", z.strictObject({ language:z.literal("de"), family:z.literal("Lexeme"), kind:z.literal("CCONJ"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag5 })],
["de/Lexeme/DET", z.strictObject({ language:z.literal("de"), family:z.literal("Lexeme"), kind:z.literal("DET"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag6 })],
["de/Lexeme/INTJ", z.strictObject({ language:z.literal("de"), family:z.literal("Lexeme"), kind:z.literal("INTJ"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag7 })],
["de/Lexeme/NOUN", z.strictObject({ language:z.literal("de"), family:z.literal("Lexeme"), kind:z.literal("NOUN"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag8 })],
["de/Lexeme/NUM", z.strictObject({ language:z.literal("de"), family:z.literal("Lexeme"), kind:z.literal("NUM"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag9 })],
["de/Lexeme/X", z.strictObject({ language:z.literal("de"), family:z.literal("Lexeme"), kind:z.literal("X"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag10 })],
["de/Lexeme/PART", z.strictObject({ language:z.literal("de"), family:z.literal("Lexeme"), kind:z.literal("PART"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag11 })],
["de/Lexeme/PRON", z.strictObject({ language:z.literal("de"), family:z.literal("Lexeme"), kind:z.literal("PRON"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag12 })],
["de/Lexeme/PROPN", z.strictObject({ language:z.literal("de"), family:z.literal("Lexeme"), kind:z.literal("PROPN"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag13 })],
["de/Lexeme/PUNCT", z.strictObject({ language:z.literal("de"), family:z.literal("Lexeme"), kind:z.literal("PUNCT"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag14 })],
["de/Lexeme/SCONJ", z.strictObject({ language:z.literal("de"), family:z.literal("Lexeme"), kind:z.literal("SCONJ"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag15 })],
["de/Lexeme/SYM", z.strictObject({ language:z.literal("de"), family:z.literal("Lexeme"), kind:z.literal("SYM"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag16 })],
["de/Lexeme/VERB", z.strictObject({ language:z.literal("de"), family:z.literal("Lexeme"), kind:z.literal("VERB"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag17 })],
["de/Morpheme/Circumfix", z.strictObject({ language:z.literal("de"), family:z.literal("Morpheme"), kind:z.literal("Circumfix"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag18 })],
["de/Morpheme/Clitic", z.strictObject({ language:z.literal("de"), family:z.literal("Morpheme"), kind:z.literal("Clitic"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag19 })],
["de/Morpheme/Duplifix", z.strictObject({ language:z.literal("de"), family:z.literal("Morpheme"), kind:z.literal("Duplifix"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag20 })],
["de/Morpheme/Infix", z.strictObject({ language:z.literal("de"), family:z.literal("Morpheme"), kind:z.literal("Infix"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag21 })],
["de/Morpheme/Interfix", z.strictObject({ language:z.literal("de"), family:z.literal("Morpheme"), kind:z.literal("Interfix"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag22 })],
["de/Morpheme/Prefix", z.strictObject({ language:z.literal("de"), family:z.literal("Morpheme"), kind:z.literal("Prefix"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag23 })],
["de/Morpheme/Root", z.strictObject({ language:z.literal("de"), family:z.literal("Morpheme"), kind:z.literal("Root"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag24 })],
["de/Morpheme/Suffix", z.strictObject({ language:z.literal("de"), family:z.literal("Morpheme"), kind:z.literal("Suffix"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag25 })],
["de/Morpheme/Suffixoid", z.strictObject({ language:z.literal("de"), family:z.literal("Morpheme"), kind:z.literal("Suffixoid"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag26 })],
["de/Morpheme/ToneMarking", z.strictObject({ language:z.literal("de"), family:z.literal("Morpheme"), kind:z.literal("ToneMarking"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag27 })],
["de/Morpheme/Transfix", z.strictObject({ language:z.literal("de"), family:z.literal("Morpheme"), kind:z.literal("Transfix"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag28 })],
["de/Phraseme/Aphorism", z.strictObject({ language:z.literal("de"), family:z.literal("Phraseme"), kind:z.literal("Aphorism"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag29 })],
["de/Phraseme/Collocation", z.strictObject({ language:z.literal("de"), family:z.literal("Phraseme"), kind:z.literal("Collocation"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag30 })],
["de/Phraseme/DiscourseFormula", z.strictObject({ language:z.literal("de"), family:z.literal("Phraseme"), kind:z.literal("DiscourseFormula"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag31 })],
["de/Phraseme/Idiom", z.strictObject({ language:z.literal("de"), family:z.literal("Phraseme"), kind:z.literal("Idiom"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag32 })],
["de/Phraseme/Proverb", z.strictObject({ language:z.literal("de"), family:z.literal("Phraseme"), kind:z.literal("Proverb"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag33 })],
["en/Construction/Fusion", z.strictObject({ language:z.literal("en"), family:z.literal("Construction"), kind:z.literal("Fusion"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag34 })],
["en/Lexeme/ADJ", z.strictObject({ language:z.literal("en"), family:z.literal("Lexeme"), kind:z.literal("ADJ"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag35 })],
["en/Lexeme/ADP", z.strictObject({ language:z.literal("en"), family:z.literal("Lexeme"), kind:z.literal("ADP"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag36 })],
["en/Lexeme/ADV", z.strictObject({ language:z.literal("en"), family:z.literal("Lexeme"), kind:z.literal("ADV"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag37 })],
["en/Lexeme/AUX", z.strictObject({ language:z.literal("en"), family:z.literal("Lexeme"), kind:z.literal("AUX"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag38 })],
["en/Lexeme/CCONJ", z.strictObject({ language:z.literal("en"), family:z.literal("Lexeme"), kind:z.literal("CCONJ"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag39 })],
["en/Lexeme/DET", z.strictObject({ language:z.literal("en"), family:z.literal("Lexeme"), kind:z.literal("DET"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag40 })],
["en/Lexeme/INTJ", z.strictObject({ language:z.literal("en"), family:z.literal("Lexeme"), kind:z.literal("INTJ"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag41 })],
["en/Lexeme/NOUN", z.strictObject({ language:z.literal("en"), family:z.literal("Lexeme"), kind:z.literal("NOUN"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag42 })],
["en/Lexeme/NUM", z.strictObject({ language:z.literal("en"), family:z.literal("Lexeme"), kind:z.literal("NUM"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag43 })],
["en/Lexeme/X", z.strictObject({ language:z.literal("en"), family:z.literal("Lexeme"), kind:z.literal("X"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag44 })],
["en/Lexeme/PART", z.strictObject({ language:z.literal("en"), family:z.literal("Lexeme"), kind:z.literal("PART"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag45 })],
["en/Lexeme/PRON", z.strictObject({ language:z.literal("en"), family:z.literal("Lexeme"), kind:z.literal("PRON"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag46 })],
["en/Lexeme/PROPN", z.strictObject({ language:z.literal("en"), family:z.literal("Lexeme"), kind:z.literal("PROPN"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag47 })],
["en/Lexeme/PUNCT", z.strictObject({ language:z.literal("en"), family:z.literal("Lexeme"), kind:z.literal("PUNCT"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag48 })],
["en/Lexeme/SCONJ", z.strictObject({ language:z.literal("en"), family:z.literal("Lexeme"), kind:z.literal("SCONJ"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag49 })],
["en/Lexeme/SYM", z.strictObject({ language:z.literal("en"), family:z.literal("Lexeme"), kind:z.literal("SYM"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag50 })],
["en/Lexeme/VERB", z.strictObject({ language:z.literal("en"), family:z.literal("Lexeme"), kind:z.literal("VERB"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag51 })],
["en/Morpheme/Circumfix", z.strictObject({ language:z.literal("en"), family:z.literal("Morpheme"), kind:z.literal("Circumfix"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag52 })],
["en/Morpheme/Clitic", z.strictObject({ language:z.literal("en"), family:z.literal("Morpheme"), kind:z.literal("Clitic"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag53 })],
["en/Morpheme/Duplifix", z.strictObject({ language:z.literal("en"), family:z.literal("Morpheme"), kind:z.literal("Duplifix"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag54 })],
["en/Morpheme/Infix", z.strictObject({ language:z.literal("en"), family:z.literal("Morpheme"), kind:z.literal("Infix"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag55 })],
["en/Morpheme/Interfix", z.strictObject({ language:z.literal("en"), family:z.literal("Morpheme"), kind:z.literal("Interfix"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag56 })],
["en/Morpheme/Prefix", z.strictObject({ language:z.literal("en"), family:z.literal("Morpheme"), kind:z.literal("Prefix"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag57 })],
["en/Morpheme/Root", z.strictObject({ language:z.literal("en"), family:z.literal("Morpheme"), kind:z.literal("Root"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag58 })],
["en/Morpheme/Suffix", z.strictObject({ language:z.literal("en"), family:z.literal("Morpheme"), kind:z.literal("Suffix"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag59 })],
["en/Morpheme/Suffixoid", z.strictObject({ language:z.literal("en"), family:z.literal("Morpheme"), kind:z.literal("Suffixoid"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag60 })],
["en/Morpheme/ToneMarking", z.strictObject({ language:z.literal("en"), family:z.literal("Morpheme"), kind:z.literal("ToneMarking"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag61 })],
["en/Morpheme/Transfix", z.strictObject({ language:z.literal("en"), family:z.literal("Morpheme"), kind:z.literal("Transfix"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag62 })],
["en/Phraseme/Aphorism", z.strictObject({ language:z.literal("en"), family:z.literal("Phraseme"), kind:z.literal("Aphorism"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag63 })],
["en/Phraseme/DiscourseFormula", z.strictObject({ language:z.literal("en"), family:z.literal("Phraseme"), kind:z.literal("DiscourseFormula"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag64 })],
["en/Phraseme/Idiom", z.strictObject({ language:z.literal("en"), family:z.literal("Phraseme"), kind:z.literal("Idiom"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag65 })],
["en/Phraseme/Proverb", z.strictObject({ language:z.literal("en"), family:z.literal("Phraseme"), kind:z.literal("Proverb"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag66 })],
["he/Construction/Fusion", z.strictObject({ language:z.literal("he"), family:z.literal("Construction"), kind:z.literal("Fusion"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag67 })],
["he/Lexeme/ADJ", z.strictObject({ language:z.literal("he"), family:z.literal("Lexeme"), kind:z.literal("ADJ"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag68 })],
["he/Lexeme/ADP", z.strictObject({ language:z.literal("he"), family:z.literal("Lexeme"), kind:z.literal("ADP"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag69 })],
["he/Lexeme/ADV", z.strictObject({ language:z.literal("he"), family:z.literal("Lexeme"), kind:z.literal("ADV"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag70 })],
["he/Lexeme/AUX", z.strictObject({ language:z.literal("he"), family:z.literal("Lexeme"), kind:z.literal("AUX"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag71 })],
["he/Lexeme/CCONJ", z.strictObject({ language:z.literal("he"), family:z.literal("Lexeme"), kind:z.literal("CCONJ"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag72 })],
["he/Lexeme/DET", z.strictObject({ language:z.literal("he"), family:z.literal("Lexeme"), kind:z.literal("DET"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag73 })],
["he/Lexeme/INTJ", z.strictObject({ language:z.literal("he"), family:z.literal("Lexeme"), kind:z.literal("INTJ"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag74 })],
["he/Lexeme/NOUN", z.strictObject({ language:z.literal("he"), family:z.literal("Lexeme"), kind:z.literal("NOUN"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag75 })],
["he/Lexeme/NUM", z.strictObject({ language:z.literal("he"), family:z.literal("Lexeme"), kind:z.literal("NUM"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag76 })],
["he/Lexeme/X", z.strictObject({ language:z.literal("he"), family:z.literal("Lexeme"), kind:z.literal("X"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag77 })],
["he/Lexeme/PART", z.strictObject({ language:z.literal("he"), family:z.literal("Lexeme"), kind:z.literal("PART"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag78 })],
["he/Lexeme/PRON", z.strictObject({ language:z.literal("he"), family:z.literal("Lexeme"), kind:z.literal("PRON"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag79 })],
["he/Lexeme/PROPN", z.strictObject({ language:z.literal("he"), family:z.literal("Lexeme"), kind:z.literal("PROPN"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag80 })],
["he/Lexeme/PUNCT", z.strictObject({ language:z.literal("he"), family:z.literal("Lexeme"), kind:z.literal("PUNCT"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag81 })],
["he/Lexeme/SCONJ", z.strictObject({ language:z.literal("he"), family:z.literal("Lexeme"), kind:z.literal("SCONJ"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag82 })],
["he/Lexeme/SYM", z.strictObject({ language:z.literal("he"), family:z.literal("Lexeme"), kind:z.literal("SYM"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag83 })],
["he/Lexeme/VERB", z.strictObject({ language:z.literal("he"), family:z.literal("Lexeme"), kind:z.literal("VERB"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag84 })],
["he/Morpheme/Circumfix", z.strictObject({ language:z.literal("he"), family:z.literal("Morpheme"), kind:z.literal("Circumfix"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag85 })],
["he/Morpheme/Clitic", z.strictObject({ language:z.literal("he"), family:z.literal("Morpheme"), kind:z.literal("Clitic"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag86 })],
["he/Morpheme/Duplifix", z.strictObject({ language:z.literal("he"), family:z.literal("Morpheme"), kind:z.literal("Duplifix"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag87 })],
["he/Morpheme/Infix", z.strictObject({ language:z.literal("he"), family:z.literal("Morpheme"), kind:z.literal("Infix"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag88 })],
["he/Morpheme/Interfix", z.strictObject({ language:z.literal("he"), family:z.literal("Morpheme"), kind:z.literal("Interfix"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag89 })],
["he/Morpheme/Prefix", z.strictObject({ language:z.literal("he"), family:z.literal("Morpheme"), kind:z.literal("Prefix"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag90 })],
["he/Morpheme/Root", z.strictObject({ language:z.literal("he"), family:z.literal("Morpheme"), kind:z.literal("Root"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag91 })],
["he/Morpheme/Suffix", z.strictObject({ language:z.literal("he"), family:z.literal("Morpheme"), kind:z.literal("Suffix"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag92 })],
["he/Morpheme/Suffixoid", z.strictObject({ language:z.literal("he"), family:z.literal("Morpheme"), kind:z.literal("Suffixoid"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag93 })],
["he/Morpheme/ToneMarking", z.strictObject({ language:z.literal("he"), family:z.literal("Morpheme"), kind:z.literal("ToneMarking"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag94 })],
["he/Morpheme/Transfix", z.strictObject({ language:z.literal("he"), family:z.literal("Morpheme"), kind:z.literal("Transfix"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag95 })],
["he/Phraseme/Aphorism", z.strictObject({ language:z.literal("he"), family:z.literal("Phraseme"), kind:z.literal("Aphorism"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag96 })],
["he/Phraseme/DiscourseFormula", z.strictObject({ language:z.literal("he"), family:z.literal("Phraseme"), kind:z.literal("DiscourseFormula"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag97 })],
["he/Phraseme/Idiom", z.strictObject({ language:z.literal("he"), family:z.literal("Phraseme"), kind:z.literal("Idiom"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag98 })],
["he/Phraseme/Proverb", z.strictObject({ language:z.literal("he"), family:z.literal("Phraseme"), kind:z.literal("Proverb"), unitKind:z.enum(["Lemma","Surface","Reading","Attestation"]), value:bag99 })]]);
export const schemaCount = registry.size;
export function parseUnit(input: unknown) {
 if (typeof input !== "object" || input === null || Array.isArray(input)) return {success:false as const, issues:[{code:"invalid_type",path:[],message:"Expected unit object"}]};
 const value = input as Record<string, unknown>;
 if ([value.language,value.family,value.kind].some(coordinate => typeof coordinate !== "string")) return {success:false as const,issues:[{code:"custom",path:[],message:"Coordinates must be strings"}]};
 const schema = registry.get(`${value.language}/${value.family}/${value.kind}`);
 if (!schema) return {success:false as const, issues:[{code:"custom",path:[],message:"Unknown grammatical route"}]};
 const result = schema.safeParse(input);
 return result.success ? result : {success:false as const, issues:result.error.issues};
}
