import { readdir, readFile, writeFile } from "node:fs/promises";
import { readingKnowledgeSchema } from "dumrel/schema";
import { z } from "zod";
import {
	breakdownRecordFileSchema,
	recordFileSchema,
	textRecordFileSchema,
} from "../src/record-schema.js";

// Emits one record JSON Schema per language, with each target's route and
// Attestation drawn from Dumling's per-route schemas and its Reading Knowledge
// from dumrel's schema, one Breakdown Record Schema per language, with its
// Locution and Saying Lemmas and Lexeme routes and Attestations, and one for
// Text Records, so a record's `$schema` gives editors completion and
// validation. Also emits `src/generated/routes.ts`, each language's routes,
// which the loader checks a target's route against without its Attestation.
const dumlingSchemas = new URL(
	"../../dumling/src/generated/schemas/",
	import.meta.url,
);
const check = process.argv.includes("--check");
const stale: string[] = [];

async function write(output: URL, content: string) {
	if (!check) await writeFile(output, content);
	else if ((await readFile(output, "utf8").catch(() => "")) !== content)
		stale.push(output.pathname);
}

const emit = (name: string, schema: object) =>
	write(
		new URL(`../schema/${name}.json`, import.meta.url),
		`${JSON.stringify(schema, null, "\t")}\n`,
	);

/** The Family and Kind a Dumling Lemma schema fixes. */
function routeOf(lemmaSchema: z.ZodType): { family: string; kind: string } {
	const { properties } = z.toJSONSchema(lemmaSchema, {
		io: "input",
		unrepresentable: "any",
	}) as { properties?: Record<string, { const?: unknown }> };
	const family = properties?.family?.const;
	const kind = properties?.kind?.const;
	if (typeof family !== "string" || typeof kind !== "string")
		throw Error("A Dumling Lemma schema fixes its Family and Kind");
	return { family, kind };
}

const routesByLanguage: Record<string, string[]> = {};

for (const language of ["de", "en", "he"] as const) {
	const routes = (
		await readdir(new URL(`${language}/`, dumlingSchemas), {
			recursive: true,
		})
	)
		.filter((path) => path.endsWith(".ts"))
		.map((path) => path.slice(0, -".ts".length))
		.toSorted();
	const schemas = await Promise.all(
		routes.map(async (route) => ({
			route,
			...((await import(`dumling/schema/${language}/${route}`)) as {
				lemmaSchema: z.ZodType;
				attestationSchema: z.ZodType;
			}),
		})),
	);
	const union = (members: z.ZodType[], of: string) => {
		const [first, ...rest] = members;
		if (!first) throw Error(`Dumling has no ${language} ${of}`);
		return rest.length === 0 ? first : z.union([first, ...rest]);
	};
	const routeSchemas = (from: typeof schemas) =>
		from.map(({ lemmaSchema }) => {
			const { family, kind } = routeOf(lemmaSchema);
			return z.strictObject({
				family: z.literal(family),
				kind: z.literal(kind),
			});
		});
	routesByLanguage[language] = schemas
		.map(({ lemmaSchema }) => {
			const { family, kind } = routeOf(lemmaSchema);
			return `${family}/${kind}`;
		})
		.toSorted();
	const lexemes = schemas.filter(({ route }) => route.startsWith("lexeme/"));
	const { $schema, ...body } = z.toJSONSchema(
		recordFileSchema({
			route: union(routeSchemas(schemas), "routes"),
			attestation: union(
				schemas.map((schema) => schema.attestationSchema),
				"routes",
			),
			knowledge: readingKnowledgeSchema,
		}),
		{ io: "input", unrepresentable: "any", reused: "ref" },
	);
	await emit(`spec-record.${language}`, {
		$schema,
		$id: `https://unpkg.com/dumspec/schema/spec-record.${language}.json`,
		title: `Dumspec ${language} Spec Record`,
		...body,
	});
	const { $schema: breakdownSchema, ...breakdownBody } = z.toJSONSchema(
		breakdownRecordFileSchema(
			union(
				schemas
					.filter(({ route }) =>
						/^(?:locution|saying)\//u.test(route),
					)
					.map((schema) => schema.lemmaSchema),
				"Locution or Saying routes",
			),
			{
				route: union(routeSchemas(lexemes), "Lexeme routes"),
				attestation: union(
					lexemes.map((schema) => schema.attestationSchema),
					"Lexeme routes",
				),
				knowledge: readingKnowledgeSchema,
			},
		),
		{ io: "input", unrepresentable: "any", reused: "ref" },
	);
	await emit(`breakdown-record.${language}`, {
		$schema: breakdownSchema,
		$id: `https://unpkg.com/dumspec/schema/breakdown-record.${language}.json`,
		title: `Dumspec ${language} Breakdown Record`,
		...breakdownBody,
	});
}
const { $schema, ...body } = z.toJSONSchema(textRecordFileSchema, {
	io: "input",
});
await emit("text-record", {
	$schema,
	$id: "https://unpkg.com/dumspec/schema/text-record.json",
	title: "Dumspec Text Record",
	...body,
});
await write(
	new URL("../src/generated/routes.ts", import.meta.url),
	[
		"// Generated by codegen/generate-record-schemas.ts from Dumling's route",
		"// schemas. Run bun run generate.",
		"",
		"/** Each language's routes, as `<Family>/<Kind>`. */",
		"export const unitRoutes: Readonly<Record<string, readonly string[]>> = {",
		...Object.entries(routesByLanguage).flatMap(([language, routes]) => [
			`\t${language}: [`,
			...routes.map((route) => `\t\t${JSON.stringify(route)},`),
			"\t],",
		]),
		"};",
		"",
	].join("\n"),
);
if (stale.length > 0)
	throw Error(
		`Stale generated file: ${stale.join(", ")}; run bun run generate`,
	);
