// Cursor flags
export const CURSOR_FLAG_HORIZONTAL_MIN = 0b0001;
export const CURSOR_FLAG_HORIZONTAL_MAX = 0b0010;
export const CURSOR_FLAG_VERTICAL_MIN = 0b0100;
export const CURSOR_FLAG_VERTICAL_MAX = 0b1000;
export const CURSOR_FLAGS_HORIZONTAL = 0b0011;
export const CURSOR_FLAGS_VERTICAL = 0b1100;
