import { assertCaseSelectionsUncontaminated } from "../../../../../assembly";
import { corpus } from "./corpus";

export const demonstrationSelection = corpus.select([
	"target-de-demo-perfect-arbeiten-click-habe",
	"target-de-demo-governed-rechnen-click-rechnet",
	"target-de-demo-adjunct-rechnen-click-mit",
	"target-de-demo-idiom-faden-click-den",
	"target-de-demo-aphorism-zeit-click-ist",
	"target-de-demo-literal-gras-click-biss",
	"target-de-demo-idiom-katze-click-verdammte",
	"target-de-demo-paired-einerseits-click-einerseits",
	"target-de-demo-inherent-reflexive-click-beeile",
	"target-de-demo-optional-reflexive-click-dich",
	"target-de-demo-modal-arbeiten-click-kann",
	"target-de-demo-passive-briefe-click-werden",
	"target-de-demo-repeated-anfangen-click-final-an",
	"target-de-demo-question-stattfinden-click-statt",
	"target-de-demo-typo-mitmachen-click-mit",
	"target-de-demo-predicative-cringe-click-cringe",
	"target-de-demo-paired-sowohl-click-robust",
	"target-de-demo-idiom-kragen-click-kragen",
	"target-de-demo-symbol-percent",
	"target-de-core-unresolved-qzxv",
]);

if (demonstrationSelection.ids.length > 35) {
	throw new Error(
		`German high-level prompt has ${demonstrationSelection.ids.length} demonstrations; maximum is 35.`,
	);
}

export const evaluationSelection = corpus.select([
	"target-de-route-lexeme-adj",
	"target-de-route-lexeme-adp",
	"target-de-route-lexeme-adv",
	"target-de-route-lexeme-aux",
	"target-de-route-lexeme-cconj",
	"target-de-route-lexeme-det",
	"target-de-route-lexeme-intj",
	"target-de-route-lexeme-noun",
	"target-de-route-lexeme-num",
	"target-de-route-lexeme-part",
	"target-de-route-lexeme-pron",
	"target-de-route-lexeme-propn",
	"target-de-route-lexeme-sconj",
	"target-de-route-lexeme-sym",
	"target-de-route-lexeme-verb",
	"target-de-route-phraseme-aphorism-click-wissen",
	"target-de-route-phraseme-aphorism-click-ist",
	"target-de-route-phraseme-aphorism-click-macht",
	"target-de-route-phraseme-discourse-click-herzlichen",
	"target-de-route-phraseme-discourse-click-dank",
	"target-de-route-phraseme-proverb-click-morgenstund",
	"target-de-route-phraseme-proverb-click-hat",
	"target-de-route-phraseme-proverb-click-gold",
	"target-de-route-phraseme-proverb-click-im",
	"target-de-route-phraseme-proverb-click-mund",
	"target-de-core-entscheidung-click-entscheidung",
	"target-de-core-entscheidung-click-trifft",
	"target-de-core-entscheidung-click-eine",
	"target-de-route-construction-fusion",
	"target-de-route-construction-paired-click-je",
	"target-de-route-construction-paired-click-desto",
	"target-de-route-construction-paired-near-frueher",
	"target-de-route-construction-paired-near-besser",
	"target-de-boundary-idiom-click-brach",
	"target-de-boundary-idiom-click-das",
	"target-de-boundary-idiom-click-eis",
	"target-de-boundary-idiom-near-endlich",
	"target-de-boundary-literal-eis-click-brach",
	"target-de-boundary-literal-eis-click-eis",
	"target-de-boundary-governed-click-wartet",
	"target-de-boundary-governed-click-auf",
	"target-de-boundary-governed-near-bus",
	"target-de-boundary-adjunct-click-laeuft",
	"target-de-boundary-adjunct-click-auf",
	"target-de-boundary-adjunct-click-wiese",
	"target-de-boundary-inherent-reflexive-click-schaemt",
	"target-de-boundary-inherent-reflexive-click-sich",
	"target-de-boundary-optional-reflexive-click-waescht",
	"target-de-boundary-optional-reflexive-click-sich",
	"target-de-boundary-separable-click-steht",
	"target-de-boundary-separable-click-auf",
	"target-de-boundary-separable-near-heute",
	"target-de-boundary-perfect-click-hat",
	"target-de-boundary-perfect-click-gelacht",
	"target-de-boundary-perfect-near-laut",
	"target-de-boundary-future-click-wird",
	"target-de-boundary-future-click-lachen",
	"target-de-boundary-passive-click-wird",
	"target-de-boundary-passive-click-gelobt",
	"target-de-boundary-modal-click-muss",
	"target-de-boundary-modal-click-schlafen",
	"target-de-boundary-copula-click-ist",
	"target-de-boundary-copula-click-muede",
	"target-de-boundary-collocation-click-trifft",
	"target-de-boundary-collocation-click-eine",
	"target-de-boundary-collocation-click-entscheidung",
	"target-de-boundary-collocation-near-heute",
	"target-de-boundary-free-object-click-bringt",
	"target-de-boundary-free-object-click-cola",
	"target-de-boundary-fixed-function-click-heult",
	"target-de-boundary-fixed-function-click-mit",
	"target-de-boundary-fixed-function-click-den",
	"target-de-boundary-fixed-function-click-woelfen",
	"target-de-boundary-fixed-function-near-hungrigen",
	"target-de-robust-repeated-click-steht",
	"target-de-robust-repeated-click-final-auf",
	"target-de-robust-repeated-near-first-auf",
	"target-de-robust-overlap-collocation-click-stellt",
	"target-de-robust-overlap-collocation-click-eine",
	"target-de-robust-overlap-collocation-click-frage",
	"target-de-robust-overlap-separable-click-stellt",
	"target-de-robust-overlap-separable-click-ab",
	"target-de-robust-overlap-near-vase",
	"target-de-robust-partial-click-brach",
	"target-de-robust-partial-click-das",
	"target-de-robust-typo-click-stet",
	"target-de-robust-typo-click-auf",
	"target-de-robust-slang",
	"target-de-robust-opaque-surroundings",
	"target-de-robust-punctuation-click-steht",
	"target-de-robust-punctuation-click-auf",
	"target-de-robust-long-click-wird",
	"target-de-robust-long-click-verstanden",
	"target-de-robust-unresolved",
]);

export const diagnosticSelection = corpus.select([
	"target-de-route-construction-fusion",
	"target-de-diagnostic-fusion-am",
	"target-de-route-construction-paired-near-frueher",
	"target-de-route-construction-paired-near-besser",
	"target-de-diagnostic-paired-je-near-waermer",
	"target-de-diagnostic-paired-je-near-schoener",
	"target-de-diagnostic-paired-entweder-near-kaffee",
	"target-de-diagnostic-paired-entweder-near-tee",
	"target-de-boundary-idiom-near-endlich",
	"target-de-boundary-fixed-function-click-heult",
	"target-de-boundary-fixed-function-click-mit",
	"target-de-boundary-fixed-function-click-woelfen",
	"target-de-boundary-fixed-function-near-hungrigen",
	"target-de-diagnostic-idiom-oel-click-goss",
	"target-de-diagnostic-idiom-oel-click-oel",
	"target-de-diagnostic-idiom-oel-click-ins",
	"target-de-diagnostic-idiom-oel-click-feuer",
	"target-de-diagnostic-idiom-oel-near-zusaetzliches",
	"target-de-boundary-optional-reflexive-click-sich",
	"target-de-diagnostic-optional-reflexive-click-rasiert",
	"target-de-diagnostic-optional-reflexive-click-sich",
	"target-de-boundary-copula-click-ist",
	"target-de-diagnostic-copula-click-bleibt",
	"target-de-robust-overlap-separable-click-stellt",
	"target-de-robust-punctuation-click-auf",
	"target-de-robust-repeated-click-steht",
	"target-de-robust-repeated-near-first-auf",
	"target-de-diagnostic-repeated-click-kommt",
	"target-de-diagnostic-repeated-click-final-an",
	"target-de-diagnostic-repeated-near-first-an",
	"target-de-diagnostic-punctuation-click-hoert",
	"target-de-diagnostic-punctuation-click-auf",
	"target-de-diagnostic-overlap-click-second-schaltet",
	"target-de-diagnostic-overlap-click-aus",
]);

/** The seven stable v16 misses, retained as adaptive-development carryovers. */
export const adaptiveCarryoverSelection = corpus.select([
	"target-de-route-construction-fusion",
	"target-de-route-construction-paired-near-frueher",
	"target-de-route-construction-paired-near-besser",
	"target-de-boundary-perfect-near-laut",
	"target-de-boundary-fixed-function-click-mit",
	"target-de-boundary-fixed-function-click-den",
	"target-de-robust-repeated-near-first-auf",
]);

/** The frozen 23-case novel analogue set, disjoint from the historical 94. */
export const adaptiveNovelSelection = corpus.select([
	"target-de-adaptive-fusion-beim",
	"target-de-adaptive-fusion-vom",
	"target-de-adaptive-fusion-ins",
	"target-de-adaptive-fusion-ans",
	"target-de-adaptive-paired-weder-click-weder",
	"target-de-adaptive-paired-weder-click-noch",
	"target-de-adaptive-paired-weder-near-regen",
	"target-de-adaptive-paired-weder-near-wind",
	"target-de-adaptive-paired-nicht-nur-near-klug",
	"target-de-adaptive-paired-nicht-nur-near-fleissig",
	"target-de-adaptive-perfect-near-gestern",
	"target-de-adaptive-future-near-bald",
	"target-de-adaptive-passive-near-sorgfaeltig",
	"target-de-adaptive-separable-near-ploetzlich",
	"target-de-adaptive-idiom-zahn-click-fuehlte",
	"target-de-adaptive-idiom-zahn-click-auf",
	"target-de-adaptive-idiom-zahn-click-den",
	"target-de-adaptive-idiom-zahn-click-zahn",
	"target-de-adaptive-idiom-zahn-near-gruendlich",
	"target-de-adaptive-repeated-vor-near-first-vor",
	"target-de-adaptive-repeated-vor-click-stellt",
	"target-de-adaptive-repeated-vor-click-sich",
	"target-de-adaptive-repeated-vor-click-final-vor",
]);

/**
 * Frozen adaptive prompt-development set: carryovers first, then novel probes.
 * The unchanged 94-case evaluation selection remains the final regression set.
 */
export const adaptiveDevelopmentSelection = adaptiveCarryoverSelection.union(
	adaptiveNovelSelection,
);

assertCaseSelectionsUncontaminated({
	route: corpus.route,
	demonstrations: demonstrationSelection,
	evaluation: evaluationSelection,
});

assertCaseSelectionsUncontaminated({
	route: corpus.route,
	demonstrations: demonstrationSelection,
	evaluation: adaptiveDevelopmentSelection,
});

assertCaseSelectionsUncontaminated({
	route: corpus.route,
	demonstrations: evaluationSelection,
	evaluation: adaptiveNovelSelection,
});

assertCaseSelectionsUncontaminated({
	route: corpus.route,
	demonstrations: demonstrationSelection,
	evaluation: diagnosticSelection,
});
