/**
 * The separable prefixes, the first parts of German particle verbs: an of
 * anziehen, hinaus of hinauslaufen, teil of teilnehmen, kennen of
 * kennenlernen. Rule de/verb-owns-its-scattered-members makes one a member
 * of its verb's target wherever it stands, Rule
 * de/bracket-particle-or-circumposition reads one in the verbal bracket as
 * the verb's particle, Rule de/verb-core-features lets a VERB's
 * hasSepPrefix name one, and Rule de/fused-word-pieces splits one from an
 * infixed zu (abzuspannen is ab, zu and spannen). The her- and hin-
 * adverbs' r- shorthands are among them (raus, rein; Rule
 * de/r-adverb-is-her-or-hin-shorthand). The list holds the prefixes Dumgen
 * has needed so far and every hasSepPrefix the gold names (darnieder,
 * durcheinander, flach and groß joined from it, #1057), not every German
 * one. Some also form inseparable verbs (durch, über, um, unter, voll,
 * wider: übersetzen 'translate'); they are here, not among the inseparable
 * prefixes below. spazieren is none: verb and verb are written apart, so
 * spazieren gehen is two VERBs (#1144).
 */
export const germanSeparablePrefixes: ReadonlySet<string> = new Set([
	"ab",
	"an",
	"auf",
	"aus",
	"auseinander",
	"bei",
	"beiseite",
	"bekannt",
	"bereit",
	"bloß",
	"da",
	"dabei",
	"dagegen",
	"daher",
	"dahin",
	"daneben",
	"dar",
	"darnieder",
	"davon",
	"dazu",
	"dazwischen",
	"durch",
	"durcheinander",
	"ein",
	"empor",
	"entgegen",
	"entlang",
	"entzwei",
	"fehl",
	"fern",
	"fertig",
	"fest",
	"flach",
	"fort",
	"frei",
	"gegenüber",
	"groß",
	"gut",
	"heim",
	"her",
	"herab",
	"heran",
	"herauf",
	"heraus",
	"herbei",
	"herein",
	"herüber",
	"herum",
	"herunter",
	"hervor",
	"hin",
	"hinab",
	"hinauf",
	"hinaus",
	"hinein",
	"hinterher",
	"hinüber",
	"hinunter",
	"hinweg",
	"hinzu",
	"hoch",
	"irre",
	"kaputt",
	"kennen",
	"klar",
	"kund",
	"leer",
	"leid",
	"los",
	"mit",
	"nach",
	"nahe",
	"nieder",
	"offen",
	"preis",
	"ran",
	"rauf",
	"raus",
	"rein",
	"rüber",
	"rückwärts",
	"runter",
	"sicher",
	"stand",
	"statt",
	"teil",
	"über",
	"übrig",
	"um",
	"umher",
	"unter",
	"voll",
	"vor",
	"voran",
	"voraus",
	"vorbei",
	"vorüber",
	"vorwärts",
	"vorweg",
	"wahr",
	"weg",
	"weiter",
	"wider",
	"wieder",
	"zu",
	"zurecht",
	"zurück",
	"zusammen",
	"zuvor",
]);

/**
 * The prefixes that only ever form inseparable verbs (bekommen, empfehlen,
 * verstehen): never a VERB's hasSepPrefix (Rule de/verb-core-features), and
 * never split from the verb. The prefixes that form both kinds are
 * separable prefixes above. No word is on both lists.
 */
export const germanInseparablePrefixes: ReadonlySet<string> = new Set([
	"be",
	"emp",
	"ent",
	"er",
	"ge",
	"miss",
	"ver",
	"zer",
]);
