import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { namedBlockMarkdown, runCodegen } from "codegen";

const generatorRoot = dirname(fileURLToPath(import.meta.url));

export const readmeRecipe = namedBlockMarkdown({
	template: join(generatorRoot, "README.template.md"),
	snippets: {
		root: join(generatorRoot, "examples"),
		include: ["*.ts"],
		recursive: false,
	},
	marker: "README_BLOCK",
	fence: "ts",
	preamble:
		"<!-- This file is generated by `npm run generate:readme`. Do not edit README.md by hand. -->\n\n",
	output: {
		root: resolve(generatorRoot, ".."),
		path: "README.md",
	},
	unusedBlocks: "error",
});

if (import.meta.main) {
	await runCodegen(readmeRecipe, { mode: "write" });
}
