import { expect, test } from "bun:test";
import { resolve } from "node:path";
import { namedBlockMarkdown } from "../src/named-block-markdown.js";
import { runCodegenWithFileSystem } from "../src/runner.js";
import { MemoryFileSystem } from "./memory-filesystem.js";

test("named blocks preserve the README grammar and final newline", async () => {
	const fileSystem = new MemoryFileSystem({
		"/workspace/README.template.md":
			"# Example\n\n<!-- README_BLOCK:alpha -->\n",
		"/workspace/examples/b.ts": "// no blocks\n",
		"/workspace/examples/a.ts":
			"// README_BLOCK:alpha:start\n\nconst answer = 42;\n\n// README_BLOCK:alpha:end\n",
	});
	const recipe = namedBlockMarkdown({
		template: "/workspace/README.template.md",
		snippets: {
			root: "/workspace/examples",
			include: ["*.ts"],
			recursive: false,
		},
		marker: "README_BLOCK",
		fence: "ts",
		preamble: "<!-- Generated. -->\n\n",
		output: { root: "/workspace", path: "README.md" },
		unusedBlocks: "error",
	});

	await runCodegenWithFileSystem(recipe, { mode: "write" }, fileSystem);
	expect(fileSystem.text("/workspace/README.md")).toBe(
		"<!-- Generated. -->\n\n# Example\n\n```ts\nconst answer = 42;\n```\n",
	);
});

test("named blocks retain actionable source diagnostics", async () => {
	const fileSystem = new MemoryFileSystem({
		"/workspace/README.template.md": "<!-- README_BLOCK:missing -->\n",
		"/workspace/examples/a.ts":
			"// README_BLOCK:present:start\nvalue\n// README_BLOCK:present:end\n",
	});
	const recipe = namedBlockMarkdown({
		template: "/workspace/README.template.md",
		snippets: {
			root: "/workspace/examples",
			include: ["*.ts"],
		},
		marker: "README_BLOCK",
		fence: "ts",
		preamble: "",
		output: { root: "/workspace", path: "README.md" },
		unusedBlocks: "error",
	});

	await expect(
		runCodegenWithFileSystem(recipe, { mode: "write" }, fileSystem),
	).rejects.toThrow('Missing README_BLOCK block "missing".');
	expect(fileSystem.mutations).toEqual([]);
});

for (const [packageName, command] of [
	["dumdict", "bun"],
	["dumgen", "bun"],
	["dumling", "npm"],
] as const) {
	test(`${packageName} README remains byte-for-byte generated`, async () => {
		const packageRoot = resolve(import.meta.dir, `../../${packageName}`);
		const recipe = namedBlockMarkdown({
			template: resolve(
				packageRoot,
				"generate-readme/README.template.md",
			),
			snippets: {
				root: resolve(packageRoot, "generate-readme/examples"),
				include: ["*.ts"],
				recursive: false,
			},
			marker: "README_BLOCK",
			fence: "ts",
			preamble: `<!-- This file is generated by \`${command} run generate:readme\`. Do not edit README.md by hand. -->\n\n`,
			output: { root: packageRoot, path: "README.md" },
			unusedBlocks: "error",
		});

		const result = await runCodegenWithFileSystem(
			recipe,
			{ mode: "check" },
			// Exercise the public Node filesystem without mutating.
			(await import("../src/runner.js")).nodeFileSystem,
		);
		expect(result.status).toBe("clean");
	});
}
