export const DUM_PUBLIC_ZOD_SURFACES = {
	"dumdict/schema": [
		"changePreconditionSchema",
		"commitChangesRequestSchema",
		"commitChangesResultSchema",
		"commitConflictCodeSchema",
		"dumdictPlanSchema",
		"lemmaRecordSchema",
		"pendingSemanticRelationLocatorSchema",
		"pendingSemanticRelationRecordSchema",
		"plannedChangeOpSchema",
		"readingEntrySchema",
		"readingPatchOpSchema",
		"surfaceEntrySchema",
	],
	"dumgen/schema": [
		"enabledSegmentationLanguageSchema",
		"grammaticalInputSchema",
		"grammaticalInteractionSchema",
		"grammaticalResolutionLanguageSchema",
		"grammaticalResultSchema",
		"grammaticalRouteSchema",
		"knowledgeGenerationInputSchema",
		"knowledgeGenerationLanguageSchema",
		"knowledgeGenerationRequestSchema",
		"knowledgeGenerationResultSchema",
		"notImplementedGrammaticalResultSchema",
		"requestableRelationSchema",
		"resolvedGrammaticalResultSchema",
		"section1ErrorSchema",
		"segmentKindSchema",
		"segmentSchema",
		"segmentationDecisionSchema",
		"segmentationResultSchema",
		"segmentedSentenceIdSchema",
		"segmentedSentenceSchema",
		"unresolvedGrammaticalResultSchema",
	],
	"dumling/schema": ["abstractSchemas", "anyLemmaSchema", "readingSchema"],
	"dumrel/schema": [
		"bindLexicalUnitShadow",
		"bindSupportedUnitShadow",
		"directSemanticRelationGraphEdgeSchema",
		"directSemanticRelationSchema",
		"directSemanticRelationValues",
		"knowledgeChangeSchema",
		"knowledgeRequestMaskSchema",
		"knowledgeSettingsSchema",
		"lemmaReferenceSchema",
		"lexemeUnitShadowSchema",
		"lexicalBreakdownSchema",
		"lexicalUnitShadowSchema",
		"morphemeReadingReferenceSchema",
		"morphologicalTreeNodeSchema",
		"morphologicalTreeSchema",
		"morphologicalTreeStructureSchema",
		"nonEmptyStringsSchema",
		"pendingSemanticRelationSchema",
		"readingKnowledgeSchema",
		"readingReferenceSchema",
		"semanticRelationGraphReadingSchema",
		"semanticRelationGraphSchema",
		"semanticRelationSchema",
		"semanticRelationValues",
		"semanticRelationsSchema",
		"unitShadowSchema",
	],
} as const;

export const DUM_DANGEROUSLY_HEAVY_ZOD_SURFACES = {
	"dumdict/dangerously-heavy-schema-tree": [
		"getDangerouslyHeavyDumdictSchemaTreeForAbout100MiBRss",
	],
	"dumling/dangerously-heavy-schema-tree": [
		"dangerouslyHeavyCompactEmojiSequencePatternForAbout100MiBRss",
		"dangerouslyHeavySchemasForAbout100MiBRss",
		"getDangerouslyHeavySchemaTreeForAbout100MiBRss",
	],
} as const;

export const DUM_OPERATIONAL_ZOD_FREE_EXPORT_SURFACES = [
	"dumling",
	"dumling/reading",
	"dumling/vocabulary",
	"dumrel",
	"dumrel/relations",
	"dumrel/settings",
	"dumrel/vocabulary",
	"dumdict",
	"dumdict/runtime",
	"dumdict/relations",
	"dumgen",
	"dumgen/projection",
	"dumgen/knowledge",
	"dumgen/knowledge-runtime",
	"dumgen/openai-fetch",
	"dumgen/runtime",
	"dumgen/runtime-prompt-data",
	"dumgen/vocabulary",
] as const;
