import { operationalEntrypoints } from "./dum-entrypoint-rss/inventory";

export const DUM_PUBLIC_ZOD_SURFACES = {
	"dumrel/schema": [
		"directSemanticRelationSchema",
		"governedCaseSchema",
		"governedPrepositionSchema",
		"governedPrepositionsSchema",
		"governmentProjectionSchema",
		"governmentRelationSchema",
		"knowledgeChangeSchema",
		"knowledgeRequestMaskSchema",
		"knowledgeRouteSchema",
		"knowledgeSelectionInputSchema",
		"knowledgeSettingsSchema",
		"lexemeUnitShadowSchema",
		"lexicalBreakdownSchema",
		"morphologicalTreeNodeSchema",
		"morphologicalTreeSchema",
		"pendingSemanticRelationSchema",
		"readingKnowledgeSchema",
		"readingWithKnowledgeSchema",
		"semanticProjectionInputSchema",
		"semanticRelationProjectionSchema",
		"semanticRelationSchema",
		"semanticRelationsSchema",
		"translationLanguageSchema",
		"unitShadowSchema",
	],
	"dumdict/schema": [
		"changePreconditionSchema",
		"commitChangesRequestSchema",
		"commitChangesResultSchema",
		"commitConflictCodeSchema",
		"dumdictPlanSchema",
		"lemmaRecordSchema",
		"pendingSemanticRelationLocatorSchema",
		"pendingSemanticRelationRecordSchema",
		"plannedChangeOpSchema",
		"readingEntrySchema",
		"readingPatchOpSchema",
		"surfaceEntrySchema",
	],
	"dumgen/schemas": [
		"analysisTargetSchema",
		"classifyInputSchema",
		"comparisonInputSchema",
		"encounterSchema",
		"knowledgeInputSchema",
		"knowledgeProductionSchema",
		"knowledgeRequestMaskSchema",
		"segmentInputSchema",
		"segmentSchema",
		"segmentationDecisionSchema",
		"segmentedSentenceSchema",
	],
} as const;
export const DUM_OPERATIONAL_ZOD_FREE_EXPORT_SURFACES =
	operationalEntrypoints().map((entry) => entry.specifier);
