export {
	DEFAULT_KNOWLEDGE_SETTINGS,
	defaultKnowledgeRequestMask,
	intersectKnowledgeRequestMask,
} from "./applicability.js";
export { applyKnowledgeChange } from "./knowledge.js";
export {
	ParsingError,
	parseAsDirectSemanticRelationGraphEdge,
	parseAsKnowledgeChange,
	parseAsKnowledgeRequestMask,
	parseAsKnowledgeSettings,
	parseAsLexemeUnitShadow,
	parseAsLexicalBreakdown,
	parseAsLexicalUnitShadow,
	parseAsMorphemeReadingReference,
	parseAsMorphologicalTree,
	parseAsMorphologicalTreeNode,
	parseAsMorphologicalTreeStructure,
	parseAsPendingSemanticRelation,
	parseAsReadingKnowledge,
	parseAsSemanticRelationGraph,
	parseAsSemanticRelationGraphReading,
	parseAsSemanticRelations,
	parseAsUnitShadow,
} from "./parsing/lightweight-parsers.js";
export {
	inverseRelationFor,
	projectRelations,
	propagateRelations,
} from "./root-relations.js";
export type {
	DirectSemanticRelation,
	DirectSemanticRelationGraphEdge,
	KnowledgeChange,
	KnowledgeRequestMask,
	KnowledgeSettings,
	LemmaReference,
	LemmaTargetedSemanticRelationGraphEdge,
	LemmaTargetedSemanticRelations,
	LexemeUnitShadow,
	LexicalBreakdown,
	LexicalUnitShadow,
	MorphemeReadingReference,
	MorphologicalTree,
	MorphologicalTreeNode,
	MorphologicalTreeStructure,
	NonEmptyStrings,
	PendingSemanticRelation,
	ProjectedSemanticRelations,
	ReadingKnowledge,
	ReadingReference,
	ReadingTargetedSemanticRelationGraphEdge,
	ReadingTargetedSemanticRelations,
	SemanticRelation,
	SemanticRelationGraph,
	SemanticRelationGraphEdge,
	SemanticRelationGraphProjection,
	SemanticRelationGraphReading,
	SemanticRelations,
	SemanticRelationTargetKind,
	UnitShadow,
} from "./types.js";
export {
	directSemanticRelationValues,
	semanticRelationValues,
} from "./vocabulary.js";
