export {
	DEFAULT_KNOWLEDGE_SETTINGS,
	defaultKnowledgeRequestMask,
	intersectKnowledgeRequestMask,
} from "./applicability.js";
export { applyKnowledgeChange } from "./knowledge.js";
export {
	inverseRelationFor,
	projectRelations,
	propagateRelations,
} from "./root-relations.js";
export {
	directSemanticRelationGraphEdgeSchema,
	directSemanticRelationSchema,
	knowledgeChangeSchema,
	knowledgeRequestMaskSchema,
	knowledgeSettingsSchema,
	lemmaReferenceSchema,
	lexemeUnitShadowSchema,
	lexicalBreakdownSchema,
	lexicalUnitShadowSchema,
	morphemeReadingReferenceSchema,
	morphologicalTreeNodeSchema,
	morphologicalTreeSchema,
	morphologicalTreeStructureSchema,
	nonEmptyStringsSchema,
	pendingSemanticRelationSchema,
	readingKnowledgeSchema,
	readingReferenceSchema,
	semanticRelationGraphReadingSchema,
	semanticRelationGraphSchema,
	semanticRelationSchema,
	semanticRelationsSchema,
	unitShadowSchema,
} from "./schema.js";
export type {
	DirectSemanticRelation,
	DirectSemanticRelationGraphEdge,
	KnowledgeChange,
	KnowledgeRequestMask,
	KnowledgeSettings,
	LemmaReference,
	LexemeUnitShadow,
	LexicalBreakdown,
	LexicalUnitShadow,
	MorphemeReadingReference,
	MorphologicalTree,
	MorphologicalTreeNode,
	MorphologicalTreeStructure,
	NonEmptyStrings,
	PendingSemanticRelation,
	ProjectedSemanticRelations,
	ReadingKnowledge,
	ReadingReference,
	SemanticRelation,
	SemanticRelationGraph,
	SemanticRelationGraphEdge,
	SemanticRelationGraphProjection,
	SemanticRelationGraphReading,
	SemanticRelations,
	UnitShadow,
} from "./types.js";
export {
	directSemanticRelationValues,
	semanticRelationValues,
} from "./vocabulary.js";
