/**
 * `dumling/codegen`: what sibling packages' generators read from Dumling
 * (ADR 0001). It is plain data and build-time helpers, not a runtime
 * registry; the repository import policy keeps operational code from
 * importing it.
 */
import type { Family, Kind, Language } from "../src/generated/units.js";
import { routes } from "./generated/routes.js";

/** One language × Family × Kind route and where its concrete schemas live. */
export interface DumlingRoute {
	readonly language: Language;
	readonly family: Family;
	readonly kind: Kind;
	/**
	 * The path after `dumling/schema/`, which names the route's Kind in
	 * kebab case: `Lexeme/PROPN` is `de/lexeme/proper-noun`.
	 */
	readonly schemaPath: string;
}

/** Every Dumling route, sorted by schema path. Generated by `bun run generate`. */
export const dumlingRoutes: readonly DumlingRoute[] = routes;

export { registrations } from "./operations.js";
export {
	dumlingOutputTypes,
	dumlingTypePreservingOperations,
} from "./output-types.js";
