import type { ZodValidationOperationRegistration } from "dumval/compiler";
import {
	emojiDescriptionError,
	englishValencyAttestationError,
	fusedMemberError,
	fusionError,
	germanAdpositionAttestationError,
	germanClosedClassSurfaceError,
	germanDeterminerCoreError,
	germanNounSurfaceError,
	germanPronounCoreError,
	germanValencyAttestationError,
	germanVerbalAttestationError,
	germanVerbalSurfaceError,
	hasMarkedFeature,
	hebrewValencyAttestationError,
	isEmojiDescription,
	isEnglishValencyAttestation,
	isFusedMember,
	isFusion,
	isGermanAdpositionAttestation,
	isGermanClosedClassSurface,
	isGermanDeterminerCore,
	isGermanNounSurface,
	isGermanPronounCore,
	isGermanValencyAttestation,
	isGermanVerbalAttestation,
	isGermanVerbalSurface,
	isHebrewValencyAttestation,
	isNounArticleAttestation,
	nonEmptyFeatureBagError,
	normalizeEmojiDescription,
	normalizeForm,
	nounArticleAttestationError,
} from "../src/validation/semantics.js";

export const registrations = [
	{
		construct: "custom",
		implementation: isGermanVerbalSurface,
		error: germanVerbalSurfaceError,
		name: "dumling.de-verbal.surface",
		version: 1,
	},
	{
		construct: "custom",
		implementation: isGermanVerbalAttestation,
		error: germanVerbalAttestationError,
		name: "dumling.de-verbal.attestation",
		version: 4,
	},
	{
		construct: "custom",
		implementation: isGermanAdpositionAttestation,
		error: germanAdpositionAttestationError,
		name: "dumling.de-adposition.attestation",
		version: 2,
	},
	{
		construct: "custom",
		implementation: isGermanValencyAttestation,
		error: germanValencyAttestationError,
		name: "dumling.de-valency.attestation",
		version: 2,
	},
	{
		construct: "custom",
		implementation: isHebrewValencyAttestation,
		error: hebrewValencyAttestationError,
		name: "dumling.he-valency.attestation",
		version: 1,
	},
	{
		construct: "custom",
		implementation: isEnglishValencyAttestation,
		error: englishValencyAttestationError,
		name: "dumling.en-valency.attestation",
		version: 1,
	},
	{
		construct: "custom",
		implementation: isGermanNounSurface,
		error: germanNounSurfaceError,
		name: "dumling.de-noun.surface",
		version: 3,
	},
	{
		construct: "custom",
		implementation: isNounArticleAttestation,
		error: nounArticleAttestationError,
		name: "dumling.noun-article.attestation",
		version: 1,
	},
	{
		construct: "custom",
		implementation: isFusion,
		error: fusionError,
		name: "dumling.fusion",
		version: 1,
	},
	{
		construct: "custom",
		implementation: isFusedMember,
		error: fusedMemberError,
		name: "dumling.fused-member",
		version: 1,
	},
	{
		construct: "custom",
		implementation: isGermanPronounCore,
		error: germanPronounCoreError,
		name: "dumling.de-pronoun.core",
		version: 1,
	},
	{
		construct: "custom",
		implementation: isGermanDeterminerCore,
		error: germanDeterminerCoreError,
		name: "dumling.de-determiner.core",
		version: 1,
	},
	{
		construct: "custom",
		implementation: isGermanClosedClassSurface,
		error: germanClosedClassSurfaceError,
		name: "dumling.de-closed-class.surface",
		version: 1,
	},
	{
		construct: "custom",
		implementation: hasMarkedFeature,
		error: nonEmptyFeatureBagError,
		name: "dumling.feature-bag.marked",
		version: 1,
	},
	{
		construct: "custom",
		implementation: isEmojiDescription,
		error: emojiDescriptionError,
		name: "dumling.emoji-description",
		version: 1,
	},
	{
		construct: "overwrite",
		implementation: normalizeForm,
		name: "dumling.normalize-form",
		version: 1,
	},
	{
		construct: "overwrite",
		implementation: normalizeEmojiDescription,
		name: "dumling.normalize-emoji-description",
		version: 1,
	},
] as const satisfies readonly ZodValidationOperationRegistration[];
