import type { ZodValidationOperationRegistration } from "dumval/compiler";
import {
	articleAttestationError,
	comparabilitySurfaceError,
	emojiDescriptionError,
	englishValencyAttestationError,
	foreignSurfaceError,
	fusedMemberError,
	fusionError,
	germanAdpositionAttestationError,
	germanClosedClassSurfaceError,
	germanDeterminerCoreError,
	germanNounSurfaceError,
	germanPronounCoreError,
	germanValencyAttestationError,
	germanVerbalAttestationError,
	germanVerbalSurfaceError,
	hasMarkedFeature,
	hebrewValencyAttestationError,
	isArticleAttestation,
	isComparabilitySurface,
	isEmojiDescription,
	isEnglishValencyAttestation,
	isForeignSurface,
	isFusedMember,
	isFusion,
	isGermanAdpositionAttestation,
	isGermanClosedClassSurface,
	isGermanDeterminerCore,
	isGermanNounSurface,
	isGermanPronounCore,
	isGermanValencyAttestation,
	isGermanVerbalAttestation,
	isGermanVerbalSurface,
	isHebrewValencyAttestation,
	isSayingCanonicalForm,
	isVariantTagCombination,
	isVariantTagList,
	nonEmptyFeatureBagError,
	normalizeEmojiDescription,
	normalizeForm,
	sayingCanonicalFormError,
	variantTagCombinationError,
	variantTagListError,
} from "../src/validation/semantics.js";

export const registrations = [
	{
		construct: "custom",
		implementation: isComparabilitySurface,
		error: comparabilitySurfaceError,
		name: "dumling.comparability.surface",
		version: 1,
	},
	{
		construct: "custom",
		implementation: isGermanVerbalSurface,
		error: germanVerbalSurfaceError,
		name: "dumling.de-verbal.surface",
		version: 1,
	},
	{
		construct: "custom",
		implementation: isGermanVerbalAttestation,
		error: germanVerbalAttestationError,
		name: "dumling.de-verbal.attestation",
		version: 4,
	},
	{
		construct: "custom",
		implementation: isGermanAdpositionAttestation,
		error: germanAdpositionAttestationError,
		name: "dumling.de-adposition.attestation",
		version: 2,
	},
	{
		construct: "custom",
		implementation: isGermanValencyAttestation,
		error: germanValencyAttestationError,
		name: "dumling.de-valency.attestation",
		version: 2,
	},
	{
		construct: "custom",
		implementation: isHebrewValencyAttestation,
		error: hebrewValencyAttestationError,
		name: "dumling.he-valency.attestation",
		version: 1,
	},
	{
		construct: "custom",
		implementation: isEnglishValencyAttestation,
		error: englishValencyAttestationError,
		name: "dumling.en-valency.attestation",
		version: 1,
	},
	{
		construct: "custom",
		implementation: isGermanNounSurface,
		error: germanNounSurfaceError,
		name: "dumling.de-noun.surface",
		version: 5,
	},
	{
		construct: "custom",
		implementation: isArticleAttestation,
		error: articleAttestationError,
		name: "dumling.article.attestation",
		version: 1,
	},
	{
		construct: "custom",
		implementation: isForeignSurface,
		error: foreignSurfaceError,
		name: "dumling.foreign.surface",
		version: 1,
	},
	{
		construct: "custom",
		implementation: isFusion,
		error: fusionError,
		name: "dumling.fusion",
		version: 1,
	},
	{
		construct: "custom",
		implementation: isFusedMember,
		error: fusedMemberError,
		name: "dumling.fused-member",
		version: 1,
	},
	{
		construct: "custom",
		implementation: isGermanPronounCore,
		error: germanPronounCoreError,
		name: "dumling.de-pronoun.core",
		version: 1,
	},
	{
		construct: "custom",
		implementation: isGermanDeterminerCore,
		error: germanDeterminerCoreError,
		name: "dumling.de-determiner.core",
		version: 1,
	},
	{
		construct: "custom",
		implementation: isGermanClosedClassSurface,
		error: germanClosedClassSurfaceError,
		name: "dumling.de-closed-class.surface",
		version: 1,
	},
	{
		construct: "custom",
		implementation: hasMarkedFeature,
		error: nonEmptyFeatureBagError,
		name: "dumling.feature-bag.marked",
		version: 1,
	},
	{
		construct: "custom",
		implementation: isSayingCanonicalForm,
		error: sayingCanonicalFormError,
		name: "dumling.saying.canonical-form",
		version: 1,
	},
	{
		construct: "custom",
		implementation: isEmojiDescription,
		error: emojiDescriptionError,
		name: "dumling.emoji-description",
		version: 1,
	},
	{
		construct: "custom",
		implementation: isVariantTagList,
		error: variantTagListError,
		name: "dumling.variant-tags.order",
		version: 1,
	},
	{
		construct: "custom",
		implementation: isVariantTagCombination,
		error: variantTagCombinationError,
		name: "dumling.variant-tags.combination",
		version: 1,
	},
	{
		construct: "overwrite",
		implementation: normalizeForm,
		name: "dumling.normalize-form",
		version: 2,
	},
	{
		construct: "overwrite",
		implementation: normalizeEmojiDescription,
		name: "dumling.normalize-emoji-description",
		version: 1,
	},
] as const satisfies readonly ZodValidationOperationRegistration[];
